### ISSUE TITLE
The method Long2DoubleArrayMap(Map<Long,Double>) is undefined

### ISSUE THREAD

**Issue by vspinu** [vigna/fastutil#10]
The following simple program doesn't compile in JDK8 with eclipse:

```
import java.util.HashMap;
import java.util.Map;

public class Test {
	public static void main(String[] args) {
		Map<Long, Double> map = new HashMap();
		System.out.println(Long2DoubleArrayMap(map));
	}
}
```

As the [documentation](http://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/longs/Long2DoubleArrayMap.html) states there should be a constructor for `Long2DoubleArrayMap(Map<? extends Long,? extends Double> m)`. 

I am probably missing something very basic. Newbe here. 

Thanks

**Comment by szarnekow** [comment]
Is it just the missing `new` keyword? This should work: `System.out.println( new  Long2DoubleArrayMap(map));`

**Comment by vspinu** [comment]
Oh. I am such a doofus. It's not the first time I miss  that part :(   Thanks!
