### ISSUE TITLE
Test sources should be in a separate jar

### ISSUE THREAD

**Issue by trejkaz** [vigna/fastutil#100]
Currently, test sources end up in the sources jar. This means that, for instance, when you're in a project which depends on fastutil and search for usages of legacy JUnit APIs, hits on fastutil appear in the results, even though the test classes themselves are not packaged in the binary jar.

If the test sources are to be packaged into a jar at all, I think it should be in a separate one from the rest of the sources.

(Witnessed in v8.1.1)

**Comment by vigna** [comment]
OK. So I could have two sources jar, probably, one with the main stuff and another with the tests (but I never tried this). Which legacy APIs do you refer to?

**Comment by vigna** [comment]
Oh I see. There's a new JUnit 5 out. "She never sleeps".

**Comment by vigna** [comment]
I pulled out the test sources. In time, I'll create a separate project.
