### ISSUE TITLE
Figure out a way to split the monolithic JAR into smaller modules

### ISSUE THREAD

**Issue by lgoldstein** [vigna/fastutil#102]
Very nice work - one concern though - to quote

>> Note that the jar file is huge, due to the large number of classes

Indeed, we are currently looking at ~18 MB. While there are solutions that would allow us to extract only the classes we actually need (+ their dependencies), I wonder if it would possible to have several _Maven_ artifacts - e.g. by "subject":

* `fastutil-core` - code that is required by the other artifacts
* `fastutil-collections`
* `fastutil-maps`
* `fastutil-arrays`
* `fastutil-io`
* etc.

Note that it is quite acceptable to have some dependencies "tree" between the artifcats - e.g., perhaps `fastutil-collections` requires `fastutil-arrays`- of course, without cyclic dependencies ....

**Comment by gaul** [comment]
Perhaps fastutil could provide a mechanism to export an implementation as a single java file?  In my application, I only want to use `LongOpenHashSet` and plan to copy it into my repo.

**Comment by lgoldstein** [comment]
I cannot speak for the developers of this project, but I believe that providing a mechanism for extracting specific classes (and the code that supports them) is not within the scope of this project as it is a rather complex/tricky/delicate (choose your adjective ...) issue. That is why when I suggested this issue I proposed a "gross" division as it seems more feasible. That being said, IMO the more granularity the better - e.g., perhaps `fastutil-collections` could be sub-divided into:

* `fastutil-collections` - common collection support code
* `fastutil-lists` - only `List`-s related code
* `fastutil-sets` - onle `Set`-s related code

**Comment by incaseoftrouble** [comment]
@gaul You might want to look into [proguard](https://www.guardsquare.com/en/products/proguard). By `-keep`ing specific classes you can easily create a shrinked jar - you may also let proguard figure out which classes of fastutil your application needs and create one shaded jar. I'm using this in a project to shrink the resulting jar from ~25mB (mostly by fastutil) to ~2mB (fastutils share are a few hundred kB)

@lgoldstein The staggering size of fastutil mostly is a result of _all_ primitives being included and thus all their combinations in the binary objects, like maps. If one only includes the basic primitives int, long, and double (did I forget one?) the size already goes down to ~2mb. I remember having a "fastutil-min" target, which did exactly that, but I can't find the code - I can search it . I do think this is would be the right way to go - maybe have two independent, self-contained artifacts.

I think there is little merit from having a finer granularity in this particular case. Quite a lot of larger utility libraries seem to follow this philosophy, for example, guava is also shipping one big jar (yes, there are also some which split their stuff). Storage is incredibly cheap and maintaining granularity is a real pain, especially with the infrastructure of fastutil. When you are developing for a somehow limited platform (Android), you should probably use a minimizer anyway.

**Comment by AhmetBilgin** [comment]
I would like to see fastutil splitted into more modular artifacts in order to reduce the library size. I my case I'm using tablesaw-core library which is about 500KB in size and it's size is bloated because of fastutil beeing such a big dependency (~18MB). 

In the meantime proguard could be a feasible solution.

Please see my ticket in the tablesaw issue-tracker:
- [https://github.com/jtablesaw/tablesaw/issues/537#issue-455223719](url)
