### ISSUE TITLE
performance of ObjectArrayList.addAll()

### ISSUE THREAD

**Issue by kno10** [vigna/fastutil#105]
This part contains optimizations (arraycopy, avoiding resizing) that should be made available also for non-primitive lists.
https://github.com/vigna/fastutil/blob/192ce83affa4a6f2ad34a96c15b5f2ec2929cf1c/drv/ArrayList.drv#L508-L542

**Comment by vigna** [comment]
Mmmh. Yeah, I think you're right.

**Comment by kno10** [comment]
We noticed this when benchmarking `list.addAll` for different implementations, because the JDK implementation as well as Eclipse worked significantly better.

**Comment by vigna** [comment]
Fixed in 6a778fa5b. There's now some additional infrastructure for adding similar methods for big lists. 

Sorry it took a while...
