### ISSUE TITLE
Queues (TreeSet, PriorityQueue) missing functions compared to java (also inconsistencies)

### ISSUE THREAD

**Issue by Speiger** [vigna/fastutil#106]
Hello. I am really new to FastUtil. I am reading since a couple days the classes that i might want to use to replace them with.

And the library is great (just missing maybe a "Light version") but every now and then i run into issue where a lot of "Nessesary" functions are missing.
These are also not just some "Oh ok thats no problem" functions that you can replace, its actually really essential functions that are really nessesary.

Ok to list them:

- Priority Queues miss a "Remove" function that allows to remove a lot of "OutOfOrder" indexed Values. Which is actually a really nessesary function for example if you want to make a "Mapped Memory Manager" where you keep track of the holes. (I use that in combo with OpenGL to keep track of my data)
- TreeSets Misses funny enough the poll/pop functions for the first/last entry which basically makes them really inperformant if you want to use them in the same way as a PriorityQueue. 

And thats just some random stuff i found which i wanted to replace with this library. Lucky for me the Java versions of those things are equal in memoryUsage, but it is still a shame that this is missing.

After researching more i found that "LinkedMaps" have exactly those features (same with the Stack.class implementations) even so that this should be present in the treesets/priorityqueues.
Its a bit inconsistent in some areas which is what i am trying to tell. (Also THANK GOD that you added a first & last function to linkedMaps)

I hope that this bugreport helps a bit, and i am sorry for my bad language.

Speiger.

**Comment by vigna** [comment]
You're right in saying that the NavigableSet/Map primitives should be implemented in fastutil. But it takes time. The remove function in the first item: I don't know what you mean. If you want to be able to remove many elements, you must use an indirect queue, or there's no way to specify the elements. In this case, it's already implemented. If you are talking about a standard queue, that does not make any sense, for there is no simple way to find the elements in the queue: your best bet is to build a new queue with the remaining elements. But please tell me if I misunderstood.

**Comment by Speiger** [comment]
- (TreeSet) yeah thats something that would be nice to see these functions being added.
- (PriorityQueue) What i mean is that the priorityQueues are missing a "remove" function to remove a object that may no longer be valid. Yes the PrimitiveArrayIndirectPriorityQueue has that feature and i totally did miss that, still that is the only one that has that feature. For stuff like a "DataManager" that keeps track of a Buffers contents is sometimes essential, since you may want to get rid of useless entries to save memory. (In my large tests i keep track of right now 16 Million Buffer entries inside of the GPU with that system).
Here is the system that uses that in a private gist.
https://gist.github.com/Speiger/2950c6d098b274a268cf6e68b9e04017
(I am referring the ensureEndEmpty function which is called in the clearEmptySlots function)
(This system uses 40 bytes per entry in my buffer it keeps track of. (Instanced OpenGL buffers) which is a lot but i have found no way to improve it)

Also i had this close because i thought ok, he might not seem it nessesary or something like that so lets close it because i personally hate having issues open and i dont want to bother.

Thanks for the answer ^^" should i reopen it?
