### ISSUE TITLE
Arrays.parallelQuickSort should use common ForkJoinPool

### ISSUE THREAD

**Issue by shevek** [vigna/fastutil#107]
Arrays.parallelQuickSort creates a new FJP every time, which means that an unknown number of threads is running on the system. Please can you either use FJP.commonPool() or expose the ForkJoinGenericQuickSort as public so that I can submit it to FJP.commonPool()?

**Comment by vigna** [comment]
I didn't know about commonPool(). I guess I could use it by default and have an additional method which let you pass another FJP. How does that sound?

**Comment by vigna** [comment]
OK, that's embarrassing—I completely forgot about this.  Commit da93cf279150cf3eda7ea372d8d9bfc8997e1c04 should fix this.

**Comment by shevek** [comment]
Thank you. Having the ability to use our own FJP would be a bonus as we don't use the common pool, but at least this is better for most people.
