### ISSUE TITLE
NPE in Reference2ReferenceOpenHashMap

### ISSUE THREAD

**Issue by hanma0** [vigna/fastutil#109]
In line #505 the variable "wrapped" gets accessed but may not have been initialized resulting in a NullPointerException. Its only occassion it gets initialized seems to be the method shiftKeys(int) which may not have been called.

Encountered in fastutil-8.2.2

**Comment by sirati97** [comment]
i encountered that once as well. was caused by a multithreading race condition

**Comment by vigna** [comment]
Yes. That's always the cause.
