### ISSUE TITLE
implementation of OpenHashMap.trim( final int n ) seems wrong

### ISSUE THREAD

**Issue by CAT-Solstice** [vigna/fastutil#110]
In current implementation of `public boolean trim(final int n)` in `OpenHashMap`, there is a conflict between method argument `n` and field member `this.n`. The argument should be renamed or a `this.n` should be used to disambiguate.

**Comment by vigna** [comment]
OMG I don't know how I missed this. Fixed. Can you give me a name for thanking you in the CHANGES file?
