### ISSUE TITLE
Why *2*OpenHashMap ergodic performance is not as good as java.util.HashMap

### ISSUE THREAD

**Issue by jiayaoguang** [vigna/fastutil#111]
When I test large-capacity map traversal, the performance is several times worse than that of java.util.HashMap.

Code:
> Int2IntLinkedOpenHashMap = new Int2IntLinkedOpenHashMap (1024*1024);
for
 (int i = 0; i < 1024 * 64; i + +) {
       map.put (i, i);
}
for (int i = 0; i < 100; i + +) {
        // For (Int2IntMap. Entry entry: map. int2IntEntrySet (){
        for (int key: map. keySet (){
}

**Comment by vigna** [comment]
If you create a map with more than a million slots and then put in 65536 integers, yes, it'll be slow. Why would you do that, it's the real question.
