### ISSUE TITLE
nio buffers ?

### ISSUE THREAD

**Issue by jonenst** [vigna/fastutil#114]
Have you considered writing replacements for nio buffers like you did for big arrays and big lists ?
Cheers,
Jon

**Comment by vigna** [comment]
Sigh. Yes, but that would be a *lot* of work. The only thing I implemented is this class

http://dsiutils.di.unimi.it/docs/it/unimi/dsi/util/ByteBufferLongBigList.html

in dsiutils that memory maps a large region multiplexing through several ByteBuffer instances.

**Comment by jonenst** [comment]
Thanks for the quick response and the pointer !
