### ISSUE TITLE
Serialization/Deserialization tests should use different files so they can be run in parallel

### ISSUE THREAD

**Issue by techsy730** [vigna/fastutil#119]
Right now, all the serialization and deserialization tests write/read to a file with the same name for all tests, "it.unimi.dsi.fastutil.test". This makes it so that if you run multiple tests in parallel (which is desirable because of how many tests there are, both JUnit and runnable main()), they will conflict with each other and corrupt each others' serialization file.

This should be changed to have a different file name for each test. Perhaps something like "it.unimi.dsi.fastutil.test." + thingToBeSerialized.getClass().getSimpleName()? That won't make it unique for each test method, but it does make it unique for each test class, which is a significant improvement.

**Comment by vigna** [comment]
Good idea. A pull request? ;)
