### ISSUE TITLE
Infinite loop in trim(n) when n < size()

### ISSUE THREAD

**Issue by ikabiljo** [vigna/fastutil#12]
This code produces infinite loop:
    IntOpenHashSet set = new IntOpenHashSet();
    set.add(1);
    set.add(2);
    set.add(3);
    set.trim(1);

while it shouldn't rehash the set at all.

**Comment by vigna** [comment]
Oh well, that's embarassing. The same bug was fixed months ago for trim(), but I completely forgot that there was also a trim(int) method. Thank you!
