### ISSUE TITLE
Provide unsafe internal state getter

### ISSUE THREAD

**Issue by paplorinc** [vigna/fastutil#123]
Since this library is mostly used for its' speed, it would be a good idea to provide unsafe array getters for the internal state, i.e. without copies.

Example:
```java
    LongArrayList longs = new LongArrayList();
    longs.add(1);
    System.out.println(Objects.hash(longs.toArrayUnsafe()));
```

**Comment by vigna** [comment]
Ahem... elements() ?

**Comment by paplorinc** [comment]
You're right, my mistake, the `LongList` interface confused me. :)
Thank you!
