### ISSUE TITLE
ensureCapacity on empty ArrayList

### ISSUE THREAD

**Issue by eparejatobes** [vigna/fastutil#125]
``` scala
val xs = new ByteArrayList()
xs.ensureCapacity(10)
xs.elements().length // = 0 (!!)
```

--
*related to #85*

**Comment by vigna** [comment]
Yes, it's lazy. Add an element and retry.

**Comment by eparejatobes** [comment]
I'd argue then that this is a bit confusing

``` scala
val xs = new ByteArrayList(10)
xs.elements().length // = 10
xs.ensureCapacity(20)
xs.elements.length() // = 20
```

specifying a capacity *without having added anything* sometimes leads to growth/allocation of the backing array, sometimes not. I think it'd simpler if `ensureCapacity` would always allocate/grow.

**Comment by vigna** [comment]
This is how the JDK does it.
