### ISSUE TITLE
sort(Comparator) overload on lists with specialized comparator

### ISSUE THREAD

**Issue by JakeWharton** [vigna/fastutil#129]
I was expecting to find methods like
```
interface IntList {
  default void sort(IntComparator c) {
    sort((Comparator<Integer>) c);
  }
}
```
on each specialized list. With the built-in subtypes offering actual implementations.

Right now it's _very_ easy to call `sort(Collections.naturalOrder())` and get destroyed by boxing.

**Comment by vigna** [comment]
But that would imply implementing a sort for each kind of list (!). If you need to sort an array-based list, just sort l.elements() from 0 to l.size()...

**Comment by JakeWharton** [comment]
Would it? You should be able to re-use the `Arrays` int-based sort for everything except longs. It would only need a new version for longs.

For `IntList` you can implement it entirely in the default method as something like:
```java
default void sort(IntComparator c) {
  Arrays.sort(0, size(), IntSwapper.instance(), c);
}
```

For everything else except longs, you can still use the int sort with a swapper and comparator wrapper that widens (although it shouldn't actually widen because they're all ints in the JVM once on the stack).

For longs you'd do that same as ints, but with a new long-based sort with a long swapper and long comparator.

**Comment by vigna** [comment]
Oh, you're right. I'm going this now.

**Comment by JakeWharton** [comment]
Can you re-open the bug so that I can track when it's closed?

And thanks for working on this!

**Comment by vigna** [comment]
It has actually been done by @techsy730 . Should be out now on Maven (or clone the repository). Let me know if it works for you...

**Comment by JakeWharton** [comment]
Oh that's even better. Thanks again!
