### ISSUE TITLE
Android: desugar fails for Reference2DoubleMap

### ISSUE THREAD

**Issue by stari4ek** [vigna/fastutil#136]
Android build toolchain fails to desugar 0.8.3:
```
> Task :app:transformClassesWithDexBuilderForDevDebug
AGPBI: {"kind":"error","text":"One or more instruction is preventing default interface method from being desugared: java.lang.Double it.unimi.dsi.fastutil.objects.Reference2DoubleMap.getOrDefault(java.lang.Object, java.lang.Double)","sources":[{"file":"/Users/astar/.gradle/caches/modules-2/files-2.1/it.unimi.dsi/fastutil/8.3.0/742307990505e3a149c9c60825ffc1db5ceef02e/fastutil-8.3.0.jar"}],"tool":"D8"}
AGPBI: {"kind":"error","text":"One or more instruction is preventing default interface method from being desugared: java.util.Comparator it.unimi.dsi.fastutil.floats.FloatComparator.thenComparing(java.util.Comparator)","sources":[{"file":"/Users/astar/.gradle/caches/modules-2/files-2.1/it.unimi.dsi/fastutil/8.3.0/742307990505e3a149c9c60825ffc1db5ceef02e/fastutil-8.3.0.jar"}],"tool":"D8"}
org.gradle.workers.WorkerExecutionException: There were multiple failures while executing work items
	at org.gradle.workers.internal.DefaultWorkerExecutor.workerExecutionException(DefaultWorkerExecutor.java:301)
	at org.gradle.workers.internal.DefaultWorkerExecutor.await(DefaultWorkerExecutor.java:276)
...
Caused by: com.android.tools.r8.utils.AbortException: Error: /Users/astar/.gradle/caches/modules-2/files-2.1/it.unimi.dsi/fastutil/8.3.0/742307990505e3a149c9c60825ffc1db5ceef02e/fastutil-8.3.0.jar:it/unimi/dsi/fastutil/floats/FloatComparator.class, One or more instruction is preventing default interface method from being desugared: java.util.Comparator it.unimi.dsi.fastutil.floats.FloatComparator.thenComparing(java.util.Comparator)
	at com.android.tools.r8.utils.Reporter.a(:21)
	at com.android.tools.r8.utils.Reporter.a(:7)
	at com.android.tools.r8.utils.t.a(:36)
	... 36 more
```

**Comment by vigna** [comment]
OMG. I have literally no idea of what this is. Can you elaborate?

**Comment by stari4ek** [comment]
when fastutil 8.* added to android project with
```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
there is special step during build to "desugar" java 8 code. So java 8 features would work on older jvm android is limited to.
Here is info about Android Java 8 support: https://developer.android.com/studio/write/java8-support

And all those lambdas/default interface methods/etc usually "just work".

Not sure if it's "too magic" on _fastutil_ side with this specific default interface methods implementations or _D8_ issue.

**Comment by vigna** [comment]
I'd try to pass this into the maintainers of the "desugar" code—fastutil is just compiled with target=1.8...

**Comment by zeroleak** [comment]
same issue here since gradle update to 3.5.1

**Comment by liuyibox** [comment]
any update on this issue? I got stuck into this issue since I upgrade the android studio to 3.6. The java version remains at 1.8.

**Comment by stari4ek** [comment]
Still valid for `8.3.1` with:
```
classpath 'com.android.tools.build:gradle:3.6.3'
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
```

One or more instruction is preventing default interface method from being desugared: java.lang.Double it.unimi.dsi.fastutil.objects.Reference2DoubleMap.getOrDefault(java.lang.Object, java.lang.Double)
```

**Comment by vigna** [comment]
Once again, I totally have no idea :(.

**Comment by stari4ek** [comment]
Yeah, but I do not see any issues created for d8/r8 team referenced here.

> I'd try to pass this into the maintainers of the "desugar" code—fastutil is just compiled with

**Comment by zerny** [comment]
A D8 issue has been filed for this and should be resolved soon: https://issuetracker.google.com/issues/157806261

FYI, the issue is a failure to rewrite the call from default method override to the default method in the library, in this case the default interface method CharConsumer.andThen forwarding to the default library method Consumer.andThen.

**Comment by stari4ek** [comment]
To anyone, who stuck with some old agp (and r8 from it):
```
buildscript {
    repositories {
        maven {
            url = uri("https://storage.googleapis.com/r8-releases/raw")
        }
    }

dependencies {
    classpath("com.android.tools:r8:8.11.18")
}
```

Using most recent R8 fixes desugaring issues.
