### ISSUE TITLE
FIFOQueue needs readAccess and BaseInterfaces need expansions

### ISSUE THREAD

**Issue by Speiger** [vigna/fastutil#138]
FIFOQueue is so far my most loved and most hated class in this library.
It is a very good and very bad linkedlist replacement.

I know removing out of the FIFOQueue is not a good idea and would be slower then a linked list.

Ok finally to get to the issue.
I try to use the FIFO queue as a linkedlist replacement whereever I can.
But as soon as "StateSaving" or "Caching" comes into play then the FIFOQueue fails because I have to basically empty&fill the queue just to see its contents. (In other words, drain = doTask = fillBackIn)
A simple: get(int index) would be really useful and allow at least to be used in without having to do this annoying iterator.

Sorry if that is a bad rant. FastUtil is amazing but a lot of its Qualities fail usually at some very basic stuff that is like pretty useful.
Like: AddAndMoveToFirst? or addTo all these functions are in their respective "Classes"
So Object2IntMap<Example> can not be used as the leftside. You have to use Object2IntOpenHashMap<Example> map = new Object2IntOpenHashMap<Example> to access these functions.
Why have Object2IntMap if most of the times you can not really use that interface because all the "REALLY usefull functions are not in there".

Also something that would be nice (recently landed on that crash) is that ObjectArrayLists could be used with a "ClassConstruction" as constructor so you dont have to do: ObjectArrayList.wrap(new BufferedImage[0], 0) just so if you access the backarray that you don't get a ClassCastException?

Again sry for rambling thats just something I noticed ^^"

Edit making a simple list now:
- [ ] FIFOQueue needs read Access with get function
- [ ] Specialized functions like "AddTo" in maps, or getElements() in List should be in the "FastUtil Interfaces" too so you can actually use the interface classes
- [ ] ObjectLists have to use WrapFunctions to allow type control.
- [ ] Maybe a good linkedList replacement? (Queues are not really ment to be used for that)
- [ ] Also this: #128
- [ ] In general increase usability.

**Comment by vigna** [comment]
As a general note: try to write in English. Or have a person re-reading your text and making itlook like English. I'll try to answer what I can understand from the characters you typed.

- For FIFO queues, one possibility could be a peek() method, similar to that of stacks, that returns the k-th object that would be returned. Or an iterator returning the contents of the queue without modifying it. That is not difficult to implement, and you could try a pull request.

- The second comment is entire nonsense. Object2IntMap is an interface, and it cannot contain methods that are bound to a specific implementation. Try to read, say, the GoF classic or similar books on software design. Your ideas about that are very confused.

- The third comment is completely incomprehensible.

- NavigableMaps would be great! Waiting for a pull request :).

**Comment by Speiger** [comment]
Oh yeah my language skills (not english only) in terms of typing are not good.
I am aware of that and already working on that but its not easy.

* FIFO Queue: Yes I can see the first and last index. But what if I have 200 indexes and I want to save it. Right now if that the case. Drop FIFO queue and use a linkedlist, because of the "dequeue, process, enqueue" thing. (I am going to answer to pullrequest at the end to make it easier)

* Ok you didnt get the point because I was horrible at explaining it: The function "addTo" is something thata Any2NumberOpenHashMap contains (same for linked). Why is this function not in the Any2NumberMap interface? Because thats like something every map would have anyways. If not, then exception, because most maps use that feature. 
About the linkedSpecific functions, yeah that maybe could be its own interface even so that would just increase the class count massivly. (Good point against that)

* Third Point: When I  create a ObjectArrayList and read its array and then try to have reference,
For example:
```
public void crashTest()
{
	ObjectArrayList<BufferedImage> images = new ObjectArrayList<BufferedImage>();
	functionToReadImages(images);
	BufferedImage[] rawArray = images.elements(); //This crashes because its a ObjectArray. It can not cast it.
}

public void nonCrashTest()
{
	ObjectArrayList<BufferedImage> images = ObjectArrayList.wrap(new BufferedImage[0]);
	functionToReadImages(images);
	BufferedImage[] rawArray = images.elements(); //This works perfectly fine. Because it knows that its wrapped and keeps the class Type.
}
```
I hope this explains the issue a lot better. It would be nice if there would be another constructor that does not require the wrap function and does this automatically. (if you provide a class or if that constructor wouldn't be needed in the first place though performance might be an issue. Dunno)

* Navigateable maps would be gread.

* Pull Requests. Do they have to be Drv classes? Or is there a way to create drv classes out of normal classes? or can you(me in this case) also pullrequest normal java classes? 
Because I am not sure how that system works. And I would like to add to the system at least a bit if I can.

I hope my language skill got at least a little bit better now that my head is a bit more clear. And I hope I was able to explain to you what I meant^^"

**Comment by vigna** [comment]
* OK, there might be a login in having an addTo() to maps towards numbers. It could be implemented by default methods.

* I don't understand what's wrong with wrapping. Please explain. It's just a factory method instead of a constructor. I can't see the difference. This is clearly explained in the class documentation.

* Yes, pull requests must be .drv files and you must learn the game first.

**Comment by Speiger** [comment]
* Ok.
* elements function feature will be only useful if the ObjectArrayList uses "Object.class" or if you use the wrap function because else it will crash because of CastClassExceptions. Not sure if that is seen as bug or not. But it may should be mentioned in the documentations that that is requirement for "ObjectArrayLists".
* Ok, so it might take a bit of time before I can even attempt making patches. Thanks for that info.

Even if this sounded bad or something like that: This library is epic. But it has its own quirks that confuse me sometimes ^^"

**Comment by vigna** [comment]
Once again: Java's ArrayList allocates Object arrays. The wrap thing is an extension of fastutil, and it *has* to be something the user is aware of (via the `wrap()` method) because reallocating by type is *much, much, much slower*.

Thank you for the appreciation! :)
