### ISSUE TITLE
Lists should never be equal to sets

### ISSUE THREAD

**Issue by cdman** [vigna/fastutil#14]
See test here: https://github.com/gpanther/fastutil-guava-tests/blob/97fda/src/test/java/net/greypanther/fastutil/tests/IntArrayListTest.java#L88

This is again caused by the fact that IntLists.EMPTY_LIST inherits equals from AbstractIntCollection.

Regards,
Attila

**Comment by vigna** [comment]
Fixed. Also in other classes (e.g., EMPTY_SET).
