### ISSUE TITLE
[Question] What does the ReferenceMap do?

### ISSUE THREAD

**Issue by Speiger** [vigna/fastutil#140]
I looked at a Long2ReferenceOpenHashMap map and compared it to the Long2ObjectOpenHashMap.

These two classes look almost the same. Only difference the name.
So my question. What does it do? Because the ReferenceMap & ObjectMap implementations of code is 100% equal.

Could you enlighten me?

**Comment by vigna** [comment]
The value() collection has equality by reference in the first case, by value in the second case.

**Comment by Speiger** [comment]
Ok thanks.
