### ISSUE TITLE
Deserialized OpenHashMap can hang forever in containsKey and get

### ISSUE THREAD

**Issue by andy-clegg** [vigna/fastutil#147]
_Legal text required by my employer: "Not a Contribution"_

It seems that if you serialize an OpenHashMap, then deserialize it, key lookup can go into an infinite loop.

Simple test case:

```java
import it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

public class FastUtilMapTest {

    public static void main(String[] args) throws Exception {
        Long2ObjectOpenHashMap<String> map1 = new Long2ObjectOpenHashMap<>(8, 1.0f);
        map1.put(13L, "13");
        map1.put(15L, "15");
        map1.put(10L, "10");
        map1.put(14L, "14");
        map1.put(16L, "16");
        map1.put(18L, "18");
        map1.put(17L, "17");
        map1.put(11L, "11");
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        ObjectOutputStream oos = new ObjectOutputStream(baos);
        oos.writeObject(map1);
        oos.flush();
        oos.close();
        ByteArrayInputStream bais = new ByteArrayInputStream(baos.toByteArray());
        ObjectInputStream ois = new ObjectInputStream(bais);
        Long2ObjectOpenHashMap<?> map2 = (Long2ObjectOpenHashMap<?>) ois.readObject();
        System.out.println(map1.containsKey(12L));
        System.out.println(map2.containsKey(12L));
    }

}
```

This will print `false` once and then hang, spinning a CPU at 100%. Tested with 8.3.1.

It looks like the `mask` field might be calculated wrongly on deserialization -- for `map1` it's 15, but for `map2` it's 7. I don't know how dependent this is on the size, fill factor, etc., or the specifics of the keys -- this particular size and key set happened to trigger it for me.

**Comment by vigna** [comment]
Seriously? Load factor 1?

**Comment by andy-clegg** [comment]
Sorry, could you elaborate on that answer please?

According to [these docs](http://fastutil.di.unimi.it/docs/), load factor is in the range 0 < f ≤ 1.

Our use case is maps that are pre-allocated to a certain size, populated, serialized, sent across the wire, deserialized, and then never mutated. Our objective is to minimize space used. If 1 is the incorrect load factor for this use case, I'm happy to hear what a more sensible value would be! Pardon my ignorance here.

In any case, this is a map which is configured with valid values according to the docs, and yet, goes into an infinite loop when queried. How is that not a bug?

**Comment by andy-clegg** [comment]
> Our use case is maps that are pre-allocated to a certain size, populated

To clarify: we know in advance the number of items we're going to insert into the map, so we never want it to grow beyond its initial capacity.

Isn't f=1 the correct setting in this case?

**Comment by vigna** [comment]
OMG, I *really* wrote that? 😂

**Comment by andy-clegg** [comment]
Seems that way :) Under Memory Usage -> Hash Tables.

**Comment by vigna** [comment]
That must have been the first release, somewhere the end of the '90s. An &le; slipped in place of an &lt;.

An open hash table cannot—physically have a load factor of 1. Items are found by scanning the backing array until an empty slot is found. If there are no empty slots, you'll get an infinite loop.

Moreover, the probabilistic analysis (see Knuth) that proves that the average number of probes when you look for an element is constant works only if the load factor is away from one. That's why the default load factor is 0.75.

I should probably even test it in constructors.

Thank you for the report, I just updated the docs.

**Comment by vigna** [comment]
When you use the constructor with the number of elements and the load factor, you get a map that will never resize up to that number of elements. What is the load factor is irrelevant—the backing array will be sized properly. You have to decide the tradeoff between space and time.

**Comment by andy-clegg** [comment]
Actually the constructor is wrong too:

```java
		if (f <= 0 || f > 1) throw new IllegalArgumentException("Load factor must be greater than 0 and smaller than or equal to 1");
```

https://github.com/vigna/fastutil/blob/master/drv/OpenHashMap.drv#L254

**Comment by vigna** [comment]
OK, so I _really_ had that idea. I'll fix, that, too. LOL.

**Comment by vigna** [comment]
That was, like, 22 years ago. 🙈

**Comment by andy-clegg** [comment]
For our use case, what would you recommend? Leave the default f or set it to something close to 1? Or doesn't it really matter?

**Comment by incaseoftrouble** [comment]
FYI Java's fixed size immutable maps (obtained with `Map.of()`) uses a load factor of 0.5 despite knowing the size in advance.

The closer you choose your load factor to one the closer to linear time access you will get. If you are fine with x2 space requirement, use an appropriate load factor. If you really want to save space and are fine with log(n) access, a tree map should be the most compact representation with sub-linear access I guess?

**Comment by vigna** [comment]
Well, no, tree maps have very large object overheads. And access is not expected constant.

0.5 is definitely faster than 0.75, but it also means you're using more memory and at some point you'll get more cache misses, which are really bad. I'd suggest benchmarking—no predictive model will work here.

**Comment by andy-clegg** [comment]
Thanks! I'll experiment.

**Comment by incaseoftrouble** [comment]
Sorry for the bump.
@andy-clegg I forgot that I actually implemented exactly this already, compatible with fastutil interfaces :) https://github.com/incaseoftrouble/naturals-util/blob/master/src/main/java/de/tum/in/naturals/set/IntArraySortedSet.java

The `Int2DoubleSortedArrayMap(int capacity)` exactly allocates `capacity` many items.
