### ISSUE TITLE
[Suggestion] Primitive EnumMaps

### ISSUE THREAD

**Issue by Speiger** [vigna/fastutil#148]
EnumMaps have quite the usecases because they are lower on memory usage and also are quite fast.
(ofc it is not linked)
Sadly they require the use of Objects and primitives are not supported. Yes a Byte2PrimitiveMap could be used on the other hand you are forced to cast and still work with 2 arrays. Enums are usually below 64 entries so arrays would be slower.

Only a suggestion.

**Comment by shevek** [comment]
We would very much appreciate an Enum2IntArrayMap.

**Comment by Speiger** [comment]
Darn couldn't you have waited like a week or two? I almost had them together. I am finishing of the Navigatable set right now xD

**Comment by magneticflux-** [comment]
I don't think these are implemented, could we get a reason for the denial? I have an enum with < 20 members that I could easily put in a an array by ordinal manually, but I'd like to have a structured way with all the niceties of the Collections API instead of "rolling my own".

The existing `EnumMap` in Java works okay, but it has a lot of unnecessarily defensive code for large enums or passing in non-enum objects since it's so old.

**Comment by vigna** [comment]
Why can't you use a reference- based map?

**Comment by magneticflux-** [comment]
I'd preferably like to be able to index into the map with the ordinals of the enum, hence why I clarified a "dense" enum map. As far as I know, all existing maps maintain two arrays and do a linear scan if they don't use the hash of the key.

**Comment by vigna** [comment]
Yes, I agree it would be technically better. If you put together a PR I'll be happy to review it.

**Comment by Marcono1234** [comment]
Another advantage of such maps compared to <code>Object2<i>Primitive</i></code> is that they would have consistent ordering (similar to Java's `EnumMap`). `Enum.hashCode()` uses the identity hash code and therefore with the hash based maps you would get arbitrary ordering which could be different for subsequent runs.

However, enums may also have a large number of constants (such as [`Character.UnicodeScript`](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/Character.UnicodeScript.html) with currently 157 constants). Maybe there is a point at which it would be more efficient to use a <code>Byte2<i>Primitive</i>Map</code> internally (which somehow also keeps enum ordinal ordering?)? In that case a factory method choosing the best fitting implementation would be useful, e.g. `enumMapFor(Class<E> enumClass)`.

One issue might be mapping back ordinal to enum constant; Java's `EnumSet` and `EnumMap` have access to the internal `values` array of the enum without having to copy it; this would not be possible for fastutil (unless reflection is used, but this will not work well with the Java Platform Module System). So maybe each enum map instance would have to maintain a copy of the enum `values` array.
