### ISSUE TITLE
[Feature Request] AVL & RB TreeSet should have "removeFirst/Last" methods

### ISSUE THREAD

**Issue by Speiger** [vigna/fastutil#149]
Smaller sub request of "Navigable Sets" in the Todo-List that would be easier to implement but already help a lot.
the functions removeFirst/Last. Getter already exists just remove is missing.

I could make a attempt patch for it but is that a good idea or should we wait for someone to do Navigable stuff?

I wanted to first get your info in that vigna.

Thanks for reading

**Comment by vigna** [comment]
Well, the navigable stuff is really far in time. If you wanna provide two working methods with unit tests, you're welcome!

**Comment by Speiger** [comment]
Yeah I can try

**Comment by Speiger** [comment]
@vigna I know this is a lot to ask. But is there any step by step instruction for how to actually generate the sourcecode of fastutil or to check it through a compiler?
Never worked with a script like that and there isn't anything on the wiki itself either.

It would really help and also allow me to actually "test" my attempts at making tests.

**Comment by Speiger** [comment]
You are 1 week to early with that xD
