### ISSUE TITLE
replaceAll is not deprecated in Int2ObjectOpenHashMap

### ISSUE THREAD

**Issue by develar** [vigna/fastutil#150]
I migrate from Trove to fastutil and I don't see easy alternative to `TIntObjectHashMap .transformValues`.

JDK 8 provides `replaceAll`. Issue is that this method is not deprecated and no efficient direct alternative. Default `replaceAll` is not good because `iterator` instead of `fastIterator` is used.

**Comment by vigna** [comment]
Mmmh. I don't think we have anything like that.

**Comment by develar** [comment]
Hmm... things are more complicate than I thought. Another issue here is that fastutil doesn't support `BiFunction<Integer, Object, Object>` (avoid generic).

Thanks for quick reply, I realised that no need to use replaceAll and fastutil provide better way:

```java
for (Int2ObjectMap.Entry<Bar> entry : Int2ObjectMaps.fastIterable(lineToRenderer)) {
  entry.setValue(new Bar());
}
```

or, in Kotlin, to avoid extra iterable wrapper:

```
for (entry in lineToRenderer.int2ObjectEntrySet().fastIterator()) {
  entry.setValue(Bar())
}
```
