### ISSUE TITLE
ArrayIndexOutOfBoundsException: null in LongArrayList.toArray()

### ISSUE THREAD

**Issue by anthonylouisbsb** [vigna/fastutil#151]
The LongArrayList method is throwing this exception regularly, even inside a synchronized block:
`java.lang.ArrayIndexOutOfBoundsException: null
    at it.unimi.dsi.fastutil.longs.LongArrayList.toArray(LongArrayList.java:428)`

The method that thrown it was _System.arraycopy()_ from Java standard lib. Do you know how to solve this issue? When I execute the command alone the error never happened, just when running with many threads.

**Comment by vigna** [comment]
Please provide a unit test that shows the bug in the last version.
