### ISSUE TITLE
[Optimization] List.removeElements should check if elements get deleted from the end

### ISSUE THREAD

**Issue by Speiger** [vigna/fastutil#152]
I wanted to use removeElements to speed up a interruptable taskqueue.
(Basically iterate over all tasks and if interrupted to use removeElements to removeElements as needed)
Sadly removeElements does automatically do a Arraycopy no matter where you start.
It should look like something like this:
```java
@Override
public void removeElements(final int from, final int to) {
	it.unimi.dsi.fastutil.Arrays.ensureFromTo(size, from, to);
	if(to != size - 1)
		System.arraycopy(a, to, a, from, size - to);
	size -= (to - from);
	int i = to - from;
	while (i-- != 0)
		a[size + i] = null;
}
```

Also isn't this a bug?

```java
public static void ensureFromTo(final int arrayLength, final int from, final int to) {
	if (from < 0) throw new ArrayIndexOutOfBoundsException("Start index (" + from + ") is negative");
	if (from > to) throw new IllegalArgumentException("Start index (" + from + ") is greater than end index (" + to + ")");
	if (to > arrayLength) throw new ArrayIndexOutOfBoundsException("End index (" + to + ") is greater than array length (" + arrayLength + ")");
}
```
The to > arrayLength. Shouldn't it be to >= arrayLength?

@vigna I can try to fix this (with a patch) but can you explain to me how to generate source so I can test my patches? (because running the gencsource script does not work for me (noob with such scripts))

**Comment by vigna** [comment]
As in all of Java, from is inclusive and to is not. So your code is wrong. Also your bug report is wrong—a to parameter equal to the list size is perfectly fine. If size == to, System.arrayCopy() does nothing. Your test is just a waste of time.

**Comment by Speiger** [comment]
Yep my mistake
