### ISSUE TITLE
Info request

### ISSUE THREAD

**Issue by Speiger** [vigna/fastutil#153]
Hello to Everyone who reads this. Maybe even @vigna.

I want to help with this project. Make improvements etc.
I have no issue with working with drv files and do all these edits even if there is no compiler help.

What I have an issue with is test the code because there is no real instructions/tutorial on how to actually generate the source code.
What this issue is about is very simple. Please provide a instruction list/tutorial how to generate these things.
If there is a difference between linux and windows and mac then provide instructions how to do these.

Why am i requesting this help?
Very simple. There is some requirements to write tests & test them. Ensure code is actually working.
Which has to be done A either in the head or B not at all. 
This is prone to cause errors or mistakes in the code that may be not found.

The single requirement:
Make them easy and simple to understand so that someone who has never worked with sh scripts & make-files before can understand them. Because right now you need actual experience to know what to do to do simple exporting of the source code.

Also the Wikisection is great for such things.

Thanks for reading.
Speiger

**Comment by Speiger** [comment]
Non of these things exist @incaseoftrouble 
only executable files are gencsource.sh, find-deps.sh and test.sh (which throws errors without end)
and these files do not even work.
(I am working with windows10)

**Comment by incaseoftrouble** [comment]
Uhm no. I just cloned the repo to double check (windows 10 with cygwin) and sources are generated just fine with `make sources` (you may need to run `dos2unix` if your git checks out CRLF). `Makefile` is not executable since the `make` command them. Yes you need a linux environment (like [cygwin](https://www.cygwin.com/) or WSL, not sure if the latter works though) but thats a five minute install

**Comment by Speiger** [comment]
From what I was told (and it could be wrong or I missunderstood it) that this could be used on Win10 but I would have to start up a linux environment run the make source and then close the environment.
Then check if everything was working (well i could keep it open).

Is that correct?

Also. It would be nice if there would be a instruction list of what to do, because not everyone who can program is knowing linux well enough to make this connection to understand what to do.
(I had to ask a couple friends before i knew that linux was required even if only some assisted software)

**Comment by incaseoftrouble** [comment]
I don't get the point. The readme tells you that you need to "make source". So you `make source`, thats the whole instruction list.

If you don't have make, you need to install it. If you really want to work on Windows, you can install cygwin. I guess we can add a sentence on this in the README but I don't think Windows users are the target audience in any case.

**Comment by Speiger** [comment]
Ok and how do i "make sources"? Is it a CommandLine command? Is it a Gradle Task? Also if it is a command what arguments do i need to supply?
Again never worked with this and this is like compiled machinecode to me.

**Comment by incaseoftrouble** [comment]
Yes, `make` is a command line tool, probably the most established build automation tool out there. I recommend learning more about `make`, its one of the essential build tools. The argument you need to supply to make is `sources`. So, together you get `make sources`.

On windows, the process is (untested):
 * Setup a linux environment (for example, cygwin or WSL) (google provides help -> "windows install cygwin")
 * Install the respective build packages containing make (google provides help -> "cygwin install make")
 * Open this environment (for cygwin: open the cygwin console)
 * Go to the fastutil folder (cygwin: via `cd`)
 * Run `make sources` by typing these words and pressing enter.

**Comment by Speiger** [comment]
Thank you for the help.

**Comment by Speiger** [comment]
@incaseoftrouble ok I managed to get through the process and I have the make folder included (latest version that the installer was able to find)
But when executing Make sources (with a clean copy of fast util and no changes made)
this error appears
```
$ make sources
./gencsource.sh drv/Iterable.drv src/it/unimi/dsi/fastutil/booleans/BooleanIterable.c >src/it/unimi/dsi/fastutil/booleans/BooleanIterable.c
./gencsource.sh: Zeile 2: $'\r': Kommando nicht gefunden.
./gencsource.sh: Zeile 9: $'\r': Kommando nicht gefunden.
./gencsource.sh: Zeile 12: $'\r': Kommando nicht gefunden.
./gencsource.sh: Zeile 15: $'\r': Kommando nicht gefunden.
./gencsource.sh: Zeile 18: $'\r': Kommando nicht gefunden.
./gencsource.sh: Zeile 21: $'\r': Kommando nicht gefunden.
./gencsource.sh: Zeile 24: $'\r': Kommando nicht gefunden.
./gencsource.sh: Zeile 27: $'\r': Kommando nicht gefunden.
./gencsource.sh: Zeile 30: $'\r': Kommando nicht gefunden.
./gencsource.sh: Zeile 33: $'\r': Kommando nicht gefunden.
./gencsource.sh: Zeile 36: $'\r': Kommando nicht gefunden.
): No such file or directoryarnung: setlocale: LC_ALL: Kann die Locale nicht ändern (C
: Ungültiger Shell Optionen Name. extglob
./gencsource.sh: Zeile 39: $'\r': Kommando nicht gefunden.
./gencsource.sh: Zeile 69: Syntaxfehler beim unerwarteten Wort `$'do\r''
'/gencsource.sh: Zeile 69: `for((k=0; k<${#TYPE_CAP[*]}; k++)); do
make: *** [makefile:130: src/it/unimi/dsi/fastutil/booleans/BooleanIterable.c] Fehler 2
```
Basically a lot of "Command not found" errors and syntax errors.

Any idea what to do?

**Comment by incaseoftrouble** [comment]
You checked out the sourcecode with git autocrlf (your files have windows line endings `\n\r`, cygwin expects unix line endings `\n`). Runing `dos2unix gencsource.sh` should fix the problems (not sure about the Locale problem though, we'll have to see)

**Comment by Speiger** [comment]
That seems to do something.

**Comment by Speiger** [comment]
@incaseoftrouble it generates the JavaFiles but all Java files are empty. Nothing in there.
this is the log:
```
$ make sources
cc -w -I. -DSMALL_TYPES=1   -DASSERTS_VALUE=false -E -C -P src/it/unimi/dsi/fastutil/booleans/BooleanIterable.c \
        | sed -e '1,/START_OF_JAVA_SOURCE/d' -e 's/^ /  /' >src/it/unimi/dsi/fastutil/booleans/BooleanIterable.java
/bin/sh: cc: Kommando nicht gefunden.

./gencsource.sh drv/Iterable.drv src/it/unimi/dsi/fastutil/bytes/ByteIterable.c >src/it/unimi/dsi/fastutil/bytes/ByteIterable.c
cc -w -I. -DSMALL_TYPES=1   -DASSERTS_VALUE=false -E -C -P src/it/unimi/dsi/fastutil/bytes/ByteIterable.c \
        | sed -e '1,/START_OF_JAVA_SOURCE/d' -e 's/^ /  /' >src/it/unimi/dsi/fastutil/bytes/ByteIterable.java
/bin/sh: cc: Kommando nicht gefunden.

./gencsource.sh drv/Iterable.drv src/it/unimi/dsi/fastutil/shorts/ShortIterable.c >src/it/unimi/dsi/fastutil/shorts/ShortIterable.c
cc -w -I. -DSMALL_TYPES=1   -DASSERTS_VALUE=false -E -C -P src/it/unimi/dsi/fastutil/shorts/ShortIterable.c \
        | sed -e '1,/START_OF_JAVA_SOURCE/d' -e 's/^ /  /' >src/it/unimi/dsi/fastutil/shorts/ShortIterable.java
/bin/sh: cc: Kommando nicht gefunden.

./gencsource.sh drv/Iterable.drv src/it/unimi/dsi/fastutil/chars/CharIterable.c >src/it/unimi/dsi/fastutil/chars/CharIterable.c
cc -w -I. -DSMALL_TYPES=1   -DASSERTS_VALUE=false -E -C -P src/it/unimi/dsi/fastutil/chars/CharIterable.c \
        | sed -e '1,/START_OF_JAVA_SOURCE/d' -e 's/^ /  /' >src/it/unimi/dsi/fastutil/chars/CharIterable.java
/bin/sh: cc: Kommando nicht gefunden.
```

**Comment by incaseoftrouble** [comment]
you cygwin needs a c / c++ compiler. install build-essential package or similar

**Comment by Speiger** [comment]
Also thanks for the help and your time.

**Comment by Speiger** [comment]
![image](https://user-images.githubusercontent.com/2556269/84439059-d2522900-ac37-11ea-92a0-e7530fb2eab3.png)
These are "Build" Packages that I have

**Comment by Speiger** [comment]
@incaseoftrouble ok almost everything went right.
Only Problem is that I have around 430 Java errors because the "Linked" Variants of the code weren't generated.

**Comment by incaseoftrouble** [comment]
I think this might be due to LinkedXY & CustomXY actually being symlinks which cannot be mapped properly on windows file systems? I'm not sure though. What should work is that you manually copy the symlinks.

If you check out https://github.com/vigna/fastutil/tree/master/drv some of the files have a "symlink" mark. (Linked* and OpenCustom*). Click the linked files to see which file they are linked to. On your repo, replace the link with the linked file. For example, [`OpenCustomHashMap.drv`](https://github.com/vigna/fastutil/blob/master/drv/OpenCustomHashMap.drv) is linked to `OpenHashMap.drv`. You should copy `OpenHashMap.drv` over the `OpenCustomHashMap.drv` file. Do this for all 6 symlinks and `make sources` again, this should work I think.

**Comment by Speiger** [comment]
Oh so just a copy paste code of the drv files would be enough. That sounds a lot easier then my idea.

Thanks for the help.

I hope this was the last time i have to do this.

**Comment by Speiger** [comment]
Thanks @incaseoftrouble that was the last of the issues.

(I will try to make a sum up tutorial for others so that this issue won't show up again)
