### ISSUE TITLE
Object2ObjectArrayMap(Map) works in a worst manner (put is used under the hood)

### ISSUE THREAD

**Issue by develar** [vigna/fastutil#154]
I use Object2ObjectArrayMap as a snapshot of map (for iteration).
I expect that `new Object2ObjectArrayMap(Map)` will be fast as `new Object2ObjectArrayMap<>(Map.keySet().toArray(), Map.values().toArray())`

but performance issue is that 

```
	public Object2ObjectArrayMap(final Object2ObjectMap<K, V> m) {
		this(m.size());
		putAll(m);
	}
```

where `putAll` calls `put` and `put` does linear search.

I fully understand purpose of this map implementation, but still I do not see any reason why this constructor cannot be implemented in an efficient manner.

**Comment by vigna** [comment]
Please provide benchmarks.

**Comment by develar** [comment]
I don't think that benchmark is needed here, as it is clear that `put` uses `findKey` and by design search is linear.  Nothing to measure :)

> just put them into two parallel arrays and scan linearly to find an item.

If you
<img width="1522" alt="Screenshot 2020-05-20 at 07 42 39" src="https://user-images.githubusercontent.com/350686/82409425-02117500-9a6e-11ea-9f41-f061fdf56883.png">
 wonder what for in this case I use `Object2ObjectArrayMap`:

```
    List<Map.Entry<Node, Collection<Node>>> list;
    synchronized (map) {
      list = new ArrayList<>(map.entrySet());
      map.clear();
    }
    // use list
```

This code works for java, but not when `map` here is `Object2ObjectOpenHashMap`. Because opposite to java, `clear` clears not only map, but also returned entry set.
So, as solution, I returns iterator of entries (I cannot expose fastutil to clients).


```
public @NotNull Iterator<? extends Map.Entry<K, Collection<V>>> fastEntrySetSnapshot() {
    if (isEmpty()) {
      return Collections.emptyIterator();
    }
    else {
      // Object2ObjectArrayMap(map) calls linear put under the hood, so, use toArray.
      return new Object2ObjectArrayMap<K, Collection<V>>(myMap.keySet().toArray(), myMap.values().toArray()).object2ObjectEntrySet().fastIterator();
    }
  }
```

**Comment by vigna** [comment]
You're entirely talking nonsense.

**Comment by develar** [comment]
@vigna Could you please explain? Just take a look on Object2ObjectArrayMap. Where I am wrong?

**Comment by vigna** [comment]
Oh God. ARRAY map. I didn't even see it.

**Comment by vigna** [comment]
You are right in that the copy constructors could iterate over the map entries and build two arrays. I do not think that anywhere in the Java specification the toArray() of keys and values has any constraint on the number of returned elements, so your first solution won't work. But iterating over the entries and filling will. Seems a decent thing to do, I'll implement it and you can test it.

**Comment by develar** [comment]
> How large is the map?

To clarify — I migrate IntelliJ ultimate/community project from Trove to fastutil.  In some cases I fully rework client code to suit a new API, in some cases preserve as is.

As commended above, the same code that works with java map, doesn't work with fastutil implementation:

> This code works for java, but not when multiMap.map here is Object2ObjectOpenHashMap. Because opposite to java, clear clears not only map, but also returned entry set.

So, after migration to fastutil, tests started to fail because of NPE, as `entry.getValue()` started to returns `null`. As I don't think that it is a bug in fastutil, I decided to change client code.
Just return iterator of entries, where iterator it is fast iterator of some map.
As I want to reduce code on my side, I decided to just use `Object2ObjectArrayMap`, as I need only iterator from it.

So, map size doesn't matter. I just use `Object2ObjectArrayMap` as a convenient way to get fast iterator of entries.

One of the reason why we migrated from Trove to fasutil —  project is not dead . I can submit pull request, but first I want to understand that I don't overlooked something.

**Comment by vigna** [comment]
OK, I implemented better constructors. Please have a try. (Sorry, I didn't have time for unit tests—later this day).

The same think might be done for sets, but one needs additional constructors, because Collection instances might return the same element twice. This cannot happen with an instance of Map.

**Comment by incaseoftrouble** [comment]
@develar Just FYI: `map.clear()` is required to clear the `entrySet()` aswell (i.e. `var set = map.entrySet(); map.clear(); assert set.isEmpty();` has to hold, because `entrySet()` is a view on the map. However, the entries themselves are copied by the list construction. The problem rather is that I guess you used `fastEntrySet()`. `new ArrayList<>(map.fastEntrySet())` doesn't make sense, since the "fast entries" are actually a single mutable object. Simply using `map.entrySet()` should be sufficient. I might be wrong though, then it would be interesting to see the code which went wrong.

**Comment by develar** [comment]
> However, the entries themselves are copied by the list construction. The problem rather is that I guess you used fastEntrySet()

Thanks for information, but please see implementation of `Object2ObjectLinkedOpenHashMap.MapEntry` class — 

```
@Override
		public V getValue() {
			return value[index];
		}
```

So, even if `new MapEntry(nextEntry())` a new instance of entry is created, still, on map clear all entries will returns `null` as value and key.
