### ISSUE TITLE
Support fixed size ArrayFIFOQueue

### ISSUE THREAD

**Issue by victornoel** [vigna/fastutil#156]
Hi,

I'm looking for a primitive-based circular buffer implementation, and it seems to me that `ArrayFIFOQueue` corresponds to this need with just one caveat: it's not of fixed size.

Would it be relevant to have some option for the `ArrayFIFOQueue` so that it doesn't grow bigger than a given size?

**Comment by vigna** [comment]
Er... and then? What should happen if you add an element and you need to enlarge? An exception? If so, why don't you check whether you have reached the capacity and throw an exception?

**Comment by victornoel** [comment]
@vigna sorry, I wasn't very clear. since my objective is to have a circular buffer, if I add an element at the beginning and there is no more space, I throw away the element at the end (or the opposite).

**Comment by incaseoftrouble** [comment]
That violates a lot of collections API ... Since its fixed sized it shouldn't be hard to just directly implement it I guess though.

**Comment by victornoel** [comment]
But maybe actually, a completely different class could be introduced for that... the idea is that once you've allocated the array, you can always add elements without moving the rest or re-allocate the array. See https://en.wikipedia.org/wiki/Circular_buffer

**Comment by vigna** [comment]
Definitely, but an overwriting buffer (i.e., you lose elements without even knowing it) is so specialized that it is not worth a specific implementation. I can hardly think of a use case (I'm sure you have one tho).

**Comment by vigna** [comment]
BTW, what I would do is subclassing, say, IntArrayFIFOQueue and replace the dequeue()enqueue() and dequeueLast() enqueueFirst() methods. In some case the modification are absolutely trivial (e.g., for dequeue you just need to skip the call to reduce()).

**Comment by victornoel** [comment]
@vigna ok, that's helpful, thank you!
