### ISSUE TITLE
Allow to reset iterators

### ISSUE THREAD

**Issue by xxDark** [vigna/fastutil#157]
Is it possible to add support for fastutil to reset already existing iterator?
For example:
```Java
 private final ObjectIterator<Object2FloatMap.Entry<K>> iterator;

// .....
ObjectIterator<Object2FloatMap.Entry<K>> iterator = this.iterator;
while (iterator.hasNext()) { /* code */ }
iterator.reset();
// ....
while (iterator.hasNext()) { /* code */ }
iterator.reset();
// ...
```

Thanks!

**Comment by incaseoftrouble** [comment]
Question: How does this differ from recreating the iterator instead of resetting / why would you want that? Performance or do you not want to pass the underlying collection? In the latter case, you could simply pass a `Supplier<Iterator<TYPE>>` with `() -> map.iterator()`.

**Comment by vigna** [comment]
Same question here. It is such a small, short-lived object that frankly the overhead of having to learn yet another interface quirky method that's different from java.util does not seem worth the performance improvement.

**Comment by xxDark** [comment]
Yes, for performance reasons.
Let's say I have immutable Object2FloatLinkedOpenHashMap<K>, and I need to create iterator only once to iterate over it's entry set, however, right now I have to do that each time.

**Comment by vigna** [comment]
And it shows up in JMH or similar benchmarks? You must be really doing nothing with those operators...

**Comment by incaseoftrouble** [comment]
Creating the object vs. resetting it probably is more or less the same operation (note that resetting it does not come for free either! In both cases you are calling a method, which probably is much slower than all the underlying memory allocations). We are talking nanosecond differences here.

It shouldn't be hard to manually add this reset operation and profile the differences.
