### ISSUE TITLE
RemoveAll should remove all occurrences of a given element from the collection 

### ISSUE THREAD

**Issue by cdman** [vigna/fastutil#16]
From the documentation: https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html#removeAll-java.util.Collection- (emphasis added):

"Removes **all** of this collection's elements that are also contained in the specified collection (optional operation). After this call returns, **this collection will contain no elements in common with the specified collection**."

This currently doesn't work for Lists where they only remove the first occurrences (the same seems to be true for BigLists). See tests at https://github.com/gpanther/fastutil-guava-tests/blob/37b76e/src/test/java/net/greypanther/fastutil/tests/IntArrayListTest.java#L68

A quick glance seems to indicate that the problem is that the method is implemented at AbstractXXXCollection level where it calls "rem" in a loop. Probably the solution would be to add "remAll" methods (both boxed and unboxed versions) at the collection level and call those from AbstractXXXCollection (for sets for example rem and remAll can contain identical implementations).

Regards,
Attila

**Comment by vigna** [comment]
This will take a little bit more to fix. :)

**Comment by vigna** [comment]
Fixed!
