### ISSUE TITLE
ReferenceArrayList::elements returns K[]

### ISSUE THREAD

**Issue by user11681** [vigna/fastutil#163]
Attempting to assign the array turned by `ReferenceArrayList::elements` to `K[]`—or anything else other than `Object[]`—causes a `ClassCastException` because `Object[]` cannot be cast to anything except `Object[]`, so either `elements` should return `Object[]` instead or the element array should actually be a `K[]`.

**Comment by vigna** [comment]
Please read the class documentation.

**Comment by user11681** [comment]
I understand now. Thank you.
