### ISSUE TITLE
Collectors

### ISSUE THREAD

**Issue by Arham4** [vigna/fastutil#166]
Collectors should be made so that one may use FastUtil Collections to collect streams. For example:
```JAVA
    public static <T> Collector<T, ?, ObjectList<T>> toList() {
        return Collector.of(ObjectArrayList::new, ObjectList::add, (left, right) -> {
            left.addAll(right);
            return left;
        });
    }
```
would allow the following:
```java
ObjectList<Foo> list = Stream.of(1, 2, 3).map(num -> new Foo(num)).collect(FastUtilCollectors.toList());
```
The only current alternative is to do:
```java
ObjectList<Foo> list = new ObjectArrayList<>(Stream.of(1, 2, 3).map(num -> new Foo(num)).collect(Collectors.toList()));
```
This alternative is not an efficient way to tackle the problem.

I'm willing to make the Collector methods if needed.

**Comment by vigna** [comment]
That's of course useful, but some classes/methods have three parameters, which would make the class number explode.

**Comment by Arham4** [comment]
Which one does, as an example (just for reference)?

**Comment by vigna** [comment]
Actually, we just merged in work from @techsy730 that implements collectors (albeit in each class, not in a IntCollectors class, say).
