### ISSUE TITLE
Feature request: type-specific functions composition remains type-specific

### ISSUE THREAD

**Issue by 16pierre** [vigna/fastutil#167]
👋 From what I read of the source code, `compose` and `andThen` in  `it.unimi.dsi.fastutil.Function` are inherited from `java.util.function`. 
Therefore, composing two type-specific functions returns a function that uses `apply()` instead of `get`, which means that we end up boxing/unboxing where we could remain in the type-specific world.

I'm wondering whether or not it'd be reasonable to override `compose` and `andThen` in this fashion:

```
// example with Int2FloatFunction
public interface Int2FloatFunction extends Function<Integer, Float>, java.util.function.IntToDoubleFunction {
	@Override
	default <V> java.util.function.Function<Integer, V> andThen(java.util.function.Function<? super Float, ? extends V> after) 
        {
		if (after instanceof Float2DoubleFunction) {
			Int2DoubleFunction composed = k -> ((Float2DoubleFunction) after).get(get(k));
			return (java.util.function.Function<Integer, V>) composed;
		}
                ...
	}
}

```

or at least have some composition utils between `fastutil` types (I found such utils in https://github.com/gridtec/lambda4j for example. If you know of other libraries that implement type-specific composition, glad to have your input !)

Thanks for this awesome library btw 😉

**Comment by vigna** [comment]
Seems entirely sensible to me. Do you wanna try a pull request?

**Comment by 16pierre** [comment]
I don't feel 100% confortable editing https://github.com/vigna/fastutil/blob/master/gencsource.sh + I'm no big C expert (especially not with this C->Java conversion) => this may take me way too much time to get this done, at least not without help

If you help me sketch how this would look like in https://github.com/vigna/fastutil/blob/master/gencsource.sh and how/if we'd want to test this, then I could try to write the actual PR.

**Comment by incaseoftrouble** [comment]
Note: You only need to edit the .drv files I think. Moreover, you don't need C knowledge. fastutil uses the C preprocessor to replace macros etc, but it is Java code nonetheless :-)

For example https://github.com/vigna/fastutil/blob/master/drv/AbstractFunction.drv is the base for the above code you posted. `KEY_VALUE_GENERIC` is replaced to `<Integer, Float>` for example.

**Comment by vigna** [comment]
Ahhh now I see the problem. The number of combinations is really bad. Well, we're used to large number of classes/methods in fastutil (I had to increase the Eclipse heap so many times..), so probably it's doable with the "fragment" approach. Let me think about it.

**Comment by vigna** [comment]
So, it was a bit of preprocessor bloodbath, but this is my first attempt:

https://github.com/vigna/fastutil/commit/50ec3e4b608748cf5c069f88bda12b01778c2ced

Note that this implements andThen/compose _between type-specific functions_, which seems to me the most interesting kind. I could also imagine a variant in which the argument is a standard Java function and we do some mild reflection to guess whether it's type-specific (as in your example). But it seems to me less interesting because we are doing in fact additional boxing and unboxing.

BTW, if anybody here is a C preprocessor wizard and can explain how to remove the ugly redundancy here

    COMPOSITION(KEY_TYPE_CAP, VALUE_TYPE_CAP, Byte, bytes, GET_AFTER(Byte), get, , KEY_GENERIC, VALUE_GENERIC, VALUE_GENERIC, KEY_GENERIC)

it would be great. Ideally, GET_AFTER() should be expanded _inside_ COMPOSITION() using the parameter T_C, and I've tried a few deferred evaluation tricks, without results. In this way it works but it's just ugly.

**Comment by vigna** [comment]
@16pierre , any comments?

**Comment by 16pierre** [comment]
Just tested the new API, looks great ! Thank you so much for your help 🙇 

> Note that this implements andThen/compose between type-specific functions, which seems to me the most interesting kind. I could also imagine a variant in which the argument is a standard Java function and we do some mild reflection to guess whether it's type-specific (as in your example). But it seems to me less interesting because we are doing in fact additional boxing and unboxing.

Indeed this sounds reasonable : the most important part is to be able to compose type-specific functions.
The use-case I saw for overriding `java.util's compose` was to be able to come back to type-specific functions after using a `java.util.Function` abstraction, without boxing. For example:

```
interface TransformerFactory {
     // Implementations could use type-specific functions under the hood
     Function<Integer, Float> getInt2FloatTransformer();
     Function<Float, Double> getFloat2DoubleTransformer();
}

class Foo {
     Int2DoubleFunction transformer;
     // could be type-specific

     public void bar(int param) {
         double result = typeSpecificFunction.get(param);
         ...
     }
}

public void main() {
        TransformerFactory factory = ...;        

        // convertToTypeSpecific returns either the underlying type-specific function,
        // either a type-specific wrapper around java.util.Function
        Int2DoubleFunction typeSpecificFunction = Int2DoubleFunction.convertToTypeSpecific(factory.getInt2FloatTransformer().andThen(factory.getFloat2DoubleTransformer()));
       Foo foo = new Foo(typeSpecificFunction);
       ...
}
```

This is definitely low-priority : you made the right call to only implement the type-specific composition.
Thank you again !

**Comment by vigna** [comment]
I'm getting a lot of these compiling:

warning: [overloads] andThen(Float2ByteFunction) in Boolean2FloatFunction is potentially ambiguous with andThen(Float2ShortFunction) in Boolean2FloatFunction

Just wondering if we should use some special name.

**Comment by 16pierre** [comment]
I don't have a strong opinion about this, fine with muting the warnings / type-specific names.

Maybe type-specific names like `andThenFloat`etc. could avoid some confusion, especially when inlining FunctionalInterfaces:
```
// unclear type inference for x->x*3 
someIntFunction.andThen(x -> x * 3)
// explicit intToFloat for x->x*3
someIntFunction.andThenFloat(x -> x * 3)
```

**Comment by incaseoftrouble** [comment]
I like this idea. Sort of in line with what JDK is doing with, e.g., `OptionalInt` etc.

**Comment by vigna** [comment]
I see now the point. Yes, there's a lot of possible ambiguity which might lead to a lot of casting.

**Comment by vigna** [comment]
OK, the last commit changes the names. That's backward-incompatible, but it has been just a few days.

**Comment by vigna** [comment]
Well, in any case comments are welcome!

**Comment by 16pierre** [comment]
Great thx a ton !
