### ISSUE TITLE
Collection<T> compatibility methods should take null parameter

### ISSUE THREAD

**Issue by cdman** [vigna/fastutil#17]
Since the collections declare that they implement the corresponding java.util.Collection interface (ie. IntSet implements Set<Integer>), they should handle nulls gracefully. See tests here:

https://github.com/gpanther/fastutil-guava-tests/blob/c16625d/src/test/java/net/greypanther/fastutil/tests/IntArrayListTest.java#L46
https://github.com/gpanther/fastutil-guava-tests/blob/c16625d/src/test/java/net/greypanther/fastutil/tests/IntArraySetTest.java

Ie. don't throw exception when .contains(null) is called (rather return false).

Note: throwing null for contains / containsAll / removeAll / retainAll IS allowed by the wording on collections (see https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html#retainAll-java.util.Collection- - "NullPointerException - if this collection contains one or more null elements and the specified collection does not permit null elements (optional), or if the specified collection is null") so perhaps the only thing needs fixing here is the equals method for sets (the second link in the above case). I only gave the example for IntArraySet but the same problem is exhibited by the other set implementations also.

Regards,
Attila

**Comment by vigna** [comment]
This has been fixed, hopefully without introducing subtle errors 😱
