### ISSUE TITLE
Code Generator can not detect #ifdef VALUE_CLASS_Char

### ISSUE THREAD

**Issue by Speiger** [vigna/fastutil#171]
When making my own FastUtil implementation i found out that VALUE_CLASS_Char is useless since it is wrongly defined in teh gensource.sh

so if anything that uses that predicate is basically not applied.

**Comment by vigna** [comment]
Fuck, this is so contorted it took me some time.

Your bug report should have been:

Maps with char values are missing the addToValue() method because the driver file mistakenly uses VALUE_CLASS_Char instead of VALUE_CLASS_Character.

**Comment by Speiger** [comment]
@vigna Yeah i know. I already fixed it but i wasn't sure if it was used somewhere else since it falls under the byte,short,char category.
