### ISSUE TITLE
[Feature Request] Iterable

### ISSUE THREAD

**Issue by Arthur-Milchior** [vigna/fastutil#174]
Would you accept that Maps become Iterable ? I would be willing to contribute to it if I understand the language.

I should emphasize that I perfectly understand that Sets, List, can't be Iterable because that would require to create objects, which is what we want to avoid in the first place. However, in the case of map, we are already creating an object to contains the pair Key/Value, it does not seems that having the map being iterable would add extra cost.

**Comment by incaseoftrouble** [comment]
I think the common way to iterate Maps is either `Map#entrySet()` or `Map#forEach(Consumer)`. Or do you have something different in mind?

**Comment by Arthur-Milchior** [comment]
Oh, my bad. I guess I misunderstood something. Seems perfect

**Comment by incaseoftrouble** [comment]
No problem, this library can be quite daunting at first :-)
