### ISSUE TITLE
 When calling toArray(T[]) the element after the last one should be null...

### ISSUE THREAD

**Issue by cdman** [vigna/fastutil#18]
if there is enough space in the passed-in array. Documented here: https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html#toArray-T:A-

"If this collection fits in the specified array with room to spare (i.e., the array has more elements than this collection), the element in the array immediately following the end of the collection is set to null. (This is useful in determining the length of this collection only if the caller knows that this collection does not contain any null elements.)"

Test showing that fastutil does not respect this: https://github.com/gpanther/fastutil-guava-tests/blob/bea3e/src/test/java/net/greypanther/fastutil/tests/IntArrayListTest.java#L30

Regards,
Attila

**Comment by vigna** [comment]
This has been fixed.
