### ISSUE TITLE
Bug in list iterator add

### ISSUE THREAD

**Issue by cdman** [vigna/fastutil#19]
I'm trying to add the battery of tests from Google Guava's testlib [1] to FastUtils and found the following discrepancy between ArrayList and (Byte)ArrayList (though I suspect that it's present in all of the *ArrayLists since they share the common template):

````java
  @Test
  public void testAddUsingIteratorToTheFirstPosition() {
    testAddUsingIteratorToTheFirstPosition_internal(new ArrayList<>());
    testAddUsingIteratorToTheFirstPosition_internal(new ByteArrayList());
  }

  private void testAddUsingIteratorToTheFirstPosition_internal(List<Byte> list) {
    list.add((byte)24);
    ListIterator<Byte> it = list.listIterator();
    it.add((byte)42);
    assertTrue(it.hasNext());
    assertEquals(Arrays.asList((byte)42, (byte)24), list);
  }
````

Ie. adding an element using the list iterator on the first position fails with IllegalStateException. The test also demonstrates that using ArrayList works as expected.

Regards,
Attila

PS. I will post other bugs I discover as I debug them.

**Comment by vigna** [comment]
This has been fixed.
