### ISSUE TITLE
Spliterators.concat.characteristics() should never return SORTED or DISTINCT even if all sub-spliterators do.

### ISSUE THREAD

**Issue by techsy730** [vigna/fastutil#190]
The SORTED and DISTINCT property do not combine.
For example: (assume there is a hypothetical `SortedSet.of`, which there isn't at the time of this writing)
```java
IntSortedSet s1 = IntSortedSet.of(1,2,3);
IntSortedSet s2 = IntSortedSet.of(1,4,6);
IntSpliterator split1 = s1.spliterator();
IntSpliterator split2 = s2.spliterator();
IntSpliterator combined = IntSpliterators.concat(split1, split2);
```

Now both split1 and split2 report NONNULL | SIZED | ORDERED | SORTED | DISTINCT as their characteristics.
As such, so does the combined spliterator.
But the combined spliterator will give the elements {1, 2, 3, 1, 4, 6}, and that is neither SORTED nor DISTINCT.

The fix is to make Spliterators.SpliteratorConcatenator#computeCharacteristics never set the SORTED or DISTINCT bits even if all child spliterators do.

**Comment by vigna** [comment]
What does the JDK do?

**Comment by techsy730** [comment]
The JDK actually had none of `Iterator`, `Spliterator`, or `Stream` concatenation functions. Guava does have Stream concatenation; I am taking a look at what they do now.

**Comment by techsy730** [comment]
Ok, so what Guava does is to only allow ORDERED | SIZED | NONNULL to be reported by the underlying concat'ed spliterator, and only if all sub-spliterators do as well.

I think that may be too restrictive for us (this implementation will correctly handle SUBSIZED for example).

**Comment by vigna** [comment]
I'd let you decide which properties filter to the concatenation—you wrote the code...
