### ISSUE TITLE
Iterator.remove throws on IntArraySet

### ISSUE THREAD

**Issue by cdman** [vigna/fastutil#20]
The following code throws an UnsupportedOperationException, even though it should remove the element (or should it? Is IntArraySet considered to be immutable? then again, it implements add/remove on the class level):

````java
    IntSet set = new IntArraySet(Arrays.asList(42));

    IntIterator iterator = set.iterator();
    assertTrue(iterator.hasNext());
    iterator.next();
    iterator.remove();
````

The stacktrace of the exception (with fastutil 7.0.10) is:

````
java.lang.UnsupportedOperationException
	at it.unimi.dsi.fastutil.ints.AbstractIntIterator.remove(AbstractIntIterator.java:66)
	at net.greypanther.fastutil.tests.IntArraySetTest.testRemoveFromIterator(IntArraySetTest.java:27)
...
````

**Comment by vigna** [comment]
Oh yeah. The array-based structures are a bit underimplemented. They were at that time a quick hack for very small collections in MG4J. I just I should implement that.

**Comment by vigna** [comment]
Oh I see. I just created an Iterator using the wrapping method.

**Comment by cdman** [comment]
IMHO a simple fix would be for the Iterator to call remove on IntArraySet.

**Comment by vigna** [comment]
Huh? The Iterator class I'm using is defined elsewhere. I'm trying to borrow the code and add a call to remove().

**Comment by vigna** [comment]
Incidentally, ArrayMaps have the same problem as all other maps with nulls. Fixed.

**Comment by vigna** [comment]
Fixed.
