### ISSUE TITLE
Fast question,Is there any backward compatibility guarentee.

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [vigna/fastutil#202]
Of course,fast util has existed for quite a long time.
I think Package it.unimi.dsi.fastutil,is probably safe to say that the api is fixed and time tested.

Just wonder if there are any explicit api or behaviour guarentee.
So one can have confidence that it will compile perfectly when swap to new version.

**Comment by vigna** [comment]
There haven't been any significant backward-incompatibke changes AFAIK, and we try to keep it what way.
