### ISSUE TITLE
Releasing 8.5.0

### ISSUE THREAD

**Issue by vigna** [vigna/fastutil#219]
I think things are ready for a release. The only open pull request needs a bit of work still, so I'd delay that to the next release (still Java 8), together with navigable sets/map. I'm going through open issues to see if there are low-hanging fruits deserving a fix. Any other proposal or comments for the upcoming 8.5.0 release should happen here. Thanks!

**Comment by dustContributor** [comment]
Thank you for your work!

**Comment by vigna** [comment]
8.5.0 is out and should be soon on Maven. 8.5.1 will be out soon—we'll get bug reports and there's #162 to pull in.
