### ISSUE TITLE
Missing emma_ant.properties referenced from build.xml

### ISSUE THREAD

**Issue by cdman** [vigna/fastutil#23]
A tiny issue: build.xml [references](https://github.com/vigna/fastutil/blob/4ca20158cc868aa314a97a14f6d3c95cce97ed1b/build.xml#L124) the missing `emma_ant.properties` around line 124 which prints the warning:

````
  [taskdef] Could not load definitions from resource emma_ant.properties. It could not be found.
````

**Comment by vigna** [comment]
I eliminated all references to emma—it's no longer developed.
