### ISSUE TITLE
Big Mutable Strings

### ISSUE THREAD

**Issue by sirinath** [vigna/fastutil#235]
Can mutable string added to FastUtils under the same license.

**Comment by vigna** [comment]
dsiutils is doubly licenced, there's no need for that.

**Comment by sirinath** [comment]
I missed the fact it has been re-licensed. Can the source be hosted on GitHub as well?

**Comment by vigna** [comment]
https://github.com/vigna/dsiutils

**Comment by sirinath** [comment]
OK Great. I guess you might need to update the website with the links as it still mentions downloading source as tarballs.

**Comment by sirinath** [comment]
Sorry I missed it. The 1st links is the GitHub link.

**Comment by vigna** [comment]
No, I just updated it LOL. You made me notice it was missing.

**Comment by sirinath** [comment]
Perhaps you can update this also "which are gathered for your convenience in a tarball." to "which are gathered for your convenience in a tarball and hosted in GitHub." as body of the text is what one looks at 1st. Also source and binary can link to GitHub releases so  it is not state. GitHub release is 8.5.2 and the download in the website is 2.6.17.

**Comment by sirinath** [comment]
The download version are not consistent for other projects also. E.g. webgraph 3.6.10 vs 3.6.8.

**Comment by sirinath** [comment]
Also some projects e.g. MG4J  do not have a GitHub link. Also they seam to be still LGPL (hopefully this can be changed).

**Comment by sirinath** [comment]
BUbiNG link in http://vigna.di.unimi.it/software.php is also broken.

**Comment by vigna** [comment]
You're right, there's too much duplication of information. I will stop distributing the tarballs, I think nobody is using them.

MG4J presently is not on Github. Maybe in the future, it takes time...

Thank you for the reports.
