### ISSUE TITLE
JavaDoc seems to be generating docs for only public elements, when they should be including protected ones

### ISSUE THREAD

**Issue by techsy730** [vigna/fastutil#236]
JavaDoc seems to be generating docs for only `public` elements, when they should be including `protected` ones.

For example, we have several protected abstract methods on abstract classes we need to document.

I think maybe the ant JavaDoc task needs to replace `public=1` with `protected=1`

**Comment by techsy730** [comment]
As this only is a documentation change, I don't think we need a 8.5.3 for this alone. Just commit the change and repush the docs on the fastutil website.

**Comment by vigna** [comment]
I think the point was that there are already si many methods. If someone wants to play with subclassing, it is easy to regenerate the docs. The final user has no interest in protected methods.
