### ISSUE TITLE
A lot of generated java files contain 'OpenHashMap.drv' / 'OpenHashSet.drv' string only

### ISSUE THREAD

**Issue by cheblin** [vigna/fastutil#237]
for example 

Byte2LongLinkedOpenHashMap.java contains string `OpenHashMap.drv` only
ByteOpenCustomHashSet.java - `OpenHashSet.drv`

**Comment by cheblin** [comment]
this is because these files contain only mentioned strings
![image](https://user-images.githubusercontent.com/29354319/107035583-570b3c00-67f3-11eb-9ee5-5e73eac990dd.png)

**Comment by incaseoftrouble** [comment]
not sure if I remember correctly but these are symlinks which windows (screenshot looks like windows) doesn't handle in the same way (NTFS has symlinks I think but they are hardly used)

**Comment by vigna** [comment]
Please replicate under a sensible OS (Linux, Mac OS X).

**Comment by cheblin** [comment]
ok. got it

What about replacing in the `makefile` strings:

`LinkedOpenCustomHashMap.drv` -> `OpenHashMap.drv`
`LinkedOpenCustomHashSet.drv` -> `OpenHashSet.drv`
`LinkedOpenHashMap.drv` -> `OpenHashMap.drv`
`LinkedOpenHashSet.drv` -> `OpenHashSet.drv`
`OpenCustomHashMap.drv` -> `OpenHashMap.drv`
`OpenCustomHashSet.drv` -> `OpenHashSet.drv`

I have done it, it works.
