### ISSUE TITLE
overridden method is final

### ISSUE THREAD

**Issue by cheblin** [vigna/fastutil#239]
> java: mergeDouble(K,double,it.unimi.dsi.fastutil.doubles.DoubleBinaryOperator) in it.unimi.dsi.fastutil.objects.Object2DoubleLinkedOpenCustomHashMap cannot override mergeDouble(K,double,it.unimi.dsi.fastutil.doubles.DoubleBinaryOperator) in it.unimi.dsi.fastutil.objects.AbstractObject2DoubleMap
>   overridden method is final

> java: mergeInt(K,int,it.unimi.dsi.fastutil.ints.IntBinaryOperator) in it.unimi.dsi.fastutil.objects.Object2IntLinkedOpenCustomHashMap cannot override mergeInt(K,int,it.unimi.dsi.fastutil.ints.IntBinaryOperator) in it.unimi.dsi.fastutil.objects.AbstractObject2IntMap
>   overridden method is final
> 

> java: mergeLong(K,long,it.unimi.dsi.fastutil.longs.LongBinaryOperator) in it.unimi.dsi.fastutil.objects.Object2LongLinkedOpenCustomHashMap cannot override mergeLong(K,long,it.unimi.dsi.fastutil.longs.LongBinaryOperator) in it.unimi.dsi.fastutil.objects.AbstractObject2LongMap
>   overridden method is final

problems in files:

_Object2DoubleLinkedOpenCustomHashMap.java
Object2DoubleLinkedOpenHashMap.java
Object2DoubleOpenCustomHashMap.java
Object2DoubleOpenHashMap.java
Object2IntLinkedOpenCustomHashMap.java
Object2IntLinkedOpenHashMap.java
Object2IntOpenCustomHashMap.java
Object2IntOpenHashMap.java
Object2LongLinkedOpenCustomHashMap.java
Object2LongLinkedOpenHashMap.java
Object2LongOpenCustomHashMap.java
Object2LongOpenHashMap.java
Reference2DoubleLinkedOpenHashMap.java
Reference2DoubleOpenCustomHashMap.java
Reference2DoubleOpenHashMap.java
Reference2IntLinkedOpenHashMap.java
Reference2IntOpenCustomHashMap.java
Reference2IntOpenHashMap.java
Reference2LongLinkedOpenHashMap.java
Reference2LongOpenCustomHashMap.java
Reference2LongOpenHashMap.java_

**Comment by vigna** [comment]
Please replicate under a sensible OS (Linux, Mac OS X).

**Comment by vigna** [comment]
BTW, there's no mergeDouble() method in that class...
