### ISSUE TITLE
ObjectArrayList removing into foreach

### ISSUE THREAD

**Issue by PedroMPagani** [vigna/fastutil#243]
Alright, i have this code and when u run it, it removes the /2 of the list size, not it all, when i remove using the iterator and nextIndex() works fine, but when i try it inside of the foreach it does not work, and it runs only the half of the list on the foreach either, not it all.
`
ObjectList s = new ObjectArrayList();

     for (int i = 0; i < 10000; i++) {
            STotem st = new STotem(String.valueOf(i), String.valueOf(i));
            st.setRankWeight(i*10000);
            s.add(i,st);
            System.out.println("Add: " + " : " + i);
        }
        System.out.println(s.size());
        Long time1 = System.currentTimeMillis();
        for (Object o : s) {
            s.remove(o);
        }
        /*ObjectListIterator g = s.listIterator();
        while (g.hasNext()){
            s.remove(g.nextIndex());
        }*/
        Long time2 = System.currentTimeMillis();
        System.out.println("Size of the list: " + s.size() + " " + (time2-time1));`

**Comment by incaseoftrouble** [comment]
Concurrent modification is not allowed, fastutil does not exhaustively try to detect such modification for performance reasons. Both loops are invalid in that sense.

Instead of `s.remove(g.nextIndex())` you could use something like `g.remove()` (I think this is how it is called).

To remove all objects, use `s.clear()`. If you want to select which to remove, use `s.removeIf(...)` or make a copy of the list.

**Comment by incaseoftrouble** [comment]
For further help, search for `ConcurrentModificationException` and how to avoid it (this is what most java collections would directly throw for this kind of code).

**Comment by PedroMPagani** [comment]
While using g.remove() it gives me an error,
Exception in thread "main" java.lang.IllegalStateException
	at it.unimi.dsi.fastutil.objects.ObjectArrayList$1.remove(ObjectArrayList.java:895)
	at com.styp.totem.manager.STRank.<init>(STRank.java:60)
	at com.styp.totem.manager.STRank.main(STRank.java:37)
![twasfagfwa](https://user-images.githubusercontent.com/56891617/111343304-0ee50200-865a-11eb-8931-0d43e9424673.PNG)

**Comment by incaseoftrouble** [comment]
You also need to call `g.next()` after removing. `.remove()` does not advance the iterator.

**Comment by PedroMPagani** [comment]
Sorry for the dumb act, thanks for the support. ( I think its before.)

**Comment by incaseoftrouble** [comment]
> Sorry for the dumb act, thanks for the support. ( I think its before.)

No problem 😄 Happens to everyone.
