### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by File14** [vigna/fastutil#246]
Hello,

We get an ArrayOutOfBoundsException when we try to add an object to the Object2IntOpenHashMap. We are currently using FastUtil 8.5.2. Do you know what causes the exception to be thrown?

Error:
[<img src=https://i.gyazo.com/ee7201eb06f0bfad16a6cf0cb3c2b38f.png>](Image)

The following code is executed from the Geyser project that throws the exception:
`CACHED_BLOCK_ENTITIES.put(new Position(position.getX(), position.getY(), position.getZ()), blockState);`

**Comment by vigna** [comment]
Most likely concurrent access. Try to synchronize the map.

**Comment by File14** [comment]
It was the issue. Thank you very much for the fast support!

**Comment by jidnyeshIon** [comment]
I am getting the same issue when i am calling the computeIfAbsent Method on the Object2ObjectLinkedOpenHashMap. 
FYI, no concurrent access problem as the map is only used in one place
