### ISSUE TITLE
The Collectors of Hash based data structures should report `UNORDERED`

### ISSUE THREAD

**Issue by techsy730** [vigna/fastutil#249]
The Collectors of hash based data structures should report `UNORDERED`. That can let the Stream framework know some optimizations are safe. It would know it doesn't need to take pains to maintain order as the thing it is collecting to doesn't maintain order anyways.

Pretty much only means the hash maps, except for the linked ones.

**Comment by vigna** [comment]
A PR? :)

**Comment by techsy730** [comment]
Yes, just that today I was busy and didn't get around to this, so wanted to remind myself
