### ISSUE TITLE
BigList removeAll adds elements :-)

### ISSUE THREAD

**Issue by cdman** [vigna/fastutil#26]
````java
  @Test
  public void testRemoveAllModifiesCollection() {
    IntBigList list = new IntBigArrayBigList();
    assertFalse(list.removeAll(Collections.emptySet()));
    assertEquals(IntBigLists.EMPTY_BIG_LIST, list);
  }
````

The first assertion fails because removeAll return true (even though it should return false since the collection was not modified). But even if we ignore that assertion, it errors out at the second assert since "removing nothing" suddenly populated the BitList with `[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]` :smile:.

**Comment by vigna** [comment]
OMG. I shouldn't code at night.

**Comment by cdman** [comment]
Good news! Lists and BigLists pass all tests in the suite!
