### ISSUE TITLE
Duplicate classes in extra and core jar

### ISSUE THREAD

**Issue by thomaswoeckinger** [vigna/fastutil#262]
Checking the current build with duplicate-finder-maven-plugin shows duplicate classes in fastutil-core and fastutil-extra

[WARNING] Found duplicate (but equal) classes in [it.unimi.dsi:fastutil-core:8.5.4, it.unimi.dsi:fastutil-extra:8.5.4]:
[WARNING]   it.unimi.dsi.fastutil.booleans.BooleanArrays
[WARNING]   it.unimi.dsi.fastutil.booleans.BooleanBigArrays
[WARNING]   it.unimi.dsi.fastutil.booleans.BooleanIterable
[WARNING]   it.unimi.dsi.fastutil.booleans.BooleanIterator
[WARNING] Found duplicate classes/resources in compile classpath.

**Comment by vigna** [comment]
This is the intended way. The previous way (splitting classes) caused infinite problems to everybody.
