### ISSUE TITLE
Classic distribution of fastutil.jar is missing some classes

### ISSUE THREAD

**Issue by thomaswoeckinger** [vigna/fastutil#264]
All classes in package it.unimi.dsi.fastutil (like it.unimi.dsi.fastutil.Hash) are missing in the classic distribution.

At least for version 8.5.5

**Comment by vigna** [comment]
I pushed yesterday 8.5.6 which was supposed to fix that. I don't know why, it's still not out. Checking...

**Comment by vigna** [comment]
I don't know what to say—that never happened to me before. It seems to be an internal sonatype issue. Please try to look again for 8.5.6 tomorrow.

**Comment by iTitus** [comment]
It is still not released :(

**Comment by vigna** [comment]
Sonatype has something really broken. I have uploaded 8.5.6 twice, yesterday and today, without any error. And it is not published yet.

**Comment by vigna** [comment]
The situation is made worse by the fact that there is no clear endpoint for reporting bugs. JIRA? Support? If you have suggestions about how to contact the correct Sonatype guys, please let me know...
