### ISSUE TITLE
Array map entrySet throws on remove / removeAll

### ISSUE THREAD

**Issue by cdman** [vigna/fastutil#27]
This is just one example, but it will throw on all calls of remove / removeAll since *ArrayMap.EntrySet inherits from AbstractObjectSet which implements remove as throwing `UnsupportedOperationException`.

````java
  @Test
  public void testEntrySetSupportsRemoveAll() {
    Int2IntMap map = new Int2IntArrayMap();
    assertFalse(map.entrySet().removeAll(Collections.singleton("TEST")));
  }
````

**Comment by vigna** [comment]
Yes, as I said the implementation of array map was quick and dirty. Fixed.
