### ISSUE TITLE
find-deps.sh

### ISSUE THREAD

**Issue by IWareQ** [vigna/fastutil#271]
How use find-deps.sh?

i use ```find-deps.sh find C:\example\path\TestProject```

return ```-->.class```

hierarchy:
TestProject.src.iwareq.testpr.Main.java

**Comment by incaseoftrouble** [comment]
Which shell are you using? MinGW or WSL?

**Comment by IWareQ** [comment]
> Which shell are you using? MinGW or WSL?

PowerShell

**Comment by incaseoftrouble** [comment]
Well, its a bash skript (`.sh`) not a powershell script (`.ps1`), this won't work. Install WSL and run it from bash.
Or replicate the script. Its not doing much besides calling `jdeps -recursive -regex "it\.unimi\.dsi\.fastutil\..*" -verbose:class -cp "<your jar>"`

**Comment by IWareQ** [comment]
iwareq@hide:/mnt/c/Users/dimon/IdeaProjects/fastutil$ bash find-deps.sh find /mnt/c/Users/dimon/IdeaProjects/testProfect
find-deps.sh: line 2: $'\r': command not found
: invalid option name set: pipefail

**Comment by IWareQ** [comment]
![image](https://user-images.githubusercontent.com/51165317/146685421-6ea23e4b-20f9-4b42-99f6-8747405b7900.png)
whats next?

**Comment by incaseoftrouble** [comment]
interesting. Which distribution? I guess Ubuntu from the looks of it.

Probably jdeps slightly changed their output format. You can extract the list of classes in the middle (all the "it.unimi..." being referenced) and pack that into a file (`dependencies.txt`) and then do `find-deps.sh minimize yourjar.jar dependencies.txt` if I remember correctly

**Comment by IWareQ** [comment]
> interesting. Which distribution? I guess Ubuntu from the looks of it.
> 
> Probably jdeps slightly changed their output format. You can extract the list of classes in the middle (all the "it.unimi..." being referenced) and pack that into a file (`dependencies.txt`) and then do `find-deps.sh minimize yourjar.jar dependencies.txt` if I remember correctly

Yes, Ubuntu. Returned "Resolving transitive dependencies​"

**Comment by incaseoftrouble** [comment]
Hm, it seems jdeps significantly changed its functionality. I can't find a way to restrict it to only analysing the given classes as roots.

To fix this, one would need to write something that parses the complete output of jdeps (essentially, a list of all dependencies in fastutil) and then build the dependency tree for the given dependencies.

Doable, but its probably easier to just minimize the final jar with proguard or similar.

**Comment by IWareQ** [comment]
Why not fix the script?

**Comment by vigna** [comment]
Hey, why not capitalize on split.sh? It does exactly what you need (I think).

**Comment by incaseoftrouble** [comment]
> Why not fix the script?

As I just said, jdeps changed how it works apparently.

**Comment by IWareQ** [comment]
> Hey, why not capitalize on split.sh? It does exactly what you need (I think).

If it creates an archive with the files that I use the project, then - yes, this is what I need

**Comment by IWareQ** [comment]
maybe open issue?)

**Comment by incaseoftrouble** [comment]
split.sh separates fastutil in the native datatypes (int long double Object). Just run it in fastutil source folder after compiling. You'll save ~15 MB.

find-deps.sh won't work because of change in jdeps behaviour. Considering the minimal benefits and many caveats of this script I don't see a reason to fix it (PR is welcome of course).

**Comment by IWareQ** [comment]
> split.sh separates fastutil in the native datatypes (int long double Object). Just run it in fastutil source folder after compiling. You'll save ~15 MB.
> 
> find-deps.sh won't work because of change in jdeps behaviour. Considering the minimal benefits and many caveats of this script I don't see a reason to fix it (PR is welcome of course).

thx
