### ISSUE TITLE
Object2ObjectArrayMap should have all fields protected

### ISSUE THREAD

**Issue by frajt** [vigna/fastutil#285]
Hi, 

any reason why _Object2ObjectArrayMap_ has all fields as private? Both the _Object2ObjectOpenHashMap_ and _Object2ObjectMaps.Singleton_ for example have all fields defined as protected allowing to implement custom subclass and custom extensions if required. This way it is a bit inconsistent and causing trouble for us when implementing our custom _Map_ iterator in a _BitSet nextIndex()/keyAtIndex()/valueAtIndex()_ style. It fully eliminates creation of an iterator object when a map (or set) needs to be iterated. Especially for small Array based Maps/Sets its perfect fit but works nice on all open-adressing maps backuped by an indexable array. No need to create Iterator object, no need to mutate BasicEntry on each next() call - kind of no-gc iteration way. 

Would it be possible to change it to protected?

Thanks,
Michal

**Comment by vigna** [comment]
I just pushed the changes. They will be part of the next release.
