### ISSUE TITLE
Does BigList use memory not managed by JVM?

### ISSUE THREAD

**Issue by xxks-kkk** [vigna/fastutil#286]
Reading the doc on BigArray (https://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/BigArrays.html), I think BigList, which is backed by BigArray still uses on heap memory, i.e., memory managed by JVM. Do I understand correctly? I greped on the source code and didn't see keyword like `sun.misc` to suggest off-heap memory usage.  But, reading overview page on big hash set, I notice "[big hash sets](https://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/ints/IntOpenHashBigSet.html) provide support for sets whose size is only limited by the amount of core memory." Does core memory mean the memory used by JVM or physical memory?

Thank you!

**Comment by vigna** [comment]
JVM memory.
