### ISSUE TITLE
Meaning of sentence about "safely casting iterator" in docs

### ISSUE THREAD

**Issue by rionda** [vigna/fastutil#295]
Hello,

I'm trying to understand the following sentence in the [documentation of, e.g., `Int2IntAVLTreeMap`](https://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/ints/Int2IntAVLTreeMap.html).

"The iterators provided by the views of this class are type-specific [bidirectional iterators](https://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/BidirectionalIterator.html). Moreover, the iterator returned by iterator() can be safely cast to a type-specific [list iterator](https://docs.oracle.com/javase/8/docs/api/java/util/ListIterator.html)."

1. What `iterator()` method is it referring to? I am assuming that of the *views*, as `Int2IntAVLTreeMap` does not seem to have an `iterator()` method (at least none is mentioned in the docs?).  If so, it is not *entirely* evident from the sentence. Perhaps a rewording such as "The iterator returned by the `iterator()` method of the view objects can be safely case ..."

2. Does the above sentence mean that I can safely do this:
```java
      @SuppressWarnings("unchecked")  ListIterator<Int2IntMap.Entry> it =
                    (ListIterator<Int2IntMap.Entry>) myInt2IntAVLTreeMap.int2IntEntrySet().iterator();
```

Thanks,
Matteo

**Comment by vigna** [comment]
Yes, map don't have iterators. Views on entries, keys, and values, instead, have iterators. This is a Java Collections Framework thing, not a fastutil thing.

Frankly, I cannot see how the rewording is different from the original. Views are obviously objects, so "view object" doesn't change anything, and "iterator returned by the `iterator()` method of" or "iterator provided by" (given that the standard iterator-returning method of `Iterable` is `iterator()`)seems really the same to me.

Yes, you can cast as indicated. I was wondering how I could I ever have implemented that in the case of an iterator starting from a key, and indeed I didn't. In the sense that if you create such an iterator `previousIndex()` and `nextIndex()` will be relative to the starting point, which is entirely undocumented. Thank you for making me notice this.

**Comment by rionda** [comment]
The rewording was more about emphasizing that `iterator()` is the one for the view objects, but as you mention, someone who knows about Java Collections (and that's not me, lol), should understand that easily. Thank you  Seba!

Matteo
