### ISSUE TITLE
Java 7 Compatibility

### ISSUE THREAD

**Issue by bdw-g** [vigna/fastutil#302]
Hi!

We're using fastutil internally and we have a few users that require Java 7 support (mainly for android applications).

Fastutil v8 is incompatible with Java 7 because it refers to various new interfaces in `java.util.function`, which were not present in java 7.

We'd like to contribute patches that would make the compilation of methods that require java 8+ conditional, so that we could compile a version of fastutil that doesn't require them.

Would you be open to such a set of patches?
Thanks in advance!

**Comment by vigna** [comment]
Well, yes, if it's not too intrusive and it makes compilation _for Java 7_ conditional. Without options the code must come out as it is now.

**Comment by bdw-g** [comment]
We're closing this issue because it has proven more complex than anticipated and because we no longer require this to perform our upgrade.

Thanks!
