### ISSUE TITLE
performance / understanding question

### ISSUE THREAD

**Issue by ddsky** [vigna/fastutil#303]
I am stuck by not understanding some performance metrics I'm obtaining.
I found that iterating through an IntOpenHashSet AND adding into another IntOpenHashSet takes much longer than expected.
When I just iterate, it takes 13ms, when I just add it takes 160ms but when I do both it takes not 160+13 but 2800 (17x longer than expected).

Can you point me in the direction to understand this behavior? Please be aware that I know in this example I could do `addAll` or use an initial capacity to dramatically boost the speed but I boiled it down to those basics that I don't understand.

This is the test code:
```
IntOpenHashSet integers = new IntOpenHashSet();
long ms = System.currentTimeMillis();
for (int i = 0; i < 3_000_000; i++) {
    integers.add(i);
}
System.out.println(System.currentTimeMillis() - ms + "ms adding 3M integers to IntOpenHashSet");
ms = System.currentTimeMillis();
for (Integer integer : integers) {
    integer++;
}
System.out.println(System.currentTimeMillis() - ms + "ms iterating through IntOpenHashSet");

IntOpenHashSet anotherHashSet = new IntOpenHashSet();
ms = System.currentTimeMillis();
for (int integer : integers) {
    anotherHashSet.add(integer);
}
System.out.println(System.currentTimeMillis() - ms + "ms iterating AND adding to IntOpenHashSet");
```

outputs
```
160ms adding 3M integers to IntOpenHashSet
13ms iterating through hashset
2809ms iterating AND adding to IntOpenHashSet
```

**Comment by pburka** [comment]
Have you controlled for garbage collection? If a GC occurs during your
timing run you might see radically different times. You may wish to take a
look at the Open JDK JMH project for some tools and documentation on
writing robust microbenchmarks.

**Comment by vigna** [comment]
This is understandably a nuisance but it is difficult to fix. Read the full discussion: https://github.com/vigna/fastutil/issues/53

**Comment by ddsky** [comment]
thanks @vigna. I have to admit I didn't fully understand the implications in the discussion you linked. I got that the order is important and another test after sorting the elements again showed that this is indeed the case.

Quick question for real world where I do not know the final size of the hash set and cannot guarantee the order.
Would it make sense to initialize the sets with a large initial capacity to allow for fast adding and then after I'm done call a `.trim()`?

**Comment by vigna** [comment]
Yes, that's a solution but it's a lot of memory. You could also iterate a first time counting the new elements, resize exactly and then add.
