### ISSUE TITLE
ByteBuffer-based OpenHashMap structures for flat structures

### ISSUE THREAD

**Issue by faucct** [vigna/fastutil#318]
It would be nice to have implementations with keys and values backed by ByteBuffers or their typed analogs. They could be used to build maps storable in flat structures, e.g. https://flatbuffers.dev. After storing the maps in flat structures it should be possible to reconstruct them from ByteBuffer to get a read-only open hash map without copying memory.

**Comment by vigna** [comment]
That's exactly what we did in [ε-serde](https://crates.io/crates/epserde)! Unfortunately, it's in Rust. Unless someone writes a very good PR I don't see this happening in Java in a short time frame.
