### ISSUE TITLE
Support for getLast/getFirst in lists

### ISSUE THREAD

**Issue by Nightenom** [vigna/fastutil#319]
Hi, in Java 21 new collection interface `SequencedCollection` was added => few methods were added to List interface - for manipulation with first/last element + reverse method. These methods have no companion for primitive-typed fastutil lists

**Comment by vigna** [comment]
Unfortunately that's not gonna happen. We are moving everything to Rust and fastutil is in maintenance mode.

**Comment by Nightenom** [comment]
Hmm, i can try PRing it myself during summer, also kinda surprised by your statement given wide public usage of this library

**Comment by vigna** [comment]
Well, but what do you have in mind? fastutil is on Java 9, you cannot use interfaces from Java 21. I mean, NavigableSet/Map would come first.

**Comment by Nightenom** [comment]
I mean, compared to NavigableMap/Set, the Sequence ifaces add singleliner defaulted methods (except `#reversed()`), which are just syntax sugar ie. they do not provided any new functionality. So I think the library may easily provide primitive typed counterparts without even using the jdk ifaces as a starting point.
(also multi-versioned jar exists, but it might be an overkill since one must already hard type via library ifaces to use the performance gain)
However the `#reversed()` method will be a larger problem. But I think I can PR the rest during summer if you want
