### ISSUE TITLE
Arrays.quicksort() produces results inconsistent with Collections.sort() with same data and comparator

### ISSUE THREAD

**Issue by lwhite1** [vigna/fastutil#32]
Hi, 

I'm trying to sort a set of integers that represents row indexes in a 'table' object, according to the values in the table, with the sorting logic provided by a comparator.

I have run a side-by-side test using java.util.Collections and it.unimi.dsi.fastutil.Arrays.  A visual inspection confirms that the Collections#sort produces the expected order. Here is the code from the test: 

```
    table1 = StorageManager.readTable("bigdata/airlines");
    table2 = StorageManager.readTable("bigdata/airlines");

   // This is just used to create a comparator below
    Sort key = Table.getSort("ORIGIN");

    // first try, with Collections.sort.
    IntComparator rowComparator = table1.getComparator(key);
    IntArrayList t1rows = table1.rows();
    Collections.sort(t1rows, rowComparator);

    // second try, with Arrays.quicksort()
    IntComparator rowComparator2 = table2.getComparator(key);
    IntArrayList t2rows = table2.rows();
    int[] values = t2rows.elements();

    Arrays.quickSort(0, t2rows.size(), rowComparator2, new Swapper() {
      @Override
      public void swap(int a, int b) {
        int temp = values[a];
        values[a] = values[b];
        values[b] = temp;
      }
    });

    // This assert fails. The arrays are sorted in a completely different order.
    assertTrue(java.util.Arrays.equals(values, t1rows.elements()));

```
My first thought was that there is a bug in my swap routine, but I can't see it. 

This is the comparator being used:

```
  public final IntComparator rowComparator = new IntComparator() {

    @Override
    public int compare(int i, int i1) {
      return getString(i).compareTo(getString(i1));
    }

    @Override
    public int compare(Integer i, Integer i1) {
      return getString(i).compareTo(getString(i1));
    }
  };

```
The method is defined such that the row indexes from the sort column ("ORIGIN") are compared according to the standard lexicographical sort on the string values of that column.

Any suggestions would be very much appreciated. If you agree that this seems like a bug, I can try to provide a simple executable test case to recreate.

**Comment by vigna** [comment]
> On 8 Mar 2016, at 14:20, Larry White <notifications@github.com> wrote:
> 
> This is the comparator being used:
> 
> ` public final IntComparator rowComparator = new IntComparator() {
> 
> @Override
> public int compare(Integer i, Integer i1) {
>   return getString(i).compareTo(getString(i1));
> }
> 
> };

Note that you can use AbstractIntComparator and avoid this paer.

Before doing anything, can you check if the second array is sorted? This is different from being equal to the first array. 

Ciao,

					seba

**Comment by lwhite1** [comment]
The second array is sorted, but not in the same order as the first array.

**Comment by vigna** [comment]
> On 8 Mar 2016, at 15:08, Larry White <notifications@github.com> wrote:
> 
> The second array is sorted, but not in the same order as the first array.
> 

So there's no bug. Collections uses TimSort, which is stable. If you use QuickSort (which is not) you can get a different result (which is still fully correct).

Try mergesort if you need stability.

Ciao,

					seba

**Comment by lwhite1** [comment]
I'm sorry, I wasn't clear. The second array is sorted only in the sense that the output is different from the input. It is not sorted correctly (in a way that respects the lexicographical relationships of the strings).  I repeated the test with mergeSort and got the same result.

**Comment by lwhite1** [comment]
I will attempt to make an executable example that reproduces what I'm seeing.

**Comment by vigna** [comment]
Sorry, I read too quickly. The Swapper-based quicksort doesn't do what you suppose it does. You should use a quicksort in IntArrays and a comparator. The Swapper-based version requires to get indices both in the comparator and in the swapper. But you're using values in the comparator and indices in the swapper (i.e., the comparator should be getString(values[i])).

I'd just use the version in IntArrays.

**Comment by lwhite1** [comment]
I'll give that a try. Thank you

**Comment by lwhite1** [comment]
Works like a charm. Thank you!
