### ISSUE TITLE
Object2ObjectArrayMap not supporting entry setValue

### ISSUE THREAD

**Issue by frajt** [vigna/fastutil#323]
Hi,

just discovered that the Object2ObjectArrayMap entry set Entry::setValue is not supported. The method is throwing UnsupportedOperationException as the BasicEntry::setValue is not overwritten like for the AVLTree or RBTree maps. Please note the more complex EntrySet::remove operation is suppored, so it is asking to have the setValue supported as well. 

Recognized by the Guava Collections tests applied on Fast Array vs Fast Hash object maps. Causing inconsistent behavior for applications where for big maps it works, for small maps covered by ArrayMap, it currently fails (version 8.5.12).

Thanks in advance,
Michal

**Comment by vigna** [comment]
Oh yes that's a very long-standing missing implementations. Basically nobody cared in 20+ years. Worth fixing tho.
