### ISSUE TITLE
@test annotation missing in IntArrayListTest.java for testAddAll

### ISSUE THREAD

**Issue by flohop** [vigna/fastutil#324]
It seems to be that the @Test annotation was forgotten for this test function
![image](https://github.com/user-attachments/assets/12e045f7-55ee-45b9-a5b5-90dc9aa5e125)

**Comment by flohop** [comment]
Same for testSort
![image](https://github.com/user-attachments/assets/7de807b6-bf16-45ae-be21-a5051a1e3715)

**Comment by incaseoftrouble** [comment]
FYI on github you can directly reference lines of code

https://github.com/vigna/fastutil/blob/3e59d8a9577801e9df866b259e4c9ebfcb9c3923/test/it/unimi/dsi/fastutil/ints/IntArrayListTest.java#L150-L157

https://github.com/vigna/fastutil/blob/3e59d8a9577801e9df866b259e4c9ebfcb9c3923/test/it/unimi/dsi/fastutil/ints/IntArrayListTest.java#L189-L193

(select the lines in the web interface > the three dots options menu > copy permalink)

**Comment by vigna** [comment]
Thanks, fixed!
