### ISSUE TITLE
Singleton sets can throw NullPointer / ClassCast exception

### ISSUE THREAD

**Issue by cdman** [vigna/fastutil#35]
See unittest here: https://github.com/gpanther/fastutil-guava-tests/blob/b154514cbaee3c06353d2c50a9babe77a21ddc6b/src/test/java/net/greypanther/fastutil/tests/Int2IntMapTest.java#L63

The problem seems to be that Maps.Singleton does not check the types of the Map.Entry it gets (IMHO it should do an instanceof check on both key and value which would also weed out null values): https://github.com/vigna/fastutil/blob/0740dcdf3a8dd3b83b68ef1b770f3a9a7fc6a47d/drv/Maps.drv#L166

**Comment by vigna** [comment]
I see. Maybe we can check for the fastutil interface and act in two different ways—all this type check doesn't seem to be very efficient.

**Comment by cdman** [comment]
Some quick ideas:
* Personally I prefer correctness over performance :smile_cat: 
* I'm not to worried about the cost of one (or several) instanceof's since:
** it boils down to reading a couple of bytes from the object header
** most cases will be filtered out upstream (by Map.Singleton.equals checking "this == that" or checking that "that.size() == 1"
** in general, if this code is only used with fastutil maps, the JIT should have an easy time to specialize the generated machine code and eliminate most of the checks
* If we're still worried, we should create some benchmarks around the code (but then there is the problem of "how we benchmark?" - do we call equals with instances of HashMap? Int2IntOpenHashMap? Int2IntMaps.Singleton? A mix of these? - depending on what the benchmark does the optimizer will take different decisions and the output might or might not be relevant for "real life" code).

**Comment by vigna** [comment]
I'm not suggesting to have incorrect code. I'm suggesting that we might take a fast path when the class type-specific, as of course in that case no instanceof error is possible.

**Comment by vigna** [comment]
BTW, I think that the same is true of the equals() method of several map classes.

**Comment by cdman** [comment]
@vigna - you sure this is fixed? I don't see any additional checks [here](https://github.com/vigna/fastutil/blob/master/drv/Maps.drv#L168) and [this unittest](https://github.com/gpanther/fastutil-guava-tests/blob/b154514cbaee3c06353d2c50a9babe77a21ddc6b/src/test/java/net/greypanther/fastutil/tests/Int2IntMapTest.java#L63) still fails.

**Comment by vigna** [comment]
Sorry, I messed up the push process. Can you check again now?

**Comment by cdman** [comment]
Yes, it's working now, thanks.
