### ISSUE TITLE
Bug: IterableCollections, isEmpty() via iterable.iterator.hasNext()

### ISSUE THREAD

**Issue by okrische** [vigna/fastutil#37]
I see this in in the IterableCollection of DoubleCollections and IntCollections, didnt check any further:

```java
		public boolean isEmpty() {
			return iterable.iterator().hasNext();
		}
```

I think, there is a missing negation. Because this actually tells me, the iterable is not empty. Or am i missing something? :)

**Comment by vigna** [comment]
That's horrible, but thanks for the report. I fixed it.
