### ISSUE TITLE
Make YYYLinkedOpenHashSet.comparator return something meaningful

### ISSUE THREAD

**Issue by cdman** [vigna/fastutil#41]
`YYYLinkedOpenHashSet` declares that it implements `SortedSet`, however it breaks [the contract for the `comparator` method|https://docs.oracle.com/javase/8/docs/api/java/util/SortedSet.html#comparator--] which states that:

> Returns the comparator used to order the elements in this set, or null if this set uses the natural ordering of its elements.

However `YYYLinkedOpenHashSet` always returns null, even though it should return a comparator which does something like: "if element A was inserted before B then return -1, if B was inserted before A return 1 else return 0" (ie. don't use the "natural order" but rather use the "insertion order").

See a failing unittest [here|https://github.com/gpanther/fastutil-guava-tests/blob/master/src/test/java/net/greypanther/fastutil/tests/Int2IntSortedSetTest.java#L13].

An other option to implementing the above comparator (which is not-very-fast) is for `YYYLinkedOpenHashSet` to just not implement `SortedSet` (as `java.util.LinkedHashSet` does it).

**Comment by vigna** [comment]
Well, the documentation warns clearly about the fact that the implementation of SortedSet/Map is just partial. Following what you say, I should return a comparator that returns different values for the same arguments depending on the state of the map.

**Comment by cdman** [comment]
@vigna:

> Following what you say, I should return a comparator that returns different values for the same arguments depending on the state of the map.

Yes, that's exactly what I'm saying :smile:. Saying `SortedMap<Integer>` means that the values are sorted based on an arbitrary criteria (depending on the actual implementation), not that they are sorted by the natural order. It can be natural order (for java.util.TreeMap for example) but it can also be "insertion order".

Alternative quick fix: throw `UnsupportedOperationException` from `YYYLinkedOpenHashSet.comparator` to make it quicker for people to discover the issue.
