### ISSUE TITLE
ObjectOpenCustomHashSet.rehash throws ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by dlipofsky** [vigna/fastutil#42]
Version 7.0.6

Getting this
`java.lang.ArrayIndexOutOfBoundsException: -1
at it.unimi.dsi.fastutil.objects.ObjectOpenCustomHashSet.rehash(ObjectOpenCustomHashSet.java:536)
at it.unimi.dsi.fastutil.objects.ObjectOpenCustomHashSet.add(ObjectOpenCustomHashSet.java:255)`

The set is created like
`ObjectOpenCustomHashSet<byte[]> set = new ObjectOpenCustomHashSet<>(ByteArrays.HASH_STRATEGY);`

And the **only** method that is ever called is
`ObjectOpenCustomHashSet.add(byte[])`

I don't have an exact path to reproduce but I am getting the error fairly often.

> $ java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
$ uname -r
2.6.32-573.12.1.el6.x86_64

**Comment by vigna** [comment]
Does it happen with the last version (7.0.12)?

**Comment by vigna** [comment]
Are you sure you aren't accessing the data structure by different threads?

**Comment by dlipofsky** [comment]
My apologies, I was accessing from 2 different threads, and I was calling the remove method from that other thread, I just missed it when I wrote this ticket. So I think this could be closed, although a `ConcurrentModificationException` would be nicer than a `ArrayIndexOutOfBoundsException`

(by the way, behavior is the same in 7.0.12)

**Comment by RainerWaldmann** [comment]
Having the same problem with 8.2.2  and jdk1.8.0_161 with Long2ObjectOpenCustomHashMap

addAll throws:
java.lang.ArrayIndexOutOfBoundsException: Index 511 out of bounds for length 257
	at it.unimi.dsi.fastutil.longs.LongOpenCustomHashSet.rehash(LongOpenCustomHashSet.java:657)
	at it.unimi.dsi.fastutil.longs.LongOpenCustomHashSet.tryCapacity(LongOpenCustomHashSet.java:319)
	at it.unimi.dsi.fastutil.longs.LongOpenCustomHashSet.addAll(LongOpenCustomHashSet.java:326)
 
Thrown by addAll  during collection in a non paralell stream:
 collect(Collectors.toMap(entry -> entry.getLongKey(), entry -> entry.getValue(),
                                (e1, e2) -> {
                                    e1.addAll(e2); 
                                    return e1;}, 
                                ()-> {return new  //Class derived from // Long2ObjectOpenCustomHashMap<>;}

**Comment by vigna** [comment]
My guess is it's the same problem...

**Comment by RainerWaldmann** [comment]
Weird since it is in a collector of a stream that is not paralell. 
If I do this kind of stuff with other non synchronized collections I never see this kind of problem.
