### ISSUE TITLE
Implement the PrimitiveIterator Interface

### ISSUE THREAD

**Issue by sickert** [vigna/fastutil#43]
Java 8 introduced support for primitive iterators to avoid costs for boxing and unboxing values during iteration: [Documentation](https://docs.oracle.com/javase/8/docs/api/java/util/PrimitiveIterator.html). This is very similar to the existing `IntIterator`, `LongIterator`, and `DoubleIterator`. In order to improve compatibility with the standard Java Collection Framework I propose changing the `IntIterator` declaration from

```
public interface IntIterator extends Iterator<Integer>
```

to

```
public interface IntIterator extends PrimitiveIterator.OfInt
```

and analogously the two other interfaces. The obvious drawback of this is that the minimum requirement for fastutil gets bumped up to Java 8.

**Comment by lemire** [comment]
@sickert 

Does Android support Java 8? Do all cloud providers support Java 8?

**Comment by sickert** [comment]
Android N supports the necessary Java 8 features. [Documentation](https://developer.android.com/preview/j8-jack.html) 

Regarding the cloud providers, this is a rather broad question: A quick search shows that providers such as Heroku or Oracle Java Cloud do support Java 8.

**Comment by vigna** [comment]
Well, Java 7 hit the end of life. So Java 8 support it's a matter of survival.

**Comment by sickert** [comment]
@vigna I've just noticed that you started using Java 8 on master. The attached pull request should address the open issue. Feedback is appreciated. :)

**Comment by vigna** [comment]
Er... why do you way so? I'm cleaning up stuff to leave behind a clean tree before starting to work on a Java 8-only version tho, so the pull request is appreciated...

**Comment by sickert** [comment]
> Er... why do you way so?

What do you mean? I guess there is a typo. ;)

**Comment by vigna** [comment]
Yes. :)

Er... why do you think so? etc.

**Comment by sickert** [comment]
> Er... why do you think so? etc.

I noticed that you started to reference the Java 8 Documentation. But I overlooked that you still build against Java 7. My bad. :)

**Comment by vigna** [comment]
Yes. The problem is that they changed the way links are generated, so if you link to the old documentation (but use the new Javadoc, which is much better) to generate fastutil's documentation the links to methods won't work.
