### ISSUE TITLE
Jar empty with maven command

### ISSUE THREAD

**Issue by vinceRicchiuti** [vigna/fastutil#44]
Hi, 
i need to use fastutil in my thesys project, but i need to use a jar of it that will be imported; i try with the usual command mvn package but it is still empty. Can someone help me with this issue? 
Thanks in advance

**Comment by vigna** [comment]
> On 14 Jun 2016, at 09:30, vinceRicchiuti <notifications@github.com> wrote:
> 
> Hi, 
> i need to use fastutil in my thesys project, but i need to use a jar of it that will be imported; i try with the usual command mvn package but it is still empty. Can someone help me with this issue? 

What does it mean "usual command"? What are you trying to do? If you want to build fastutil, read the README. Otherwise, add it to your dependencies.

Ciao,

					seba
