### ISSUE TITLE
Java 8 Synchronization

### ISSUE THREAD

**Issue by almondtools** [vigna/fastutil#48]
From reviewing the source code I would expect some methods not to be synchronized correctly if `xxxxMaps.synchronize(xxxxMap<K, V>)` is called.

That would be probably every method being defined as default in `java.util.Map`, such as `compute`, `computeIfAbsent` or `computeIfPresent`.

**Comment by vigna** [comment]
Absolutely so. The introduction of default methods was controversial exactly for that reason—it kills everything depending on delegation.
