### ISSUE TITLE
???ArrayFIFOQueue#dequeue??? should throw NoSuchElementException

### ISSUE THREAD

**Issue by sirinath** [vigna/fastutil#49]
`dequeue???` should throw NoSuchElementException if there is no element in the queue like `dequeueLast???`. `???` is the primitive type name.

Alternatively have 2 methods like in Java where on rentuns a special value and another throws an exception. (https://docs.oracle.com/javase/7/docs/api/java/util/Queue.html)

**Comment by vigna** [comment]
That's not English. Please rephrase.

**Comment by sirinath** [comment]
Done

**Comment by vigna** [comment]
Can you provide a unit test for the last version? I cannot reproduce.

**Comment by sirinath** [comment]
The documentation does not mention that it throws a exception or not. E.g.: http://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/objects/ObjectArrayFIFOQueue.html#dequeue--

**Comment by vigna** [comment]
I see. The problem is that when you inherit documentation you don't inherit the exceptions. I never realized that. Fixed.

**Comment by sirinath** [comment]
I do not see any change in the Docs?

**Comment by vigna** [comment]
It'll take quite some time 😂
