### ISSUE TITLE
Packaging of sources is not "standard"

### ISSUE THREAD

**Issue by shevek** [vigna/fastutil#5]
Standard packaging of sources makes the .java file names match the .class file names in the corresponding binary JAR file. This allows the IDEs, static analysis tools, etc to discover them.

fastutil packages sources under src/ and test/ which means that they are essentially useless in any automated environment, and can only be handled manually.

Please can you publish a more standard -sources.jar and either merge the test sources at the root of the sources JAR or publish a separate test sources JAR?

Thank you.

**Comment by vigna** [comment]
> On 12 Nov 2015, at 03:50, Shevek <notifications@github.com> wrote:
> 
> Standard packaging of sources makes the .java file names match the .class file names in the corresponding binary JAR file. This allows the IDEs, static analysis tools, etc to discover them.
> 
> fastutil packages sources under src/ and test/ which means that they are essentially useless in any automated environment, and can only be handled manually.

Er. They work perfectly for me under Eclipse. Which IDE are you using?

Ciao,

					seba

**Comment by shevek** [comment]
Thank you for your response. Eclipse is very heuristic about naming, and is happy to generate false positives for implements-method etc.

I'm using NetBeans, and occasionally IntelliJ. We also have standalone processes for processing sources for static analysis. This is one of only two JARs out of the 129 JARs in our application which uses a nonstandard layout. The other is Apache Hive, against which I withhold comment!

**Comment by vigna** [comment]
> On 12 Nov 2015, at 19:05, Shevek <notifications@github.com> wrote:
> 
> Thank you for your response. Eclipse is very heuristic about naming, and is happy to generate false positives for implements-method etc.
> 
> I'm using NetBeans, and occasionally IntelliJ. We also have standalone processes for processing sources for static analysis. This is one of only two JARs out of the 129 JARs in our application which uses a nonstandard layout. The other is Apache Hive, against which I withhold comment!

OK, I'll pack the sources without src/test for the next release.

Ciao,

					seba

**Comment by shevek** [comment]
You rock, thank you SO much!
