### ISSUE TITLE
Code generation fails when changing names in makefile

### ISSUE THREAD

**Issue by dustContributor** [vigna/fastutil#54]
Hi! I decided to try modifying the makefile so to generate classes with different naming scheme, like this:

```
#  The capitalized types used to build class and method names; boolean and object types are not listed.
TYPE_NOBOOL_NOOBJ=Byte Short Int Long Char Float Double

#  The capitalized types used to build class and method names; boolean and reference are not listed.
TYPE_NOBOOL_NOREF=$(TYPE_NOBOOL_NOOBJ) Obj

#  The capitalized types used to build class and method names; object types are not listed.
TYPE_NOOBJ=Boolean $(TYPE_NOBOOL_NOOBJ)

#  The capitalized types used to build class and method names; references are not listed.
TYPE_NOREF=$(TYPE_NOOBJ) Obj

#  The capitalized types used to build class and method names; boolean is not listed.
TYPE_NOBOOL=$(TYPE_NOBOOL_NOREF) Ref

# The capitalized types used to build class and method names; now references appear as Reference.
TYPE=$(TYPE_NOREF) Ref

#  The capitalized types used to build class and method names; only types for which big structures are built are listed.
TYPE_BIG=Int Long Float Double Obj Ref
```

So you'd get something like Ref2ObjMap. Ideally I wanted it to be RefObjMap for example, removing the '2', names which are described in the same file.

The thing is that it seems to break code generation, for instance I get class definitions like:

```
 public abstract class Abstract2BooleanFunction implements 2BooleanFunction , java.io.Serializable {
```

That ought to be AbstractSomething2BooleanFunction and Something2BooleanFunction, so compilation fails.

Also if I change TYPE_NOOBJ from Boolean to Bool, I get an error for a missing file:
```
./drv/BinIO.drv:157:63: fatal error: src/it/unimi/dsi/fastutil/io/BooleanBinIOFragment.h: No such file or directory
```

Since it seems the full name "BooleanBinIOFragment" is hardcoded in the BinIO.drv file. The generator instead creates BoolBinIOFragment, thus why it cant find it.

Any ideas on what might be wrong or what I am missing?

**Comment by dustContributor** [comment]
I also tried to change the names in the gensources.sh file and the problem persists. Searching around it seems there are a few hardcoded checks like 
´´´
if [[ "${CLASS[$k]}" != "Object" && "${CLASS[$k]}" != "Reference" ]]; then\
´´´
Which fails if you actually change the names.

**Comment by vigna** [comment]
I understand your concerns, but this is no *no way* an "issue" :).

**Comment by dustContributor** [comment]
Really? I thought the class names were configurable for a reason. So any pointers on how would I accomplish changing the generated class names like that?
