### ISSUE TITLE
Versioning policy?

### ISSUE THREAD

**Issue by io7m** [vigna/fastutil#56]
Hello!

I use `fastutil` in several projects with the types often appearing as part of published APIs. As `fastutil` is a healthy project with frequent releases, I often have to update version numbers. Is it safe to assume that `fastutil` is using [semantic versioning](http://semver.org/)? It seems like it is, given how the version numbers have changed over time, but I don't see an explicit policy written down anywhere. With an explicit policy in place, I can use version ranges in dependencies to make it easier to stay up-to-date.

**Comment by vigna** [comment]
> On 22 Feb 2017, at 12:20, io7m <notifications@github.com> wrote:
> 
> Hello!
> 
> I use fastutil in several projects (with the types often appearing as part of a published API). As fastutil is a healthy project with frequent releases, I often have to update version numbers. Is it safe to assume that fastutil is using semantic versioning? It seems like it is, given how the version numbers have changed over time, but I don't see an explicit policy written down anywhere. With an explicit policy in place, I can use version ranges in dependencies to make it easier to stay up-to-date.

Nothing that formal, but yes, more or less I do that :).

Ciao,

					seba

**Comment by io7m** [comment]
Ok, thanks!
