### ISSUE TITLE
Add efficient versions of Java 8 Map's methods  (primitive specializations)

### ISSUE THREAD

**Issue by leventov** [vigna/fastutil#57]
map.putIfAbsent(k, v): v
map.replace(k): v
map.replace(k, v): boolean
map.remove(k, v): boolean

Even not talking about lambda-accepting methods, `putIfAbsent()` is a painfully missing part.

**Comment by vigna** [comment]
Man, you're so right. Pull request? ;)

**Comment by vigna** [comment]
Did you check the current fastutil 8 version on GitHub? It's very close to release and fixes this and more.
