### ISSUE TITLE
Allocations on Map/Set Removal

### ISSUE THREAD

**Issue by pjulien** [vigna/fastutil#60]
I am seeing a lot of allocations from the open hash set and map classes.  For this use case I am using the [ACT pattern](https://www.dre.vanderbilt.edu/~schmidt/PDF/ACT.pdf) to keep track of information for requests.  

- When responses are received, the ACT is re-read from the received response and used to remove the object from the corresponding map.
- When new requests are made, objects are retrieved from the pool and associated to a new ``ACT`` by inserting into a ``Int2ObjectOpenHashMap``

This is causing a massive amount of allocations because the map is constantly being halved and then moments later is doubled in size.  This behavior is indeed [documented](http://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/ints/Int2ObjectOpenHashMap.html):

> If the table is emptied below one fourth of the load factor, it is halved in size

but I still feel this behavior is unwarranted because:

- Trimming methods are provided for anyone who might care about using too much memory.
- No facility, to my knowledge, is provided to anyone who cares about allocations instead of memory usage, not to mention all the copying this requires.
- It's next to impossible to provide a valid sizing hint, i.e., the following immediately halves the table:
```java
  Int2IntOpenHashMap m = new Int2IntOpenHashMap(4_096);

  m.put(1, 1);
  m.remove(1);
```

This has the following impact on my code:

- In one of my applications with ``fastutil`` 7.0.11, this is causing several hundreds of GiBs worth of allocations per second with pauses ranging in the 200-400 milliseconds per *second*.  In this case I am fortunate because I can work around it using ``clear``
- I have another application that uses a very small heap on Java 6 with ``fastutil`` 6.6.3.  This application I thought was allocation free once it reached the steady state but because of this it makes about 1 MiB/s worth of allocations resulting in about 2 pauses of 8 ms each per minute.

The following code reproduces the issue in case I am not being clear:

```java
import it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap;
import org.junit.Test;

import static org.junit.Assert.*;

public class RehashTest {
  @Test
  public void test() {
    Int2IntOpenHashMap m = new Int2IntOpenHashMap();

    for (int i = 0; i < 100_000_000; i++) {
      for (int j = 0; j < 1_000; j++) {
        m.put(j, j);
      }

      for (int j = 0; j < 1_000; j++) {
        m.remove(j, j);
      }
    }
  }
}
```

I am willing to provide the patch for this myself if there is interest.  The solution is just not to rehash on ``remove``, e.g., replace this

```java
	private V removeEntry(final int pos) {
		final V oldValue = value[pos];
		value[pos] = null;
		size--;
		shiftKeys(pos);
		if (size < maxFill / 4 && n > DEFAULT_INITIAL_SIZE) rehash(n / 2);
		return oldValue;
	}
```

with 

```java

	private V removeEntry(final int pos) {
		final V oldValue = value[pos];
		value[pos] = null;
		size--;
		shiftKeys(pos);
		return oldValue;
	}
```

For completeness, I also looked at ``Agrona``, its maps [do not rehash on removal](https://github.com/real-logic/Agrona/blob/master/agrona/src/main/java/org/agrona/collections/Int2IntHashMap.java#L373)

**Comment by vigna** [comment]
I see. You're the first reporting about this, so let's try to find a solution. Total lack of rehash is somehow a bad idea in my opinion, but what about trying maxFill / 8 instead? Would that solve your problem? The current threshold was chosen because it guarantees amortized linear behaviour, but we can adapt for a garbage-collected language like Java.

**Comment by pjulien** [comment]
@vigna 

>  Total lack of rehash is somehow a bad idea in my opinion,

Is it a total of rehash?  Rehashing is still being performed when adding, also when calling ``trim`` directly

>  what about trying maxFill / 8 instead?

The examples above are incredibly silly but they would reproduce the issue even if using 1/8 of the table size.  In any scenario where the size of the table changes significantly, the table will constantly be reallocating its table and copying it over.

> The current threshold was chosen because it guarantees amortized linear behaviour

Well I think that makes perfect sense when expanding the table, but why is this needed when removing?  If it's only when adding, the table is the wrong size until it isn't, and at that point, it's the right size forever.

By doing this on remove, the table is pretty much always the wrong size.

**Comment by vigna** [comment]
I don't understand what you mean by "much always the wrong size".

If I add 1M elements, I remove them, and I don't rehash, the table is of course of the wrong size—it contains millions of useless slots. The map is empty.

"Wrong" can mean too small—and then the structure becomes slow—or too large—and then the structure uses too much memory.

In understand, though, the "size-hinting issue". It is indeed a scenario I never considered.

One solution for this very specific problem would be that of never rehashing below the initial size. It is a sensible behavior as you requested at least that capacity.

Would that solve your problem (maybe together with maxFill / 8)?

**Comment by pjulien** [comment]
@vigna 

> I don't understand what you mean by "much always the wrong size".

In the simplest case

```java
  Int2IntOpenHashMap m = new Int2IntOpenHashMap(4_096);

  m.put(1, 1);
  m.remove(1);
```

I want a 4096 entry table.  I know I'll never need more than this, this is the exact size I want.  I can't do that if I ever call ``remove`` myself.  I might be able to work the issue by using ``clear`` but that's it.

> If I add 1M elements, I remove them, and I don't rehash, the table is of course of the wrong size—it contains millions of useless slots. The map is empty.

but aren't you making the assumption that I need the table to have a small array?  If you start populating this table again, and do this frequently enough like I do, this is where the problem comes in.  I'm OK with the table being 1 million in size because I know my data set.

> "Wrong" can mean too small—and then the structure becomes slow—or too large—and then the structure uses too much memory

and that's why you added ``trim`` operations

> One solution for this very specific problem would be that of never rehashing below the initial size.

Yes, that's what I want.  Well, more specifically, don't re-allocate the backing array if still above the initial size.

> Would that solve your problem (maybe together with maxFill / 8)?

Yes, because now I can trust the sizing hint is respected which means I can stay out of trouble in a predictable way.

**Comment by vigna** [comment]
Note that you are not considering iterators, but they are important to some people. A large table with few elements will have very, very (per-element) slow iterators.

I just implemented the changes—you can find them in the current GitHub version. Let me know if they work for you...

**Comment by pjulien** [comment]
> Note that you are not considering iterators, but they are important to some people.

That's definitely true but I would argue iterators on a open hash table are never going to be that great just because of the nature of the data structure.

> I just implemented the changes—you can find them in the current GitHub version. Let me know if they work for you...

checking

**Comment by vigna** [comment]
Quite the contrary. If you keep your table filled, they're much faster than anything else—having two skip one or two empty locations per element has almost zero cost.

**Comment by pjulien** [comment]
@vigna 

works great thanks using 8.0.0 with the latest commit
