### ISSUE TITLE
Does parallel Quicksort require extra memory?

### ISSUE THREAD

**Issue by simlu** [vigna/fastutil#61]
**Does parallel Quicksort require extra memory?** And if so, how much?

There is a note on _sequential_ Quicksort indicating that it does not. However parallel Quicksort _does not_ have this note.

Looking forward to a reply!

**Comment by vigna** [comment]
Good question, difficult to answer. Part of the problem is that how much resources are allocated by the fork-join framework. Of course there's no direct allocation like in mergesort.

**Comment by simlu** [comment]
Right. So we should be looking at a small, static overhead (almost) independent of the array size? Is there data duplicates into threads or is only the one array used, accessed from all worker threads?

**Comment by vigna** [comment]
There's positively no data duplication.

**Comment by simlu** [comment]
Sweet, thank you!
