### ISSUE TITLE
Making 100 Billion Longs Unique

### ISSUE THREAD

**Issue by simlu** [vigna/fastutil#62]
I'm trying to make approx 100 billion longs unique. Currently I'm inserting sequentially into LongOpenHashSet. This works fine, but is really slow (many hours). Meanwhile my CPU and disk IO are very much underutilized.

Note: There are a lot of duplicates, so I expect around 10 billion elements to remain.

Best I could come up with right now is to bucket the longs by computing `long mod prime number` and then processing each bucket individually using LongOpenHashSets (in chunks to minimize memory required). When completed I would concatenate all LongOpenHashSets.

Before I start implementing this, do you have any recommendations or better ideas to solve this? Maybe some experience with a similar project? Goal is to reduce overall compute time. Looking forward to a reply.

**Comment by vigna** [comment]
Be sure to be using pages. That  changes a lot.

Still, the fastest way to uniquefy a list is by sorting. Did you consider that?

**Comment by vigna** [comment]
I meant "huge pages".

**Comment by simlu** [comment]
What do you mean by "using huge pages"? Is that a setting on the LongOpenHashSet?

So sorting and removing duplicates is actually faster than putting elements into a LongOpenHashSet?

**Comment by vigna** [comment]
Google for huge pages. It's an OS feature.

There's no rule about what method is faster. Three are too many factors involved.

**Comment by simlu** [comment]
Kk, will do!

Fair enough. I'll have to test :) Thanks for the input!

**Comment by pburka** [comment]
If you're willing to sacrifice some precision (maybe you can tolerate a small number of missed values) you could use a Bloom filter, which is much more space efficient, but probabilistic.
