### ISSUE TITLE
Java 8 support

### ISSUE THREAD

**Issue by incaseoftrouble** [vigna/fastutil#64]
Hi,

as you said in #43:
> Well, Java 7 hit the end of life. So Java 8 support it's a matter of survival.

Do you plan to migrate to Java 8? I strongly urge you to - I personally need most of these changes :) I identified several "todo"-items for Java 8, which I would be willing to implement:

- Support of the new Map methods like `putIfAbsent`, `computIfAbsent` etc. (#57)
- Synchronization support of the newly introduced map methods (#48)
- Support of new Iterator interfaces (#43)
- Support of new Function interfaces, e.g. `Int2DoubleMap` should implement Java 8's `IntToDoubleFunction`.

I imagine that one could implement all this in a way which allows you to specify the target Java version. But, while it should be possible, I advice against it; as you pointed out, Java 7 is not the go-to version anymore and future releases should target Java 8.

**Comment by incaseoftrouble** [comment]
I added some preliminary work at https://github.com/incaseoftrouble/fastutil/commit/bad6ffa147d9017350973a99f631a03858de2ea6 . Feel free to suggest improvements / modifications!

Most of the issues are already addressed there (at least partially). Synchronization is not complete.
TODO: Javadoc for newly added methods (but most of it will be more or less copy-paste from the generic methods), Test cases and specific implementations of the Map methods (although this can be delayed).

**Comment by vigna** [comment]
Great. There some initial work in the default_methods branch about how to manage the various class conflicts (e.g., you're adding getOrDefault to Map, but actually we need to add it to Function). Can you have a look at how it has been done?

**Comment by incaseoftrouble** [comment]
I can't see that branch unfortunately (I'm quite new to github though so maybe I'm doing something wrong here ...).

Note that I only added the generic default methods to Map (to have the `@Deprecated`), the primitive counterparts are actually found in Function.

**Comment by vigna** [comment]
Please try 

git checkout default_methods
git diff 9a0d5a19b1

That should show that changes w.r.t. the version I added the method to. I'll probably have to redo the work as the master has changed a lot since then. But it gives an idea to what need to be done.

I'm including the diff in case you encounter difficulties.

[diff.txt](https://github.com/vigna/fastutil/files/1019253/diff.txt)

**Comment by incaseoftrouble** [comment]
Thanks! It seems that I can't access the branch. I suppose it is only visible to members of the project?

I looked through the diff. It pretty much looks like what I implemented (apart from putting some of the methods into the generic Function interface). I also added the ofter methods (like merge etc.). This isn't fully finished yet but I plan on having a working prototype quite soon.

**Comment by incaseoftrouble** [comment]
Okay so I pushed something which is at least compiling to https://github.com/incaseoftrouble/fastutil/tree/java-8 . Synchronized counterparts are partly missing I think. Javadoc and specific implementation still remains to be done but I want to agree upon the interface specifications first. Please provide some feedback whenever convenient.

**Comment by incaseoftrouble** [comment]
Sorry for being so verbose. One more question / suggestion: Since upgrading the Java version is quite a significant change anyway, we could potentially introduce another redesign. The `K2VFunction` interface is somewhat in a weird place. I totally understand the reasoning behind it and support its existence, but in light of the Java 8 primitive functions, the naming is somewhat questionable. I suggest the following changes: Rename `K2VFunction` to `K2VMapping` (or similar) and create a super-interface `K2VFunction` which directly corresponds to the Java functions, i.e. it is a functional interface only yielding an `apply`-like method.

**Comment by vigna** [comment]
No, we cannot change Function's name at this point.

I really appreciate your contribution, but I sent the diff because I want all methods to be implemented *exactly* following the scheme shown therein—in particular, where and how the documentation is specified. I cannot go through a lot of code checking that is done following the specs (see REVISE.md), so please be sure that the new methods follow exactly that scheme. Also, we should discuss *first* at which level of the hierarchy to implement methods (Function? Map? SortedMap?). Otherwise it becomes a nightmare for me...

**Comment by vigna** [comment]
Two on-the-fly comments:

1) In fastutil code, we don't do one-line blocks: we put the statement on the same line of the if or else keyword.

2) For efficiency reasons we do not explicitly check for non-null references if they are immediately accessed in the method (as a NullPointerException will be thrown anyway).

**Comment by incaseoftrouble** [comment]
> No, we cannot change Function's name at this point.

Ok.

Regarding the rest: I fully understand and agree with your concerns. Please take the changes I pushed so far as mere suggestions, nothing more. I don't mind a complete overhaul if you think it should be done differently. I will go through my current design again and check against the format specifications.

Regarding the discussion: I will try to briefly summarize where I put what in the following, basically going from top to bottom.
- I added a type-specific `Consumer` (yielding `IntConsumer`, `ShortConsumer`, etc.), extending the Java Consumers where applicable.
- The type-specific `Function` now extends the JDK primitive function interface, where applicable.
- I added `getValueOrDefault`*, `putIfAbsent`, binary `remove`, `replace`, `computeIfAbsent`* **, `computeIfPresent`* **, `compute`* **, and `merge`* ** as default methods to `Function`. * name adapted to the value (i.e. `computeIntIfAbsent` etc.). ** the function involves `BiFunction`s, which are not supported by fastutil as of now - I resorted to the generic versions for now.
- Above methods have been added to `SynchronizedFunction`
- I added a `forEach`-style primitive method to Iterable, using aforementioned Consumers where applicable.
- Iterator now extends the Java primitive iterators where applicable, the `forEachRemaining` supports the Consumers (not pushed yet)
- `Iterators` has an `any`, `all` and `indexof` method, based on Java predicate where applicable (one could consider adding type-specific predicates for this reason)
- Since the type-specific Map inherits from both `java.util.Map` and `Function`, the default methods like `computeIfAbsent` would clash, the interface resolves the clashes and deprecates the generic default methods where applicable.
- `SynchronizedMaps` contains the synchronized versions of all these methods.
- A few more macros have been added to gensource
- The fastutil `Function` interface now extends the java Function interface and furthermore has the generic versions of all the default methods from above.

Regarding your comments: I shall implement both of them while revising the code.

**Comment by vigna** [comment]
This seems to be reasonable, but I need to think about the Function issue.

**Comment by incaseoftrouble** [comment]
A small comment on this: Most use cases should be fine with the current state I suppose. Since java does not offer any kind of primitive handling apart from int, long, double and boolean, most implementations either tightly bind to fastutil already or will be taken care of by these changes. The only users affected by not implementing this are those who need something like a "ShortToXFunction" over a "IntToXFunction". While I can see this happening, the performance gains of such a "ShortToXFunction" are questionable, since (to my knowledge at least) the JRE has no `short`-specific instructions anyway and every operation on e.g. two shorts converts them to ints and back. Instead, the `short` datatype is only relevant for more efficient storage, which is something taken care of by fastutil already.
In light of this, one could instead let `Short2XFunction`, `Char2XFunction`, etc. extend the `IntToX`-Java function (or whatever is appropriate). A cast from `short` to `int` and back still is considerably faster than boxing and unboxing.

I also added some javadoc to Function in my branch. If you don't have any immediate objections, I'll start implementing the methods for a few implementations. Again, don't hesitate to tell me that something should be reworked!

**Comment by vigna** [comment]
Can you give me just a couple of days? I want to minimize rewrite from your part.

**Comment by incaseoftrouble** [comment]
Sure, no worries :) I just had not much else to spend my time on these few days.

**Comment by vigna** [comment]
OK. So let's try at least to set up the additional Map methods exactly as in the diff that I sent you (Javadoc location, etc.). The question is: which methods go to Map and which go to (fastutil's) Function? Anything involving enumerating the keys should go to map, the rest to Function.

**Comment by incaseoftrouble** [comment]
Enumeration only is needed for the forEach and replaceAll methods, which can't be mapped to fastutil. The former needs a BiConsumer, the latter a BiFunction. All others are only related to single keys, thus I put them into Function instead of Map. The definitions in Function should match the style of the diff as far as I see it.

**Comment by incaseoftrouble** [comment]
> OK, why not adding also a BiConsumer and BiFunction interfaces? The main problem I see is the gigantic number of BiFunction interfaces—9x9x9=81. But we've seen worse.

There are two reasons. First, as you said, there would be quite a lot of classes. Secondly, the gensources and makefile would need to also support ternary input (i.e. KEY, KEY2 and VALUE). Both problems are not to hard conceptually and I can try to implement them if you want but I probably would need some guidance there.

**Comment by vigna** [comment]
BTW, does your code include https://github.com/vigna/fastutil/pull/58 ? Or is it orthogonal?

**Comment by vigna** [comment]
So, the main problem in this moment is the lack of unit tests (like the one I included in the diff). It's a lot of code—it needs to be covered.

Another issue is that I'm trying to make everything lambda-able. This means, for example, that I'll have to default *all* Function's method, as well as their conterparts in type-specific functions. So those will have to be pulled up from AbstractFunction etc.

I just did this for comparators and it's lovely.

**Comment by incaseoftrouble** [comment]
> BTW, does your code include #58 ? Or is it orthogonal?

It's fully extending it.

> So, the main problem in this moment is the lack of unit tests (like the one I included in the diff). It's a lot of code—it needs to be covered.

Yup, this is something I did plan to do when we agreed on the interface decisions. Have you considered writing ".drv-based" Unit tests? I.e. tests generated by the same mechanism all the instances are generated?

> Another issue is that I'm trying to make everything lambda-able. This means, for example, that I'll have to default all Function's method, as well as their counterparts in type-specific functions. So those will have to be pulled up from AbstractFunction etc.

Yes this is my main concern about Function. A "mathematical" function is stateless, currently the functions have some state ("put"). One could consider defaulting them to `UnsupportedOperationException`, but I don't know if this is good design then. The problem is that the concept of partiality and `defaultReturnValue` fundamentally conflicts with the totality of primitive functions specified by lambdas.

> I just did this for comparators and it's lovely.

Yes, seen this :) Lambdas are so nice and expressive. I merged your changes into my java-8 branch.

**Comment by vigna** [comment]
So, after fiddling a bit with the code I'm changing my mind.

I think it's best if we think of fastutil's Function and its type-specific versions as a dead end. They are not fit as JDK's Function instances because it's very difficult to make the lambda-able (lots of conflicts in existing code). Nobody uses them, I think, apart from Sux4J and the DSI Utilities, and in their present state they're perfectly good for that purpose. Moreover, they'd be a continuous source of ambiguity.

I think it's much better if we add all Java 8's method at the Map level, leaving Function and associates undisturbed. No conflicts to solve, etc. Also, all new methods imply in some form that you actually know the keys, which is not in general true of a Function. For the cases in which the JDK provides a type-specific function, we will use it. And that's it.

But I would like to hear anybody else's opinion on this.

**Comment by incaseoftrouble** [comment]
I agree with that for the most part. The design choices of Function are rather specific ("pretty much a map but just not quite"), so trying to coerce them into the Java hierarchy is probably not needed.

One thing I'd suggest is to always use the Java primitive functions, even if applying the function involves upward casts, like `short` to `int` or `float` to `double`), i.e. let a `Short2ShortFunction` implement the `IntUnaryOperator` (Java's "IntToInt" function).

I'll invite @sickert to the discussion.

**Comment by mdekstrand** [comment]
I use `Long2DoubleFunction` in a couple places in LensKit, but completely agree that it doesn't need to grow Java 8's map extensions.

**Comment by vigna** [comment]
Well, it's OK if the cast is *widening*, but using a Short2ShortFunction to implement IntUnaryOperator means that the input must be cast to a short.

We could do the following:

- New methods of java.util.Map go to type-specific Map interfaces (so: no conflicts).
- it.unimi.dsi.fastutil.Function extends java.util.Function but has a default method that implements apply() using get().
- type-specific instances of Function implement corresponding JDK type-specific functions, so Int2IntFunction implements IntToIntFunction and there's a default apply() method that uses get().
- We can decide whether we want to implement "widening" interfaces. For example, Int2ShortFunction could implement IntToIntFunction. If we want to do this, we'll need some logic in getcsources.sh. Argument should be narrowed, results should be widened.
- Finally, in the type-specific implementation of methods using functions, consumers, etc. we might decide, once again, to use a soft approach. In this case, however, we need to opposite: arguments should be widened, whereas results show be narrowed.

**Comment by incaseoftrouble** [comment]
> Well, it's OK if the cast is widening, but using a Short2ShortFunction to implement IntUnaryOperator means that the input must be cast to a short.

Not necessarily I think. Say you have a ShortToShortFunction and "apply" it with something larger than Short.MAX_VALUE. Either, you could do a "guarded" cast (throw exception if it doesn't fit into a `short`, [Guava](https://github.com/google/guava/wiki/PrimitivesExplained#general-utility-methods) does this with `checkedCast`) or just say "this key is not contained" and return `defaultReturnValue()`. This is not about "perfect" representation, but rather about compatibility. It might be a bit more tricky for `float` to `double`. We definitely need to provide a "Utility" class offering all the checked casts.

Doing widening and guarded narrowing is still a lot faster than using `Function<Short, Short>` I guess, and, as far as I know, the widening actually gives you close to no overhead actually even for the computations. The gensource logic shouldn't be too hard to implement.

**Comment by vigna** [comment]
BTW, the C preprocessor does not expand macros in comments. So stuff like {@link SORTEDMAP....} doesn't work.

**Comment by vigna** [comment]
OK, let's try with the widening/narrowing idea...

**Comment by vigna** [comment]
Note that also UnmodifiableCollection needs some of those method, as in the JDK.

**Comment by incaseoftrouble** [comment]
> BTW, the C preprocessor does not expand macros in comments. So stuff like {@link SORTEDMAP....} doesn't work.

I learned that the hard way :D

> OK, let's try with the widening/narrowing idea...

I'm busy with reviews / vacation the next two weeks, but I'll see what I can do.

> Note that also UnmodifiableCollection needs some of those method, as in the JDK.

Do you mean that any potentially modifiying method should throw an `UnsupportedOperationException`?

**Comment by vigna** [comment]
Well, no, but apparently they delegate a number of forEach-like methods, I guess for efficiency. Let's just stick to what the JDK does...

**Comment by incaseoftrouble** [comment]
Ah I see. I will try to replicate the behavior as faithfully as possible.

One more thing: Thanks a lot for crediting the changes in the CHANGES file. Could you, if possible, modify it to "Tobias Meggendorfer and Salomon Sickert from the Technical University of Munich" or similar? Salomon is a colleague of mine who sparked the whole process and contributed quite some ideas and I'd feel bad for not including him.

**Comment by vigna** [comment]
OK!

**Comment by incaseoftrouble** [comment]
I pushed some changes with the widening / narrowing idea for functions and consumers. The approach (especially in gensources) probably is suboptimal - I'd be happy for some feedback on this.

Further, I fixed some warnings, and replaced some abstract implementations with default methods (Iterators).

I also tried implementing the narrowing / widening for iterators, but there the problem is fundamentally different: The java primitive iterators (e.g. `PrimitiveIterator.OfInt`), have a `Integer next()` method, which clashes with the, say, `Short next()` method of a `ShortIterator` (same with the `forEachRemaining` etc.). There, a `ShortIterators.widenedIterator(iterator)` method could help.

**Comment by incaseoftrouble** [comment]
Some more stuff pushed (see [here](https://github.com/incaseoftrouble/fastutil/commits/java-8)):

* Pulled quite a few generic (i.e. non type-specific) methods from the `AbstractXY` to default methods in the corresponding interface and improved them slightly. If you pass a key to e.g. `get` which does not correspond to the primitive class, you now get a `null` back instead of a `ClassCastException`.
* Added tests for the new Map default methods.
* Fixed some warnings and incorporated the new `fastIterator` method at a few places. JUnit tests complete, `test.sh` completed the "100 elements" round.
* Renamed `static void test(int n)` to `static void runTest(int n)` since it clashed with `boolean test(int n)` for classes extending `IntPredicate`.
* Small changes to pom.xml to make it work better with some IDEs (IntelliJ now picks up JUnit dependency for testing and the correct target version).

I will be away until Monday at least.

**Comment by vigna** [comment]
> On 31 May 2017, at 11:55, Tobias Meggendorfer <notifications@github.com> wrote:
> 
> Some more stuff pushed (see here):
> 
> 	• Pulled quite a few generic (i.e. non type-specific) methods from the AbstractXY to default methods in the corresponding interface and improved them slightly. If you pass a key to e.g. get which does not correspond to the primitive class, you now get a null back instead of a ClassCastException.
> 	• Added tests for the new Map default methods.
> 	• Fixed some warnings and incorporated the new fastIterator method at a few places. JUnit tests complete, test.sh completed the "100 elements" round.
> 	• Renamed static void test(int n) to static void runTest(int n) since it clashed with boolean test(int n) for classes extending IntPredicate.
> 	• Small changes to pom.xml to make it work better with some IDEs (IntelliJ now picks up JUnit dependency for testing and the correct target version).
> I will be away until Monday at least.

We continue to have the same problem--your changes contain hundreds of space fixes and it becomes impossible for me to sift through the code...

I see you seem to have actually *eliminated* abstract classes after pulling up the methods, but in this way previous code won't work anymore. These classes must be emptied and deprecated--you can see an example in AbstractComparator. Please revise accordingly.

Ciao,

					seba

**Comment by vigna** [comment]
> On 31 May 2017, at 11:55, Tobias Meggendorfer <notifications@github.com> wrote:
> 
> Some more stuff pushed (see here):
> 
> improved them slightly. If you pass a key to e.g. get which does not correspond to the primitive class, you now get a null back instead of a ClassCastException.

No, this is a major change from previous behaviour. It is also unpredictable (the null can propagate a lot before you realize you passed the wrong object). Please remove all such tests.

Ciao,

					seba

**Comment by incaseoftrouble** [comment]
> We continue to have the same problem--your changes contain hundreds of space fixes and it becomes impossible for me to sift through the code...

I can't quite follow there. You can just [ignore all whitespace changes](https://github.com/vigna/fastutil/compare/master...incaseoftrouble:java-8?w=1) in the diff if that solves the issue.

> I see you seem to have actually *eliminated* abstract classes after pulling up the methods, but in this way previous code won't work anymore. These classes must be emptied and deprecated--you can see an example in AbstractComparator. Please revise accordingly.

Oh yes, sorry, that makes sense. Will do so tomorrow.

> No, this is a major change from previous behaviour. It is also unpredictable (the null can propagate a lot before you realize you passed the wrong object). Please remove all such tests.

Ah my bad. I thought the Java API actually requires you to just return false for "invalid" keys. Will revert the changes.

**Comment by vigna** [comment]
> On 5 Jun 2017, at 18:22, Tobias Meggendorfer <notifications@github.com> wrote:
> 
> I can't quite follow there. You can just ignore all whitespace changes in the diff if that solves the issue.

I understand. I don't see them, but the changes are there. Line count statistics, etc. get all wrong...

> Ah my bad. I thought the Java API actually requires you to just return false for "invalid" keys. Will revert the changes.

Well, there's no notion of "invalid" primitive key. I decided to generate a ClassCastException...

Ciao,

					seba

**Comment by incaseoftrouble** [comment]
I pushed the changes you mentioned.

> I understand. I don't see them, but the changes are there. Line count statistics, etc. get all wrong...

If it helps I can try to remove the whitespace changes as much as possible. Some may have been generated by my IDE though.

> Well, there's no notion of "invalid" primitive key. I decided to generate a ClassCastException...

"Invalid" as in doing something like `anInt2IntMap.containsKey(aDouble)`. I thought that in this case you are required to return false, but instead the API allows for more freedom. See the following paragraph:

> Some map implementations have restrictions on the keys and values they may contain. For example, some implementations prohibit null keys and values, and some have restrictions on the types of their keys. Attempting to insert an ineligible key or value throws an unchecked exception, typically NullPointerException or ClassCastException. Attempting to query the presence of an ineligible key or value may throw an exception, or it may simply return false; some implementations will exhibit the former behavior and some will exhibit the latter. More generally, attempting an operation on an ineligible key or value whose completion would not result in the insertion of an ineligible element into the map may throw an exception or it may succeed, at the option of the implementation.

One more thing: We could actually fit Function into the Java framework (i.e. make it expressible through a lambda expression) by making the interface behave like a total, immutable function by default. Implementations of course still can decide to be partial and/or mutable (similar to how the Java Map API works). The following changes would be necessary: Default `put`, `clear` and `remove` to `UnsupportedOperationException`, default the (primitive) `containsKey` to `true` (total functions are applicable to any key), default `size` to `-1` and then somehow deal with the default return value (either make it a no-op or unsupported operation, too, since total functions have no need for a default return value).

**Comment by vigna** [comment]
> On 6 Jun 2017, at 10:03, Tobias Meggendorfer <notifications@github.com> wrote:
> 
> One more thing: We could actually fit Function into the Java framework (i.e. make it expressible through a lambda expression) by making the interface behave like a total, immutable function by default. Implementations of course still can decide to be partial and/or mutable (similar to how the Java Map API works). The following changes would be necessary: Default put, clear and remove to UnsupportedOperationException, default the (primitive) containsKey to true (total functions are applicable to any key), default size to -1 and then somehow deal with the default return value (either make it a no-op or unsupported operation, too, since total functions have no need for a default return value).

When I tried to do that, I ran into unsolvable conflict problems in maps, as now some methods come from default Function methods and some from abstract map classes.

Frankly, I don't think it's worth the effort. All existing fastutil.Function implementation I'm aware of have nothing (semantically) to do with what Java's function intends to represent. At some point, try to merge everything generates only confusion with the user.

With Comparator, for example, the situation is very different because people might really like to write an IntComparator using a lambda expression. But why would someone want to generate a fastutil.Function using a lambda?

**Comment by incaseoftrouble** [comment]
I agree, I don't see too many application points. I was merely suggesting.

Are there any major points left to do? Otherwise I'll open a MR and we can discuss the finer points.

**Comment by vigna** [comment]
What's the situation with narrowing/widening of arguments? I'm losing track :)

**Comment by incaseoftrouble** [comment]
That is done as far as it seemed reasonable to me. Especially, functions / maps use it.

**Comment by vigna** [comment]
OK, just give me a couple of days to have a look at everything...

**Comment by incaseoftrouble** [comment]
Sure! If you want I can open a merge request, then you can comment particular code blocks.

**Comment by vigna** [comment]
Could you write me at sebastiano.vigna@gmail.com?

**Comment by vigna** [comment]
I'm going through the code. Great job! In fact, it's must more sorted out than *my* code.

One first observation: the implementation of containsKey() in Function is different from the original and has a different behaviour. The first test must be with null, in which case one returns false. There should be no type test (like in remove()).

**Comment by vigna** [comment]
The line 

			if (o instanceof SynchronizedFunction) synchronized (sync) { return function.equals(((SynchronizedFunction) o).function); }

in the equals() method of a synchronized function is potentially deadly, as it accesses a synchronized function *without* synchronization. The function might thus be in an inconsistent state when you read it.

**Comment by incaseoftrouble** [comment]
I'll open a MR then you can comment directly, give me a second.

> I'm going through the code. Great job! In fact, it's must more sorted out than my code.

Thank you :)

> One first observation: the implementation of containsKey() in Function is different from the original and has a different behaviour. The first test must be with null, in which case one returns false. There should be no type test (like in remove()).

It may very well be that I missed something while reverting my behavior changes. I'll check it later.

**Comment by vigna** [comment]
Is there a particular reason why you deleted my comments about 

http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8177440

**Comment by incaseoftrouble** [comment]
I think the reason for this was that the situation changed. Now, one super-interface (`Function`) provides a default implementation and Map provides an "abstract" method. This clash has to be resolved - it also results in a different error message if not resolved.

**Comment by vigna** [comment]
I left around a number of comments. Let me know what you think!

**Comment by incaseoftrouble** [comment]
> I left around a number of comments. Let me know what you think!

At first glance everything looks reasonable. I'll go over it later today! Thanks for the feedback.
