### ISSUE TITLE
Transparent accessor for `FastEntrySet`

### ISSUE THREAD

**Issue by incaseoftrouble** [vigna/fastutil#65]
The `FastEntrySet` mechanism currently is of limited use. In order to access it, one needs to either know the used implementation or do instanceof checks and casting all the time. Currently, I am using something like this:
```java
public static Iterator<Int2DoubleMap.Entry> fastIterator(Int2DoubleMap map)
{
  ObjectSet<Int2DoubleMap.Entry> entries = map.int2DoubleEntrySet();
  if (entries instanceof Int2DoubleMap.FastEntrySet) {
    return ((Int2DoubleMap.FastEntrySet) entries).fastIterator();
  }
  return entries.iterator();
}
```
Furthermore, foreach loops can't make use of the fast iterator. This is necessary in general since the contract on Iterables requires the default behavior. However, it should be possible to use the fast iterator in an accessible manner. I'd suggest wrapper functions to be used like this:
```java
for (Int2DoubleMap.Entry entry : Int2DoubleMaps.fastIterable(map)) { ; }
```
and
```java
Iterator<Int2DoubleMap.Entry> iterator = Int2DoubleMaps.fastIterator(map)
```
where both of these methods return the "fast" version when available. I am willing to provide a patch for both of these methods.

If such a mechanism already exists I am sorry for missing it.

**Comment by vigna** [comment]
That's an excellent idea. Do you want to try a pull request?
