### ISSUE TITLE
(Sparse)BitSet as (Sorted/Navigable)IntSets

### ISSUE THREAD

**Issue by incaseoftrouble** [vigna/fastutil#67]
[BitSet](https://docs.oracle.com/javase/7/docs/api/java/util/BitSet.html)s and [SparseBitSet](https://github.com/brettwooldridge/SparseBitSet)s can be used as backing data structure for `IntSet`s, or, with some more work, even `SortedIntSet` or `NavigableIntSet` (if they are supported eventually). In a nutshell, BitSet stores the contained integers as flipped bits in a long array.

The beauty of these structures is that they can very compactly represent a set of non-negative integers (if they aren't to sparse). Further, one can use these bit sets to store the complement, enabling an even more compact representation for some sets. Also, if one is not interested in the result of these operations, BitSets can perform operations like union and intersection amazingly fast (using a bitwise `or` of the longs for , for example). A use case would be if one for example wants to "mark" certain elements of `[0, n]`. In my particular case, I use this implementation to e.g. store reachable / interesting / etc. states in a numbered graph.

I already have a (more or less) finished and tested implementation of this (using both a slightly optimized version of the above linked SparseBitSet and the Java BitSet). Since the Java Collection API demands a `boolean` return for operations like `addAll`, I added a `BitIntSet` interface which allows for e.g. `void union(IntSet other)` in order to allow use of the faster implementations if possible.

**Comment by vigna** [comment]
> On 31 May 2017, at 11:41, Tobias Meggendorfer <notifications@github.com> wrote:
> 
> BitSets and SparseBitSets can be used as backing data structure for IntSets, or, with some more work, even SortedIntSet or NavigableIntSet (if they are supported eventually). In a nutshell, BitSet stores the contained integers as flipped bits in a long array.
> 
> The beauty of these structures is that they can very compactly represent a set of non-negative integers (if they aren't to sparse). Further, one can use these bit sets to store the complement, enabling an even more compact representation for some sets. Also, if one is not interested in the result of these operations, BitSets can perform operations like union and intersection amazingly fast (using a bitwise or of the longs for , for example). A use case would be if one for example wants to "mark" certain elements of [0, n]. In my particular case, I use this implementation to e.g. store reachable / interesting / etc. states in a numbered graph.
> 
> I already have a (more or less) finished and tested implementation of this (using both a slightly optimized version of the above linked SparseBitSet and the Java BitSet). Since the Java Collection API demands a boolean return for operations like addAll, I added a BitIntSet interface which allows for e.g. void union(IntSet other) in order to allow use of the faster implementations if possible.

Well, both structures are only useful if you have very specific data distribution. If you set bits at position 64*k the SparseBitSet structure will quickly explode. For BitSet, this is even more true. It is quite rare that this kind of approach is useful. Also, BitSets can be ridiculously slow if they are sparse (lots of work to scan empty data).

From what I see, you use BitSet as a kind of compact array of Booleans. This is a typical usage, and it is absolutely fine, albeit much slower than an array of Booleans (usually, the gain in space is irrelevant because other data takes orders of magnitude more space than a Boolean).

In fact, LongArrayBitVector (from the DSI utilities) provides such sets since a looong time:

http://dsiutils.di.unimi.it/docs/it/unimi/dsi/bits/AbstractBitVector.html#asLongSet--

Ciao,

					seba

**Comment by incaseoftrouble** [comment]
> From what I see, you use BitSet as a kind of compact array of Booleans.

Correct, but arguably, any set of nonnegative integers is equivalent to a boolean array. Interpretation as a set of integers is just more natural for my use case: In a nutshell, states of a graph are enumerated and then algorithms are run on it. I use (Sparse)BitSets to, e.g., represent strongly connected components or reachably areas of the graph. Since this approach may be rather specific, it might not be worth including it in fastutil. I just have the code more or less ready.

> This is a typical usage, and it is absolutely fine, albeit much slower than an array of Booleans (usually, the gain in space is irrelevant because other data takes orders of magnitude more space than a Boolean).

The relevant thing is that bulk operations like `containsAll`, `union`, etc. can be performed very efficiently between (Sparse)BitSets. When dealing with, say, 1e12 elements, performing `or` with two boolean arrays should be slower than BitSets (I did not verify this; I actually could try and implement a `boolean[]` based version of my BitIntSet and profile a bit), and more importantly, the difference in memory footprint is immense. `boolean[]` a) takes up to a *byte* (!) per element instead of a bit and b) is not sparse.

From reading the documentation, `LongArrayBitVector` is similar in spirit to Java's BitSet (with more convenience methods on top and longs instead of ints), right? More specifically, it is not sparse, which I would require for my application.

**Comment by lemire** [comment]
@incaseoftrouble 

You know about Roaring bitmaps...?
http://roaringbitmap.org/

**Comment by incaseoftrouble** [comment]
No I didn't, thanks for the pointer! I will look into this. Admittedly, I am fairly new to highly optimized datastructures in Java (as are most people in my field). I was abstracting an existing codebase which used BitSets hard-coded. Using abstraction + sparse bitsets as backend already gave a huge benefit there.

Is there is any benefit of wrapping these roaring bitmaps into `BooleanList` and/or `IntSet` of fastutil?

One more question, although this is diverging from the original issue: Do you think pairing up your implementation with fastutil (replacing the primitive iterators etc.) is worth considering?

**Comment by lemire** [comment]
> Is there is any benefit of wrapping these roaring bitmaps into BooleanList and/or IntSet of fastutil? One more question, although this is diverging from the original issue: Do you think pairing up your implementation with fastutil (replacing the primitive iterators etc.) is worth considering?


I am not sure what you mean by "benefit", but I expect that it can be done if you need it.

**Comment by incaseoftrouble** [comment]
Benefit as in "someone might make use of this work", which in turn justifies implementing this in fastutil. Similarly, for my second question, it might make sense to replace your implementation with fastutil's if it e.g. adds some functionality or enables people to use the some generic code with this particular implementation.

**Comment by lemire** [comment]
@incaseoftrouble 

> Benefit as in "someone might make use of this work", which in turn justifies implementing this in fastutil.
> Similarly, for my second question, it might make sense to replace your implementation with fastutil's

The Druid people have [wrappers](https://github.com/metamx/bytebuffer-collections/tree/master/src/main/java/com/metamx/collections)  that implement ``com.google.common.collect.Sets``. It works well *in production* within Druid right now. The same work can be done with ``fastutil`` if you want. Should be fairly trivial.

**Comment by vigna** [comment]
> On 5 Jun 2017, at 21:31, Daniel Lemire <notifications@github.com> wrote:
> 
> Is there is any benefit of wrapping these roaring bitmaps into BooleanList and/or IntSet of fastutil? One more question, although this is diverging from the original issue: Do you think pairing up your implementation with fastutil (replacing the primitive iterators etc.) is worth considering?
> 
> I am not sure what you mean by "benefit", but I expect that it can be done if you need it.

I think Thomas means that by wrapping them in a (somewhat) standardized primitive-type interface they can be plugged in existing code.

Ciao,

					seba

**Comment by vigna** [comment]
> On 5 Jun 2017, at 22:20, Daniel Lemire <notifications@github.com> wrote:
> 
> @incaseoftrouble
> 
> Benefit as in "someone might make use of this work", which in turn justifies implementing this in fastutil.
> Similarly, for my second question, it might make sense to replace your implementation with fastutil's
> 
> The Druid people have wrappers that implement com.google.common.collect.Sets. It works well in production within Druid right now. The same work can be done with fastutil if you want. Should be fairly trivial.
> 

Er... what do you mean by "implement com.google.common.collect.Sets"? It's a static container, not an interface.

Ciao,

					seba

**Comment by vigna** [comment]
> On 5 Jun 2017, at 21:03, Daniel Lemire <notifications@github.com> wrote:
> 
> @incaseoftrouble
> 
> You know about Roaring bitmaps...?
> http://roaringbitmap.org/

In fact, you can even get close to the information-theory lower bound with dynamic Elias-Fano:

http://pages.di.unipi.it/rossano/wp-content/uploads/sites/7/2017/04/CPM17.pdf

I don't know how practical that can be made, but static Elias-Fano is the basic data structure throughout Facebook.

Ciao,

					seba

**Comment by lemire** [comment]
> Er... what do you mean by "implement com.google.common.collect.Sets"? 

Right. It implements ``java.util.Set<Integer>``, which you can then plug into ``com.google.common.collect.Sets`` (e.g.).

**Comment by vigna** [comment]
> On 6 Jun 2017, at 00:22, Daniel Lemire <notifications@github.com> wrote:
> 
> Er... what do you mean by "implement com.google.common.collect.Sets"?
> 
> Right. It implements java.util.Set<Integer>, which you can then plug into com.google.common.collect.Sets (e.g.).

But it doesn't implement it.unimi.dsi.fastutil.ints.IntSet (or LongSet--much more interesting), which I think it's Thomas's point.

Ciao,

					seba

**Comment by lemire** [comment]
I was pointing at an example of what can be done without too much effort.

**Comment by vigna** [comment]
> On 6 Jun 2017, at 00:31, Daniel Lemire <notifications@github.com> wrote:
> 
> I was pointing at an example of what can be done without too much effort.

BTW, do you have an idea of the space/speed relationship between Roaring Bitmaps and SparseBitSets?

**Comment by lemire** [comment]
> BTW, do you have an idea of the space/speed relationship between Roaring Bitmaps and SparseBitSets?

Comparing data structures or software libraries is a tricky business. 

If you care about memory usage, then SparseBitSet is maybe not the best choice,  see https://github.com/brettwooldridge/SparseBitSet/issues/4 (compare the plots)

Roaring has more users though, for sure.

**Comment by incaseoftrouble** [comment]
So what do you guys think. Should we connect fastutil with Sparse/Roaring? I guess, since the introduced dependencies are rather heavy and usage is very scarce, the best idea would be to create a separate project which contains the additional code. I could do that, then you can have a look at the code if you are interested and see if the implementation might be useful.

**Comment by vigna** [comment]
I think it could be interesting, but to be really useful you would have to contribute to those project code for primitive-type accessors—wrapping will not work in this case. I mean, it's not a matter of bringing SparseBitSets into fastutil, but rather of bringing fastutil's interfaces to SparseBitSets.

**Comment by vigna** [comment]
In fact, I'm seeing that roaring's bitmaps implementation in defining from scratch stuff line IntIterator:

https://github.com/RoaringBitmap/RoaringBitmap/blob/master/src/main/java/org/roaringbitmap/IntIterator.java

And Druid has correspondingly adapters for fastutil:

https://github.com/druid-io/druid/blob/master/processing/src/main/java/io/druid/segment/IntIteratorUtils.java
