### ISSUE TITLE
Source is missing?

### ISSUE THREAD

**Issue by lwhite1** [vigna/fastutil#7]
I was looking for the source of IntArrayList, and cannot find it in the repo.  I did a repository search and found references to it, but there is no IntArrayList.java file. Is this a temporary thing, or am i missing something?  Thank you. Love this library, btw.

**Comment by vigna** [comment]
You must generate the code. Please read the README.

On November 17, 2015 4:54:13 PM GMT+01:00, Larry White <notifications@github.com> wrote:
>I was looking for the source of IntArrayList, and cannot find it in the
>repo.  I did a repository search and found references to it, but there
>is no IntArrayList.java file. Is this a temporary thing, or am i
>missing something?  Thank you. Love this library, btw.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/vigna/fastutil/issues/7

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lwhite1** [comment]
Sorry, I've been using it so long I forgot about the file generation.
