### ISSUE TITLE
NullPointerException in ObjectOpenHashSet$SetIterator.next

### ISSUE THREAD

**Issue by shevek** [vigna/fastutil#72]
Version 7.2.0 from Maven Central:

```
Exception in thread "main" java.lang.NullPointerException
        at it.unimi.dsi.fastutil.objects.ObjectOpenHashSet$SetIterator.next(ObjectOpenHashSet.java:518)
```

That's presumably the pointer to 'wrapped', which is null by default.

It's a puzzle, my process runs for a few hours before producing this error. I don't _think_ we ever remove from the set. We certainly never remove from the iterator. Our calling code for this iterator is just a `for (Object o : set)`

**Comment by vigna** [comment]
> On 15 Jun 2017, at 21:12, Shevek <notifications@github.com> wrote:
> 
> Version 7.2.0 from Maven Central:
> 
> Exception in thread "main" java.lang.NullPointerException
>         at it.unimi.dsi.fastutil.objects.ObjectOpenHashSet$SetIterator.next(ObjectOpenHashSet.java:518)
> 
> That's presumably the pointer to 'wrapped', which is null by default.
> 
> It's a puzzle, my process runs for a few hours before producing this error. I don't think we ever remove from the set. We certainly never remove from the iterator. Our calling code for this iterator is just a for (Object o : set)

Looking at it, looks like you are removing elements from the set after creating the iterator (not using the Iterator.remove()). I'd suggest adding a throw new RuntimeException() in the remove() method. What is happening is that scanning the backing array next() can't find size() elements, so it goes to the wrapped list.

Probably I could add a message to that effect ("you probably modified this set" etc.)

Ciao,

					seba

**Comment by shevek** [comment]
I would agree with you except I never remove any elements from any of these sets. I have a weak hypothesis that while I add to these sets on many threads, using a lock, I did not raise and lower that lock one last time on the main thread before consuming the set in single-threaded mode, but ... the threads are on an ExecutorService, and that creates a happen-before relationship with the Future.get() on the main thread.

**Comment by vigna** [comment]
Well of course adding can be a problem, too, if it causes rehashing. 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by shevek** [comment]
I suspect this was caused by a lack of a happen-before relationship between our thread-pool and following single-threaded code. Thank you for the help. Closing, and will notify if we ever see it again.
