### ISSUE TITLE
Build failure when TEST=1 (m.rehash())

### ISSUE THREAD

**Issue by pburka** [vigna/fastutil#74]
When I try to build from head with ASSERT=1, I get errors like the following from javac:

    [javac] fastutil/src/it/unimi/dsi/fastutil/ints/Int2IntLinkedOpenHashMap.java:2878: error: method rehash in class Int2IntLinkedOpenHashMap cannot be applied to given types;
    [javac] 	 m.rehash();
    [javac] 	  ^
    [javac]   required: int
    [javac]   found: no arguments
    [javac]   reason: actual and formal argument lists differ in length

drv/OpenHashSet.drv#2396, drv/OpenHashBigSet.drv#1319, and drv/OpenHashMap.drv#3343 call rehash with no arguments, which isn't valid. Their goal is not immediately obvious to me, so I'm not sure what the fix ought to be.

**Comment by vigna** [comment]
> On 25 Jun 2017, at 20:06, Peter Burka <notifications@github.com> wrote:
> 
> When I try to build from head with ASSERT=1, I errors like the following from javac:
> 
> [javac] fastutil/src/it/unimi/dsi/fastutil/ints/Int2IntLinkedOpenHashMap.java:2878: error: method rehash in class Int2IntLinkedOpenHashMap cannot be applied to given types;
> [javac] 	 m.rehash();
> [javac] 	  ^
> [javac]   required: int
> [javac]   found: no arguments
> [javac]   reason: actual and formal argument lists differ in length
> 
> drv/OpenHashSet.drv#2396 and drv/OpenHashBitSet#1319 call rehash with no arguments, which isn't valid. Their goal is not immediately obvious to me, so I'm not sure what the fix ought to be.

Oh well. I removed the method and forgot to test with asserts. Please remove all such calls. It's fixed for the next release.

Ciao,

					seba
