### ISSUE TITLE
new IntAVLTreeSet().subSet(10, 20).subSet(5, 25) fails to throw exception

### ISSUE THREAD

**Issue by pburka** [vigna/fastutil#75]
While working on some unit tests for `NavigableSet`, I discovered an error in the implementation of `AVLTreeSet.Subset.subSet`. According to [the Java spec](https://docs.oracle.com/javase/8/docs/api/java/util/SortedSet.html#subSet-E-E-), subSet should throw

> IllegalArgumentException - if fromElement is greater than toElement; or _if this set itself has a restricted range, and fromElement or toElement lies outside the bounds of the range_

However, [the implementation](https://github.com/pburka/fastutil/blob/master/drv/AVLTreeSet.drv#L1259) of `AVLTreeSet.Subset.subSet` doesn't do that -- it clips the range if `fromElement` or `toElement` are out of bounds.

I've confirmed that `java.util.TreeSet` does have the described behavior, with the caveat that it permits `toElement` to be equal to the top of the (exclusive) range.

I suspect that other `SortedSet` and `SortedMap` implementations in fastutil have the same bug. Unfortunately, fixing this could cause working programs to start throwing an exception.

**Comment by vigna** [comment]
> On 6 Jul 2017, at 02:19, Peter Burka <notifications@github.com> wrote:
> 
> While working on some unit tests for NavigableSet, I discovered an error in the implementation of AVLTreeSet.Subset.subSet. According to the Java spec, subSet should throw
> 
> IllegalArgumentException - if fromElement is greater than toElement; or if this set itself has a restricted range, and fromElement or toElement lies outside the bounds of the range
> 
> However, the implementation of AVLTreeSet.Subset.subSet doesn't do that -- it clips the range if fromElement or toElement are out of bounds.
> 
> I've confirmed that java.util.TreeSet does have the described behavior, with the caveat that it permits toElement to be equal to the top of the (exclusive) range.

I really think this is documented somewhere. I'm trying to find where, exactly :).

Ciao,

					seba

**Comment by shevek** [comment]
I think this hinges on whether AVLTreeSet.Subset is defined to have a "restricted range" - if we know that as the static type, then it has, but we could also consider it to be just an IntSet, at which point it does not have a restricted range, and the exception would be an unexpected annoyance.

I'm a little surprised by the behaviour of j.u.TreeMap, as if I ask any mathematician for the set of integers greater than 10 which are also greater than 5, he would not scream "IllegalArgumentException" at me. A more sensible response to the degenerate case would be to 'return this', and not allocate a new object.

I'd like to argue that this bug be considered invalid against fastutil.
