### ISSUE TITLE
Empty ArrayList should not allocate an array

### ISSUE THREAD

**Issue by orionll** [vigna/fastutil#85]
Hi, I'm new to fastutil and I noticed that the following code allocates an unnecessary int[16] array:

```
IntList list = new IntArrayList();
System.out.println(list);
```

I think a new `IntArrayList` should be initialized with a constant array of size 0 (like in java.util.ArrayList).

**Comment by vigna** [comment]
But then adding an element would cause a reallocation. If you want an immutable empty list that'll stay empty, use IntLists.EMPTY_LIST.

**Comment by orionll** [comment]
I think you miss the point. The number of allocations will be the same. You just postpone the allocation to the moment when you actually start adding elements to the list. But if you don't add any elements, your allocation will never occur. The same strategy is used in `java.util.ArrayList`.

Example:
```
int size = ... // unknown in compile time
IntList list = new IntArrayList();
for (int i = 0; i < size; i++) {
    list.add(i);
}
return list;
```
If size is 0, no array allocation will happen.

**Comment by leventov** [comment]
I support @orionll, it seems to me that the issue is valid. The same optimization is implemented in JDK.

**Comment by orionll** [comment]
Ping

**Comment by vigna** [comment]
OK I'm looking into that. Sorry I've been a bit busy...

**Comment by vigna** [comment]
Implemented in 8.2.0.

**Comment by orionll** [comment]
Great! Looking forward to see this in Central.

**Comment by vigna** [comment]
> On 28 May 2018, at 16:21, Zheka Kozlov <notifications@github.com> wrote:
> 
> Great! Looking forward to see this in Central.
> 

Give it an hour or so...

Ciao,

					seba
