### ISSUE TITLE
Introduce IntList.concat

### ISSUE THREAD

**Issue by blasd** [vigna/fastutil#87]
Hello,

Would you consider introducing a way to concat XXXList, like Guava Ints.concat but for IntList?

I'm working on compressed int array implementations and I use fastutil as abstraction layer. It would be nice to have the ability to concat multiple IntList (each with a different compression scheme).

Thanks

**Comment by vigna** [comment]
> On 30 Nov 2017, at 11:09, Benoit Lacelle <notifications@github.com> wrote:
> 
> Hello,
> 
> Would you consider introducing a way to concat XXXList, like Guava Ints.concat but for IntList?
> 
> I'm working on compressed int array implementations and I use fastutil as abstraction layer. It would be nice to have the ability to concat multiple IntList (each with a different compression scheme).

OK... but why don't you addAll()? Ints.concat() exists because arrays have no methods.

Ciao,

					seba

**Comment by blasd** [comment]
I can not use .addAll as each IntList is associated to a different compression scheme.

More specifically, I have a custom CompressedIntList which implements IntList. In some situation, I want to concatenate such an instance with a FastUtil IntArrayList (typically when the compression scheme gives poor result).

Referring to Ints.concat was not relevant I would expect each IntList to remain unchanged.

My need is maybe too much specific. For now, I live with:

    public class ConcatIntList extends AbstractIntList {

	protected final List<IntList> intLists;

	public ConcatIntList(IntList... intLists) {
		this(Arrays.asList(intLists));
	}

	public ConcatIntList(List<IntList> intLists) {
		this.intLists = intLists;
	}

	@Override
	public int getInt(final int index) {
		Iterator<IntList> it = intLists.iterator();

		int previousSize = 0;

		while (it.hasNext()) {
			IntList next = it.next();
			int size = next.size();

			if (index >= previousSize + size) {
				previousSize += size;
				continue;
			} else {
				return next.getInt(index - previousSize);
			}
		}

		throw new ArrayIndexOutOfBoundsException("index=" + index + " while size=" + size());
	}

	@Override
	public int size() {
		return intLists.stream().mapToInt(IntList::size).sum();
	}

    }
Thanks

**Comment by vigna** [comment]
> On 30 Nov 2017, at 12:25, Benoit Lacelle <notifications@github.com> wrote:
> 
> I can not use .addAll as each IntList is associated to a different compression scheme.
> 
> More specifically, I have a custom CompressedIntList which implements IntList. In some situation, I want to concatenate such an instance with a FastUtil IntArrayList (typically when the compression scheme gives poor result).
> 
> Referring to Ints.concat was not relevant I would expect each IntList to remain unchanged.

Sorry--I completely misunderstood your point. You want an object that exposes a sequence of lists as a single list. Correct? Should it be immutable?

Ciao,

					seba

**Comment by vigna** [comment]
> On 30 Nov 2017, at 12:25, Benoit Lacelle <notifications@github.com> wrote:
> 
> I can not use .addAll as each IntList is associated to a different compression scheme.
> 
> More specifically, I have a custom CompressedIntList which implements IntList. In some situation, I want to concatenate such an instance with a FastUtil IntArrayList (typically when the compression scheme gives poor result).
> 
> Referring to Ints.concat was not relevant I would expect each IntList to remain unchanged.

BTW, if the liste will not change you should store the prefix sum of the lists sizes, so you can scan it quickly to find the right list, or even switch to a binary search if there are several lists involved.

Implementing this in the general case is a bit tricky because there's no way to guarantee that the list length won't change (with arrays, it's fixed). So why it is safe to expose a bunch of arrays as a single array, I think there's no way to expose safely a bunch of lists as a list and keep the prefix sum around.

So maybe what you're doing is the best. I don't see how I could improve on your implementation.

Ciao,

					seba

**Comment by blasd** [comment]
Thanks for reviewing!
