### ISSUE TITLE
Please add Automatic-Module-Name manifest entries

### ISSUE THREAD

**Issue by io7m** [vigna/fastutil#89]
Hello!

It'd be great if `fastutil` published `Automatic-Module-Name` entries in the jar manifest for each module. This would assign the modules stable names to be used in (modular) Java 9 projects.

Of course, full modularization would be better, but that'd involve generating a rather enormous `module-info.java` file to export all of the hundreds of packages.

**Comment by vigna** [comment]
Is that compatible with Java 8? Sorry but I'm entirely unfamiliar with the modularization feature.

**Comment by io7m** [comment]
Hi.

Yes, it's completely ignored on JDKs prior to 9. Essentially, it's a way of saying "This is the module name that I'll be using in the future if I ever modularize the code". It allows people to specify stable dependencies on your code from Java 9 projects without you actually having to publish full modules.

**Comment by io7m** [comment]
Thanks for merging that in.

Any chance you could push a new release?

**Comment by vigna** [comment]
Released with 8.2.0.

**Comment by io7m** [comment]
Thanks!

**Comment by io7m** [comment]
Hm, checking today, something seems to have gone wrong somewhere. The `8.2.0` jars don't seem to have the manifest header:

```
$ wget -O fastutil-8.2.0.jar http://search.maven.org/remotecontent?filepath=it/unimi/dsi/fastutil/8.2.0/fastutil-8.2.0.jar
--2018-05-28 21:53:52--  http://search.maven.org/remotecontent?filepath=it/unimi/dsi/fastutil/8.2.0/fastutil-8.2.0.jar
Proxy request sent, awaiting response... 200 OK
Length: 18800399 (18M) [application/java-archive]
Saving to: ‘fastutil-8.2.0.jar’

fastutil-8.2.0.jar                100%[============================================================>]  17.93M  1018KB/s    in 25s     

2018-05-28 21:54:17 (734 KB/s) - ‘fastutil-8.2.0.jar’ saved [18800399/18800399]

$ unzip -p fastutil-8.2.0.jar META-INF/MANIFEST.MF
Manifest-Version: 1.0
Bnd-LastModified: 1527515258573
Bundle-ManifestVersion: 2
Bundle-Name: it.unimi.dsi.fastutil
Bundle-SymbolicName: it.unimi.dsi.fastutil
Bundle-Version: 8.2.0
Created-By: 10.0.1 (Oracle Corporation)
Export-Package: it.unimi.dsi.fastutil;uses:="it.unimi.dsi.fastutil.ints,
 it.unimi.dsi.fastutil.longs";version="8.2.0",it.unimi.dsi.fastutil.bool
 eans;uses:="it.unimi.dsi.fastutil,it.unimi.dsi.fastutil.objects";versio
 n="8.2.0",it.unimi.dsi.fastutil.bytes;uses:="it.unimi.dsi.fastutil,it.u
 nimi.dsi.fastutil.booleans,it.unimi.dsi.fastutil.chars,it.unimi.dsi.fas
 tutil.doubles,it.unimi.dsi.fastutil.floats,it.unimi.dsi.fastutil.ints,i
 t.unimi.dsi.fastutil.longs,it.unimi.dsi.fastutil.objects,it.unimi.dsi.f
 astutil.shorts";version="8.2.0",it.unimi.dsi.fastutil.chars;uses:="it.u
 nimi.dsi.fastutil,it.unimi.dsi.fastutil.booleans,it.unimi.dsi.fastutil.
 bytes,it.unimi.dsi.fastutil.doubles,it.unimi.dsi.fastutil.floats,it.uni
 mi.dsi.fastutil.ints,it.unimi.dsi.fastutil.longs,it.unimi.dsi.fastutil.
 objects,it.unimi.dsi.fastutil.shorts";version="8.2.0",it.unimi.dsi.fast
 util.doubles;uses:="it.unimi.dsi.fastutil,it.unimi.dsi.fastutil.boolean
 s,it.unimi.dsi.fastutil.bytes,it.unimi.dsi.fastutil.chars,it.unimi.dsi.
 fastutil.floats,it.unimi.dsi.fastutil.ints,it.unimi.dsi.fastutil.longs,
 it.unimi.dsi.fastutil.objects,it.unimi.dsi.fastutil.shorts";version="8.
 2.0",it.unimi.dsi.fastutil.floats;uses:="it.unimi.dsi.fastutil,it.unimi
 .dsi.fastutil.booleans,it.unimi.dsi.fastutil.bytes,it.unimi.dsi.fastuti
 l.chars,it.unimi.dsi.fastutil.doubles,it.unimi.dsi.fastutil.ints,it.uni
 mi.dsi.fastutil.longs,it.unimi.dsi.fastutil.objects,it.unimi.dsi.fastut
 il.shorts";version="8.2.0",it.unimi.dsi.fastutil.ints;uses:="it.unimi.d
 si.fastutil,it.unimi.dsi.fastutil.booleans,it.unimi.dsi.fastutil.bytes,
 it.unimi.dsi.fastutil.chars,it.unimi.dsi.fastutil.doubles,it.unimi.dsi.
 fastutil.floats,it.unimi.dsi.fastutil.longs,it.unimi.dsi.fastutil.objec
 ts,it.unimi.dsi.fastutil.shorts";version="8.2.0",it.unimi.dsi.fastutil.
 io;uses:="it.unimi.dsi.fastutil.booleans,it.unimi.dsi.fastutil.bytes,it
 .unimi.dsi.fastutil.chars,it.unimi.dsi.fastutil.doubles,it.unimi.dsi.fa
 stutil.floats,it.unimi.dsi.fastutil.ints,it.unimi.dsi.fastutil.longs,it
 .unimi.dsi.fastutil.shorts";version="8.2.0",it.unimi.dsi.fastutil.longs
 ;uses:="it.unimi.dsi.fastutil,it.unimi.dsi.fastutil.booleans,it.unimi.d
 si.fastutil.bytes,it.unimi.dsi.fastutil.chars,it.unimi.dsi.fastutil.dou
 bles,it.unimi.dsi.fastutil.floats,it.unimi.dsi.fastutil.ints,it.unimi.d
 si.fastutil.objects,it.unimi.dsi.fastutil.shorts";version="8.2.0",it.un
 imi.dsi.fastutil.objects;uses:="it.unimi.dsi.fastutil,it.unimi.dsi.fast
 util.booleans,it.unimi.dsi.fastutil.bytes,it.unimi.dsi.fastutil.chars,i
 t.unimi.dsi.fastutil.doubles,it.unimi.dsi.fastutil.floats,it.unimi.dsi.
 fastutil.ints,it.unimi.dsi.fastutil.longs,it.unimi.dsi.fastutil.shorts"
 ;version="8.2.0",it.unimi.dsi.fastutil.shorts;uses:="it.unimi.dsi.fastu
 til,it.unimi.dsi.fastutil.booleans,it.unimi.dsi.fastutil.bytes,it.unimi
 .dsi.fastutil.chars,it.unimi.dsi.fastutil.doubles,it.unimi.dsi.fastutil
 .floats,it.unimi.dsi.fastutil.ints,it.unimi.dsi.fastutil.longs,it.unimi
 .dsi.fastutil.objects";version="8.2.0"
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Tool: Bnd-2.4.0.201411031536
```

**Comment by vigna** [comment]
Ok... can you check on github? I just merged in your pull request.  Maybe there's something else to do.

On May 28, 2018 10:54:45 PM GMT+02:00, Mark Raynsford <notifications@github.com> wrote:
>Hm, checking today, something seems to have gone wrong somewhere. The
>`8.2.0` jars don't seem to have the manifest header:
>
>```
>$ wget -O fastutil-8.2.0.jar
>http://search.maven.org/remotecontent?filepath=it/unimi/dsi/fastutil/8.2.0/fastutil-8.2.0.jar
>--2018-05-28 21:53:52-- 
>http://search.maven.org/remotecontent?filepath=it/unimi/dsi/fastutil/8.2.0/fastutil-8.2.0.jar
>Proxy request sent, awaiting response... 200 OK
>Length: 18800399 (18M) [application/java-archive]
>Saving to: ‘fastutil-8.2.0.jar’
>
>fastutil-8.2.0.jar               
>100%[============================================================>] 
>17.93M  1018KB/s    in 25s     
>
>2018-05-28 21:54:17 (734 KB/s) - ‘fastutil-8.2.0.jar’ saved
>[18800399/18800399]
>
>$ unzip -p fastutil-8.2.0.jar META-INF/MANIFEST.MF
>Manifest-Version: 1.0
>Bnd-LastModified: 1527515258573
>Bundle-ManifestVersion: 2
>Bundle-Name: it.unimi.dsi.fastutil
>Bundle-SymbolicName: it.unimi.dsi.fastutil
>Bundle-Version: 8.2.0
>Created-By: 10.0.1 (Oracle Corporation)
>Export-Package:
>it.unimi.dsi.fastutil;uses:="it.unimi.dsi.fastutil.ints,
>it.unimi.dsi.fastutil.longs";version="8.2.0",it.unimi.dsi.fastutil.bool
>eans;uses:="it.unimi.dsi.fastutil,it.unimi.dsi.fastutil.objects";versio
>n="8.2.0",it.unimi.dsi.fastutil.bytes;uses:="it.unimi.dsi.fastutil,it.u
>nimi.dsi.fastutil.booleans,it.unimi.dsi.fastutil.chars,it.unimi.dsi.fas
>tutil.doubles,it.unimi.dsi.fastutil.floats,it.unimi.dsi.fastutil.ints,i
>t.unimi.dsi.fastutil.longs,it.unimi.dsi.fastutil.objects,it.unimi.dsi.f
>astutil.shorts";version="8.2.0",it.unimi.dsi.fastutil.chars;uses:="it.u
>nimi.dsi.fastutil,it.unimi.dsi.fastutil.booleans,it.unimi.dsi.fastutil.
>bytes,it.unimi.dsi.fastutil.doubles,it.unimi.dsi.fastutil.floats,it.uni
>mi.dsi.fastutil.ints,it.unimi.dsi.fastutil.longs,it.unimi.dsi.fastutil.
>objects,it.unimi.dsi.fastutil.shorts";version="8.2.0",it.unimi.dsi.fast
>util.doubles;uses:="it.unimi.dsi.fastutil,it.unimi.dsi.fastutil.boolean
>s,it.unimi.dsi.fastutil.bytes,it.unimi.dsi.fastutil.chars,it.unimi.dsi.
>fastutil.floats,it.unimi.dsi.fastutil.ints,it.unimi.dsi.fastutil.longs,
>it.unimi.dsi.fastutil.objects,it.unimi.dsi.fastutil.shorts";version="8.
>2.0",it.unimi.dsi.fastutil.floats;uses:="it.unimi.dsi.fastutil,it.unimi
>.dsi.fastutil.booleans,it.unimi.dsi.fastutil.bytes,it.unimi.dsi.fastuti
>l.chars,it.unimi.dsi.fastutil.doubles,it.unimi.dsi.fastutil.ints,it.uni
>mi.dsi.fastutil.longs,it.unimi.dsi.fastutil.objects,it.unimi.dsi.fastut
>il.shorts";version="8.2.0",it.unimi.dsi.fastutil.ints;uses:="it.unimi.d
>si.fastutil,it.unimi.dsi.fastutil.booleans,it.unimi.dsi.fastutil.bytes,
>it.unimi.dsi.fastutil.chars,it.unimi.dsi.fastutil.doubles,it.unimi.dsi.
>fastutil.floats,it.unimi.dsi.fastutil.longs,it.unimi.dsi.fastutil.objec
>ts,it.unimi.dsi.fastutil.shorts";version="8.2.0",it.unimi.dsi.fastutil.
>io;uses:="it.unimi.dsi.fastutil.booleans,it.unimi.dsi.fastutil.bytes,it
>.unimi.dsi.fastutil.chars,it.unimi.dsi.fastutil.doubles,it.unimi.dsi.fa
>stutil.floats,it.unimi.dsi.fastutil.ints,it.unimi.dsi.fastutil.longs,it
>.unimi.dsi.fastutil.shorts";version="8.2.0",it.unimi.dsi.fastutil.longs
>;uses:="it.unimi.dsi.fastutil,it.unimi.dsi.fastutil.booleans,it.unimi.d
>si.fastutil.bytes,it.unimi.dsi.fastutil.chars,it.unimi.dsi.fastutil.dou
>bles,it.unimi.dsi.fastutil.floats,it.unimi.dsi.fastutil.ints,it.unimi.d
>si.fastutil.objects,it.unimi.dsi.fastutil.shorts";version="8.2.0",it.un
>imi.dsi.fastutil.objects;uses:="it.unimi.dsi.fastutil,it.unimi.dsi.fast
>util.booleans,it.unimi.dsi.fastutil.bytes,it.unimi.dsi.fastutil.chars,i
>t.unimi.dsi.fastutil.doubles,it.unimi.dsi.fastutil.floats,it.unimi.dsi.
>fastutil.ints,it.unimi.dsi.fastutil.longs,it.unimi.dsi.fastutil.shorts"
>;version="8.2.0",it.unimi.dsi.fastutil.shorts;uses:="it.unimi.dsi.fastu
>til,it.unimi.dsi.fastutil.booleans,it.unimi.dsi.fastutil.bytes,it.unimi
>.dsi.fastutil.chars,it.unimi.dsi.fastutil.doubles,it.unimi.dsi.fastutil
>.floats,it.unimi.dsi.fastutil.ints,it.unimi.dsi.fastutil.longs,it.unimi
> .dsi.fastutil.objects";version="8.2.0"
>Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
>Tool: Bnd-2.4.0.201411031536
>```
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/vigna/fastutil/issues/89#issuecomment-392602011

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by io7m** [comment]
It actually wasn't my PR, but I'll take a look now.

**Comment by vigna** [comment]
Oh sorry...

On May 28, 2018 11:05:10 PM GMT+02:00, Mark Raynsford <notifications@github.com> wrote:
>It actually wasn't my PR, but I'll take a look now.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/vigna/fastutil/issues/89#issuecomment-392603278

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by io7m** [comment]
It's no trouble, I have an interest in making sure this works. It would have been my PR if @kashike hadn't beat me to it!

**Comment by io7m** [comment]
OK, I've verified that if I do `make sources && ant jar`, that results in a jar file that looks like this:

```
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.7
Created-By: 10.0.1+10 (Oracle Corporation)
Automatic-Module-Name: it.unimi.dsi.fastutil

```

But I notice a distinct lack of OSGi metadata in there... Is there some other step you normally run when you make a release?

**Comment by vigna** [comment]
> On 28 May 2018, at 23:16, Mark Raynsford <notifications@github.com> wrote:
> 
> 
> 
> But I notice a distinct lack of OSGi metadata in there... Is there some other step you normally run when you make a release?
> 

So, the procedure for building the jars for the tar distribution and for building them for staging into Sonatype is different. I think whoever did the OSGI thing did it in the staging part, and whoever did the module thing did it in the distribution part. So I'm trying to figure out to make the module think in the staging part, too...

Ciao,

					seba

**Comment by vigna** [comment]
So, it seems like fastutil.bnd should include the automatic module thing. Let me try to temporarily stage a new jar and see whether the module stuff gets in.

**Comment by vigna** [comment]
It seems like it's in. Please wait a couple of hours and try 8.2.1 on Central.

**Comment by io7m** [comment]
Yep, can confirm, `8.2.1` has the `Automatic-Module-Name` header. Thanks very much!
