### ISSUE TITLE
Underlying arrays should be allocated lazily

### ISSUE THREAD

**Issue by oehme** [vigna/fastutil#90]
In my use case, many collections are empty. This wastes a large amount of memory if I just replace usages of java.util.HashMap with OpenHashMap. So I either have to add lazy init code around the whole collection or make the initial size tiny. It would be great if by default the fastutil collections would use a shared empty table and only grow on first use. Is there a specific reason you didn't go for this approach, similar to what JDK and Trove do?

**Comment by vigna** [comment]
This means an additional test for every operation, but if you keep a null into the table pointer, or an empty fixed array. 

If you're OK with that test, probably a wrapper is a good idea. You can even subclass, in fact, so you don't have an additional object around.

**Comment by oehme** [comment]
The subclassing solution sounds like the way to go for my case, thank you for pointing me in the right direction.
