### ISSUE TITLE
Slow performance of ObjectOpenHashSet

### ISSUE THREAD

**Issue by shevek** [vigna/fastutil#91]
Given that ObjectOpenHashSet uses a masking strategy and discards the high bits of the hashCode(), the mix() strategy isn't really adequate, and values which differ only in high bits tend to hash consecutively. One would do well to take `h ^ (h >>> 16)` to increase entropy in the low bits.

**Comment by shevek** [comment]
One could also use Integer.rotateRight(), with which I am currently experimenting. I wish I could rotate right by the number of 1 bits in mask, but I don't have access to that.

**Comment by vigna** [comment]
Or maybe extract the starting position with a shift?

**Comment by shevek** [comment]
Having now played somewhat with CustomHashSet implementations, suffering the same issue, perhaps another answer is to provide a standard set of mix() implementations for primitive types. e.g. for int (I haven't checked or proven the utility of this, it's my first guess) i ^ (i >>> 2) ^ (i >>> 4) ^ (i >>> 8) ^ (i >>> 16) aims to make the low bits maximally useful.

**Comment by shevek** [comment]
See http://www.burtleburtle.net/bob/hash/integer.html

**Comment by vigna** [comment]
Did you try what happens just adding h ^ (h >>> 16) to the integer hashing?

**Comment by shevek** [comment]
I did, and the cascade isn't good enough. If I have a set of consecutive integers between N and N+2000 then `h ^ (h >>> 16)` doesn't make them nonconsecutive, so hashing STILL degenerates to linear search. I used the Thomas Wang function, with its documented cascade properties, and my life is now happier, richer, faster, more profitable, more successful, and a new life awaits me in the off-world colonies.

I had a vague memory that JDK's HashMap used to use a simple Mersenne twister in the hash() function, but it seems not to do so in 1.8+; that was what started me on this road. But it's a list-hash not an open hash, so the linear degeneration for consecutive values (a longstanding criticism of String) doesn't apply.

Even if this isn't implemented in the default, it may be worth providing a default Strategy implementation for the primitive types which does do bit mixing, so people can trivially be steered towards OpenCustom maps.

FWIW my performance increase was 1000x.

**Comment by vigna** [comment]
I don't know even why I'm answering—what you're writing doesn't make any sense. Why would you put integers in an ObjectOpenHashMap? How can mix() not work, given that it mixes with a multiplication?

Provide a unit test and reopen if you have one.

**Comment by shevek** [comment]
The hash codes, which are masked to the low bits are integers. If the hash codes are sequential, e.g. if they're database-backed objects whose hashCodes are their database ids, ObjectOpenHashMap (equivalently IntOpenHashMap for raw integers) has terrible performance. Will put up test case when I have time. For now, using Custom variants solves my problem.
