### ISSUE TITLE
ArrayIndexOutOfBoundsException when trying to remove items in OpenHashMap

### ISSUE THREAD

**Issue by maxdemarzi** [vigna/fastutil#92]
I am getting an error trying to load up an open hash map with 100 values and then removing them one by one in an iterator. Am I doing something wrong here? What's the right way to do this?
```
java.lang.ArrayIndexOutOfBoundsException: 36

	at it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap$MapIterator.nextEntry(Object2IntOpenHashMap.java:851)
	at it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap$ValueIterator.nextInt(Object2IntOpenHashMap.java:1182)
	at it.unimi.dsi.fastutil.ints.IntIterator.next(IntIterator.java:54)
	at it.unimi.dsi.fastutil.ints.IntIterator.next(IntIterator.java:33)
```
The error gets thrown on the line:

```
 int i = iterator.next();
```
of this test:

```
@Test
    public void shouldRemoveWithoutException() {
        Object2IntOpenHashMap<String> objects = new Object2IntOpenHashMap<>();
        for (int i = 0; i < 100; i++) {
            objects.put(String.valueOf(i), i);
        }

        final Iterator<Integer> iterator = objects.values().iterator();
        assertTrue(iterator.hasNext());
        while (iterator.hasNext()) {
            int i = iterator.next();
            objects.removeInt(String.valueOf(i));
        }
        assertFalse(iterator.hasNext());
    }
```

**Comment by vigna** [comment]
> On 11 Jan 2018, at 07:31, Max De Marzi <notifications@github.com> wrote:
> 
> I am getting an error trying to load up an open hash map with 100 values and then removing them one by one in an iterator. Am I doing something wrong here? What's the right way to do this?

What you're doing is totally illegal. You cannot modify a collection while you iterate over it.

You can, however, remove the very last element returned by an iterator using Iterator.remove().

Ciao,

					seba

**Comment by maxdemarzi** [comment]
```iterator.remove();``` instead of ```objects.removeInt(String.valueOf(i));``` works, but this simple test doesn't capture that in the app, I lose direct access to the iterator.

The error happens when it gets resized and in the _nextEntry_ method of the MapIterator the **pos** is greater than the length of keys.

Couldn't an if statement setting **pos** to the length of keys if it is greater before the loop ```if (--pos < 0) {``` starts allow it? It's "illegal" by convention sure, but since we have access to the mechanism finding the next item here, couldn't it be made legal?

**Comment by incaseoftrouble** [comment]
Making it legal would break a lot of things. Then, all other implementations would have to support it, too. Also, this would break compatibility with Java's standard counterparts. Iterators are not supposed to handle a modification, simply because this is notoriously hard / impossible to accomplish. For example, when `pos` isn't out of bounds after a resize (which might re-order entries) you might even get an element twice or never.

**Comment by maxdemarzi** [comment]
Yeah, you guys are right. I was trying to get away with something. I think I'll pump the ints into a roaringbitmap as my clone of the data and iterate over that.

**Comment by incaseoftrouble** [comment]
Shameless self-advertisement: If you are working with medium-sized sets of natural numbers, you could have a look at my (naturals-util)[http://github.com/incaseoftrouble/naturals-util/] library. It basically wraps `BitSet`, `SparseBitSet`, etc. into `IntSet` (with some more bulk operations). There are also some more utilities that might come in handy.
