### ISSUE TITLE
ObjectOpenCustomHashSet should take Strategy<? super K> not Strategy<K>

### ISSUE THREAD

**Issue by shevek** [vigna/fastutil#93]
It's perfectly valid to use a Strategy<Object> in any custom-hash set, since K is only ever an argument not a return type. But I can't because the constructor parameter is Strategy<K>. It should be Strategy<? super K>.

**Comment by vigna** [comment]
I think you're right. I can see no negative consequences at this point.

**Comment by vigna** [comment]
Fixed for 8.2.2. Sorry it took so long... if you send me at sebastiano.vigna@gmail.com your real name I'll thank you in the CHANGES file.
