### ISSUE TITLE
Primitive streams

### ISSUE THREAD

**Issue by benmccann** [vigna/fastutil#98]
`DoubleArrayList.stream()` returns a `Stream<Double>` which converts from primitive to Object. It would be nice if it returned a `DoubleStream` which is a stream of primitives. If the existing `stream` method cannot be changed then it would be nice to add a new method which returns the primitive `DoubleStream`

**Comment by vigna** [comment]
Yeah, that would be a good thing. We're introducing Java 8 stuff a bit at a time, when we have time. Would you beta test an implementation in case?

**Comment by incaseoftrouble** [comment]
Note: The primitive streams only exist for the "base" primitive types (`int`, `double`, `long`).

**Comment by vigna** [comment]
That's probably something that would be worth implementing everywhere. Looks like a lot of methods tho.

**Comment by benmccann** [comment]
There are only three primitive stream implementations (`DoubleStream`, `IntStream`, `LongStream`), so I'm imagining there would be three methods. I'm not sure when you say there would be "a lot of methods" if three is a lot or if you were envisioning other methods?

**Comment by vigna** [comment]
> On 2 Apr 2018, at 18:42, Ben McCann <notifications@github.com> wrote:
> 
> There are only three primitive stream implementations (DoubleStream, IntStream, LongStream), so I'm imagining there would be three methods. I'm not sure when you say there would be "a lot of methods" if three is a lot or if you were envisioning other methods?

We have to return a Stream. DoubleStream etc. has a billion methods. Someone will have to write them :).

Ciao,

					seba

**Comment by benmccann** [comment]
Do you have to actually implement `DoubleStream`? You might be able to call `java.util.StreamSupport.doubleStream` to create the `Stream`

**Comment by vigna** [comment]
OMG, I didn't even know that thing existed. Thanks!

**Comment by lwhite1** [comment]
@vigna When you implement this I would be happy to beta test.  

And, thanks for the awesome library.

**Comment by techsy730** [comment]
As I mentioned in a dup bug I filed, https://github.com/vigna/fastutil/issues/116, I am working on this.
It's not done yet, but the basics are implemented.
https://github.com/techsy730/fastutil/tree/spliterators

**Comment by vigna** [comment]
The current commit has streams, so anybody interested please test the implementation—comments are welcome.
