### ISSUE TITLE
consider protocol-buffers style number compression

### ISSUE THREAD

**Issue by berndhopp** [vigna/fastutil#99]
protocol buffers has an interesting way of number compression called [varints](https://developers.google.com/protocol-buffers/docs/encoding#varints) which is especially useful for scenarios with a lot of small numbers ( compared to e.g. Integer.MAX_VALUE), like database ids.
My guess is that in many scenarios, IntSets based on Varints could turn out to consume only half the memory that the current implementations do.

**Comment by simlu** [comment]
How does this compare to other compression, e.g. simple gzip? What advantages / penalties would this have?

**Comment by berndhopp** [comment]
varints are especially suited for sets where the numbers are not randomly distributed but mostly small. in this case, for example 127 would fit in one byte, 128 to 2 ^ 14 fits in two bytes and so forth. The penalty is that if you have randomly distributed numbers or numbers that are generally very large ( larger than Integer.MAX_VALUE / 2 that is ), then you will end up consuming more memory. So one needs to be aware that this would not be a general-purpose collection but a specialized one.

**Comment by vigna** [comment]
That's unfeasible. One thing is to use variable-length byte codes for storing a structure, another thing for a live structure.
